build.gradle
src/main/java/org/keynote/godtools/android/SettingsPW.java
src/main/java/org/keynote/godtools/android/business/GTLanguage.java
src/main/java/org/keynote/godtools/android/utils/WordUtils.java

Removed commons lang as clean up task.

Removed apache string libraries to reduce size and prevent multidex

---

godtools-tract-renderer/src/main/java/org/cru/godtools/tract/model/Page.java

Instead, we track if a rebind was requested, and trigger the rebind after we finish our current bind pass

prevent recursion which caused data model corruption

---

app/build.gradle

This will aid in testing proguard related issues

make it a bit easier to enable proguard for debug builds

---

app/src/main/res/layout/list_item_language.xml

This came out of some feedback and interaction with Ann and Eric

Remove remove language action

---

library/tract-renderer/src/main/java/org/cru/godtools/tract/activity/TractActivity.java
library/tract-renderer/src/main/java/org/cru/godtools/tract/model/Manifest.java

- Translates code from kgp-us to kgp for "Know God Personally"
- Adds page number to URLS for i > 0
- But no page numbers for US KGP

Gt 421 us kgp share link

---

build.gradle
library/analytics/build.gradle
library/analytics/proguard-rules-adobe.pro
library/analytics/proguard-rules-snowplow.pro
library/analytics/src/main/java/org/cru/godtools/analytics/AnalyticsService.java
library/base-ui/src/main/java/org/cru/godtools/base/ui/activity/BaseActivity.java
library/everystudent/src/main/java/org/cru/godtools/everystudent/EveryStudent.java
library/everystudent/src/main/java/org/cru/godtools/everystudent/EveryStudentView.java

This PR sets up the initial tracking for SnowPlow. It should track screen views and application crashes, as well as the EveryStudent search.

GT-461 - Setup Snowplow Tracker

---

library/tract-renderer/src/main/java/org/cru/godtools/tract/model/CallToAction.java

Use control-color attribute to color the arrow.
Falls back to page.primary-color and manifest.primary-color in that order

Gt 379 call to action custom color

---

library/analytics/build.gradle

Update from snowplow.cru.org to s.cru.org.

GT-461 - New DNS

---

library/analytics/src/main/java/org/cru/godtools/analytics/AdobeAnalyticsService.java
library/analytics/src/main/java/org/cru/godtools/analytics/AnalyticsService.java
library/analytics/src/main/java/org/cru/godtools/analytics/DefaultAnalyticsService.java
library/analytics/src/main/java/org/cru/godtools/analytics/GoogleAnalyticsService.java
library/analytics/src/main/java/org/cru/godtools/analytics/SnowplowAnalyticsService.java
library/everystudent/src/main/java/org/cru/godtools/everystudent/EveryStudent.java
library/tract-renderer/src/main/java/org/cru/godtools/tract/activity/TractActivity.java
library/tract-renderer/src/main/java/org/cru/godtools/tract/adapter/ManifestPagerAdapter.java
library/tract-renderer/src/main/java/org/cru/godtools/tract/model/Card.java
library/tract-renderer/src/main/java/org/cru/godtools/tract/model/Page.java

Also separate lifecycle collection from state tracking

Track tract card views within Adobe Analytics

---

app/src/main/java/org/cru/godtools/GodToolsApplication.java
library/analytics/src/main/java/org/cru/godtools/analytics/DefaultAnalyticsService.java
library/analytics/src/main/java/org/cru/godtools/analytics/EventBusAnalyticsHelper.java

Create a JDK Proxy to eliminate code duplication

Analytics service proxy

---

library/tract-renderer/src/main/res/layout/activity_tract.xml

I love simple changes like this :)

keep the screen on while presenting a tract

---

library/download-manager/src/main/java/org/cru/godtools/download/manager/GodToolsDownloadManager.java

Download indicator fix

---

library/analytics/src/main/java/org/cru/godtools/analytics/AdobeAnalyticsService.java
library/analytics/src/main/java/org/cru/godtools/analytics/AnalyticsService.java
library/analytics/src/main/java/org/cru/godtools/analytics/GoogleAnalyticsService.java
library/tract-renderer/src/main/java/org/cru/godtools/tract/activity/TractActivity.java
library/tract-renderer/src/main/java/org/cru/godtools/tract/model/Button.java

Actions tracked
- Share tract
- clicking URL buttons
- toggling between languages when viewing a tract

Track several Analytics actions

---

app/src/debug/res/values/misc.xml
app/src/main/AndroidManifest.xml
app/src/main/res/values/misc.xml

we use userPortrait for release and user for dev builds. The wider rotation support allows testing for limits of screen layout

update the enforced screenOrientation

---

app/src/main/res/drawable/ic_tool_checkmark.xml
app/src/main/res/layout/list_item_tool_card.xml
app/src/main/res/values/styles_tools.xml

For styles I try to keep layout/positioning within the view XML, but extract other style properties to the styles xml

tweak some styles for the parallel language, and extract the styling to a common style

---

app/build.gradle
app/src/main/java/org/cru/godtools/adapter/ToolsAdapter.java
app/src/main/java/org/keynote/godtools/android/fragment/ToolsFragment.java
app/src/main/res/layout/list_item_tool_card.xml
app/src/main/res/values/styles_tools.xml

changes:
- make title bold
- make height of card dynamic

Tool card tweaks

---

library/tract-renderer/src/main/java/org/cru/godtools/tract/model/Link.java
library/tract-renderer/src/main/res/layout/tract_content_link.xml

This provides more touchable area for the link

add a minHeight to content links

---

feature/tract/src/main/AndroidManifest.xml
library/tract-renderer/src/main/java/org/cru/godtools/tract/Constants.java
library/tract-renderer/src/main/java/org/cru/godtools/tract/activity/TractActivity.java

This will allow the try now button to attempt to use the device language

add a useDeviceLanguage parameter that will attempt to use the device language for a deep link

---

ui/tract-renderer/src/main/res/layout/page_manifest_page.xml
ui/tract-renderer/src/main/res/layout/tract_call_to_action.xml
ui/tract-renderer/src/main/res/layout/tract_header.xml

split up parts of the page layout to better facilitate required RTL changes

split up layout

---

ui/tract-renderer/src/main/java/org/cru/godtools/tract/activity/ImmersiveActivity.java

Any interaction with the phone would disable immersive mode in JellyBean

disable immersive mode before KitKat

---

app/src/main/AndroidManifest.xml
feature/tract/src/main/AndroidManifest.xml
ui/tract-renderer/src/main/AndroidManifest.xml

Maybe some day I'll have addressed all the play store release process bugs

Instant app fixes

---

library/analytics/src/main/java/org/cru/godtools/analytics/SnowplowAnalyticsService.java

- Make SnowPlow executor single threaded to guarantee execution order
- utilize Subject object to inject custom keys into events

include content scoring URL as "url" parameter for SnowPlow.

---

ui/tract-renderer/src/main/java/org/cru/godtools/tract/model/Button.java
ui/tract-renderer/src/main/java/org/cru/godtools/tract/model/Card.java
ui/tract-renderer/src/main/java/org/cru/godtools/tract/model/Content.java
ui/tract-renderer/src/main/java/org/cru/godtools/tract/model/DeviceType.java
ui/tract-renderer/src/main/java/org/cru/godtools/tract/model/Form.java
ui/tract-renderer/src/main/java/org/cru/godtools/tract/model/Hero.java
ui/tract-renderer/src/main/java/org/cru/godtools/tract/model/Image.java
ui/tract-renderer/src/main/java/org/cru/godtools/tract/model/Input.java
ui/tract-renderer/src/main/java/org/cru/godtools/tract/model/Link.java
ui/tract-renderer/src/main/java/org/cru/godtools/tract/model/Modal.java
ui/tract-renderer/src/main/java/org/cru/godtools/tract/model/Paragraph.java
ui/tract-renderer/src/main/java/org/cru/godtools/tract/model/Tab.java
ui/tract-renderer/src/main/java/org/cru/godtools/tract/model/Tabs.java
ui/tract-renderer/src/main/java/org/cru/godtools/tract/model/Text.java

Dependent on https://github.com/CruGlobal/mobile-content-api/pull/156
We are working on deploying an updated web version of the GodTools tracts. Due to differences in how we want to display content we want to be able to restrict certain pieces of content to certain platforms only. This PR updates the Android app to know about the restrictTo attribute and correctly apply it to the content.

restrictTo support

---

library/analytics/src/main/java/org/cru/godtools/analytics/SnowplowAnalyticsService.java
library/analytics/src/main/java/org/cru/godtools/analytics/model/AnalyticsActionEvent.java
library/analytics/src/main/java/org/cru/godtools/analytics/model/AnalyticsBaseEvent.java
library/analytics/src/main/java/org/cru/godtools/analytics/model/AnalyticsScreenEvent.java

[Jira](https://jira.cru.org/browse/GT-515)

Send page title to Snowplow for tracking

---

app/build.gradle
app/proguard-searchview.pro
app/src/main/java/org/keynote/godtools/android/fragment/LanguagesFragment.java
app/src/main/res/drawable/ic_ab_search.xml
app/src/main/res/menu/fragment_language_search.xml

We were getting NPEs for this logic when it went to release. See: https://fabric.io/cru/android/apps/org.keynote.godtools.android/issues/5b8ea53a6007d59fcdb4ea87?time=last-ninety-days

Fix search view

---

ui/base-tool/src/main/res/values/styles.xml

https://jira.cru.org/browse/GT-512

GT 512 Duplicate action bars

---

library/analytics/src/main/java/org/cru/godtools/analytics/AdobeAnalyticsService.java
library/analytics/src/main/java/org/cru/godtools/analytics/AnalyticsService.java
library/analytics/src/main/java/org/cru/godtools/analytics/model/AnalyticsBaseEvent.java
library/analytics/src/main/java/org/cru/godtools/analytics/model/AnalyticsScreenEvent.java
ui/everystudent/src/main/java/org/cru/godtools/everystudent/EveryStudent.java
ui/everystudent/src/main/java/org/cru/godtools/everystudent/EveryStudentView.java
ui/everystudent/src/main/java/org/cru/godtools/everystudent/analytics/model/EveryStudentAnalyticsScreenEvent.java
ui/tract-renderer/src/main/java/org/cru/godtools/tract/analytics/model/TractPageAnalyticsScreenEvent.java

This PR covers the missing Adobe Analytics tags

Updated the Adobe Analytics call to include missing requirements.

---

library/base/src/main/java/org/cru/godtools/base/util/PriorityRunnable.java
library/download-manager/src/main/java/org/cru/godtools/download/manager/GodToolsDownloadManager.java
ui/articles-aem-renderer/build.gradle
ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/service/AEMDownloadManger.java

- make the download manager a singleton
- create wireframe methods for the various tasks

AEM download manager wireframe

---

library/xml-model/src/main/java/org/cru/godtools/xml/model/Image.java
library/xml-model/src/main/java/org/cru/godtools/xml/model/Tab.java
ui/tract-renderer/src/main/java/org/cru/godtools/tract/viewmodel/BaseViewHolder.java
ui/tract-renderer/src/main/java/org/cru/godtools/tract/viewmodel/CardViewHolder.java
ui/tract-renderer/src/main/java/org/cru/godtools/tract/viewmodel/FormViewHolder.java
ui/tract-renderer/src/main/java/org/cru/godtools/tract/viewmodel/ImageViewHolder.java
ui/tract-renderer/src/main/java/org/cru/godtools/tract/viewmodel/PageViewHolder.java
ui/tract-renderer/src/main/java/org/cru/godtools/tract/viewmodel/ParentViewHolder.java
ui/tract-renderer/src/main/java/org/cru/godtools/tract/viewmodel/TabsViewHolder.java

This is dependent on https://github.com/CruGlobal/mobile-content-api/pull/163
There is a test page that illustrates this use-case, it is the "Tabs Select Listener testing" page in the "Renderer Test" tract in the stage environment

[GT-509] Make it possible to toggle tabs by clicking images

---

ui/article-renderer/build.gradle
ui/article-renderer/src/main/AndroidManifest.xml
ui/article-renderer/src/main/java/org/cru/godtools/article/activity/ArticlesActivity.java
ui/article-renderer/src/main/java/org/cru/godtools/article/adapter/ArticleAdapter.java
ui/article-renderer/src/main/java/org/cru/godtools/article/fragment/ArticlesFragment.java
ui/article-renderer/src/main/res/drawable/divider.xml
ui/article-renderer/src/main/res/drawable/list_item_decorator_article_divider.xml
ui/article-renderer/src/main/res/layout/activity_article_articles.xml
ui/article-renderer/src/main/res/layout/fragment_articles.xml
ui/article-renderer/src/main/res/layout/list_item_article.xml
ui/article-renderer/src/main/res/values/styles_article.xml
ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/model/Article.java
ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/view_model/ArticleViewModel.java
ui/base/src/main/res/values/colors.xml

Create List View for Articles Section

Article list view

---

ui/articles-aem-renderer/src/androidTest/java/org/cru/godtools/articles/aem/db/AEMDownloadMangerTest.java
ui/articles-aem-renderer/src/androidTest/java/org/cru/godtools/articles/aem/db/TranslationRepositoryIT.java
ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/db/AemImportDao.java
ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/service/AEMDownloadManger.java

The PR is for attaching the logic for parsing an AEM api into the import Task.

Sync aem import task

---

ui/articles-aem-renderer/src/androidTest/java/org/cru/godtools/articles/aem/service/support/ArticleParserTest.java
ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/model/Article.java
ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/service/AEMDownloadManger.java
ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/service/support/ArticleParser.java

This is to convert from using the Uuid for the Article Key to the Article url.

Use url for article key

---

ui/tract-renderer/src/main/java/org/cru/godtools/tract/widget/PageContentLayout.java

I really need to work up some UI tests for this logic to verify how things work together

stop any PCL animation currently running if we are changing the active card without animating.

---

ui/article-renderer/src/main/java/org/cru/godtools/article/activity/ArticlesActivity.java
ui/article-renderer/src/main/res/layout/list_item_article.xml
ui/articles-aem-renderer/build.gradle
ui/articles-aem-renderer/room-schemas/org.cru.godtools.articles.aem.db.ArticleRoomDatabase/3.json
ui/articles-aem-renderer/src/androidTest/java/org/cru/godtools/articles/aem/db/ArticleRoomDatabaseTest.java
ui/articles-aem-renderer/src/androidTest/java/org/cru/godtools/articles/aem/db/DBBaseTest.java
ui/articles-aem-renderer/src/androidTest/java/org/cru/godtools/articles/aem/service/support/ArticleParserTest.java
ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/api/AemApi.java
ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/db/AemImportDao.java
ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/db/AemImportRepository.java
ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/db/ArticleDao.java
ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/db/ArticleRepository.java
ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/db/ArticleRoomDatabase.java
ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/model/Article.java
ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/service/AEMDownloadManger.java
ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/service/support/ArticleParser.java
ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/view_model/ArticleViewModel.java

- Add some synchronization around syncing an AemImport
- utilize Retrofit to fetch AEM json for articles
- create an AemImportRepository that encompasses all logic to store a processed AemImport in the database

Store articles in db

---

build.gradle
library/analytics/build.gradle
library/analytics/src/main/java/org/cru/godtools/analytics/SnowplowAnalyticsService.java

This will allow snowplow API calls to show up in Stetho

attach any global OkHttp3Client interceptors

---

ui/articles-aem-renderer/room-schemas/org.cru.godtools.articles.aem.db.ArticleRoomDatabase/6.json
ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/api/AemApi.java
ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/db/ArticleRoomDatabase.java
ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/db/ResourceDao.kt
ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/model/Resource.kt
ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/service/AEMDownloadManger.java
ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/util/ResourceUtils.kt

implements AEMDownloadManager task to download resources that haven't been downloaded yet

Download resources

---

analysis/checkstyle/checkstyle.xml
build.gradle
ui/articles-aem-renderer/build.gradle
ui/articles-aem-renderer/src/androidTest/java/org/cru/godtools/articles/aem/db/ArticleRoomDatabaseTest.java
ui/articles-aem-renderer/src/androidTest/java/org/cru/godtools/articles/aem/db/DBBaseTest.java
ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/db/ArticleDao.java

I found a way to actually test against `LiveData` room DAO methods

update ArticleRoomDatabaseTest to utilize actual LiveData method

---

app/build.gradle
app/src/debug/java/org/cru/godtools/DebugGodToolsApplication.java
app/src/debug/java/org/cru/godtools/util/BuildTypeUtils.java
app/src/main/java/org/keynote/godtools/android/activity/MainActivity.java
app/src/release/java/org/cru/godtools/util/BuildTypeUtils.java

This change will launch the new articles renderer on debug builds, but leave the legacy everystudent UI in place for release builds

Launch articles for debug builds

---

ui/articles-aem-renderer/src/androidTest/assets/tests/article-test.json

Updated the saved test json for to reflect the changes made in Aem json.

Update test json

---

library/xml-model/src/main/java/org/cru/godtools/xml/model/Manifest.java
ui/article-renderer/src/main/java/org/cru/godtools/article/fragment/ArticlesFragment.java
ui/article-renderer/src/main/res/layout/fragment_articles.xml
ui/article-renderer/src/main/res/layout/list_item_article.xml
ui/article-renderer/src/main/res/values/styles_article.xml

Adjust the UI for the articles list so that it pull colors from the Manifest

Articles list style updates

---

library/xml-model/src/main/java/org/cru/godtools/xml/model/Manifest.java
ui/article-renderer/src/main/java/org/cru/godtools/article/databinding/adapter/TextViewAdapters.java
ui/article-renderer/src/main/res/layout/list_item_category.xml

This will use the manifest `category-label-color` attribute as the default color for category labels

Category label color

---

.travis.yml
build.gradle

This breaks the travis build up into several stages to hopefully improve reliability and overall performance of travis
I have not tested the deploy stage yet, that will come once this PR is merged

Travis build stages

---

build.gradle
library/analytics/build.gradle
library/analytics/src/main/AndroidManifest.xml
library/analytics/src/main/java/org/cru/godtools/analytics/FirebaseAnalyticsService.java
library/analytics/src/main/java/org/cru/godtools/analytics/model/AnalyticsSystem.java
library/base/build.gradle
library/base/google-services.json
ui/base-app/src/main/java/org/cru/godtools/base/app/BaseGodToolsApplication.java

Add Firebase to GodTools. This will be the basis for experimenting with Firebase Dynamic Links

Firebase Analytics

---

library/analytics/build.gradle
library/analytics/src/main/java/org/cru/godtools/analytics/SnowplowAnalyticsService.java

This PR standardizes the data we're sending to snowplow to match the standard found [here](https://github.com/CruGlobal/user-data-platform/wiki/tracker-protocol#mobile-app-events).

GT-542 - standardize snowplow data

---

.idea/codeStyles/Project.xml

This should allow us to use a common style when using Android Studio's code reformatting

Add Android Studio code style configuration file

---

app/src/main/res/layout/fragment_tool_details.xml

https://jira.cru.org/browse/GT-553
This is what Ann requested about making links in the TextView Clickable.

GT-553 added Linkify to extract url from TextView

---

ui/base-tool/build.gradle
ui/base-tool/src/main/java/org/cru/godtools/base/tool/activity/BaseSingleToolActivity.java
ui/base-tool/src/main/java/org/cru/godtools/base/tool/activity/BaseToolActivity.java
ui/tract-renderer/src/main/java/org/cru/godtools/tract/activity/TractActivity.java
ui/tract-renderer/src/test/java/org/cru/godtools/tract/activity/TractActivityUpdateHiddenLanguagesTest.java

This will trigger a sync/download of articles on access.

GT-550 move sync/cache tools logic to BaseToolActivity

---

ui/article-aem-renderer/src/androidTest/java/org/cru/godtools/article/aem/util/UriUtilsIT.kt
ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/api/AemApi.java
ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/service/AemArticleManger.java
ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/util/UriUtils.kt

This adds extensions onto Uris in a more robust fashion

Handle query parameters on uris for AemArticleManager

---

build.gradle
ui/article-aem-renderer/build.gradle
ui/article-aem-renderer/room-schemas/org.cru.godtools.article.aem.db.ArticleRoomDatabase/10.json
ui/article-aem-renderer/src/androidTest/java/org/cru/godtools/article/aem/db/ArticleRoomDatabaseMigrationIT.kt
ui/article-aem-renderer/src/androidTest/java/org/cru/godtools/article/aem/util/UriUtilsIT.kt
ui/article-aem-renderer/src/main/AndroidManifest.xml
ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/Constants.kt
ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/activity/AemArticleActivity.kt
ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/db/AemImportDao.kt
ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/db/AemImportRepository.kt
ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/db/ArticleRoomDatabase.java
ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/fragment/AemArticleFragment.java
ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/model/AemImport.kt
ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/service/AemArticleManger.java
ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/util/UriUtils.kt
ui/article-renderer/src/main/java/org/cru/godtools/article/activity/ArticlesActivity.java
ui/article-renderer/src/main/java/org/cru/godtools/article/activity/CategoriesActivity.java
ui/base-tool/src/main/java/org/cru/godtools/base/tool/activity/BaseSingleToolActivity.java

Currently the deeplink should be in the form:
`https://godtoolsapp.com/article/aem?uri={experienceFragmentUri}`. This can be adjusted later if a more appropriate deeplink is determined.
The firebase dynamic links PR will be updated to utilize this deeplink format when generating dynamic short links for the share action.
Sample deep link: https://godtoolsapp.com/article/aem?uri=https%3A%2F%2Fwww.cru.org%2Fcontent%2Fexperience-fragments%2Fshared-library%2Flanguage-masters%2Fen%2Fhow-to-know-god%2Fchanged-life-stories%2Fa-voice-that-stopped-a-suicidal-teen%2Fa-voice-that-stopped-a-suicidal-teen

Support deep linking to AEM articles

---

ui/article-renderer/src/main/java/org/cru/godtools/article/activity/CategoriesActivity.java
ui/base-tool/src/main/java/org/cru/godtools/base/tool/activity/BaseSingleToolActivity.java
ui/base/src/main/java/org/cru/godtools/base/ui/activity/BaseActivity.java
ui/shortcuts/build.gradle
ui/shortcuts/src/main/java/org/cru/godtools/shortcuts/GodToolsShortcutManager.java

Currently the questions about God shortcut deep links to the legacy activity, it should deep link to the new Articles related activities.
https://jira.cru.org/browse/GT-546

GT-545 - add Article Renderer to Short Cut

---

app/src/main/AndroidManifest.xml
library/sync/src/main/AndroidManifest.xml

These crashes:
https://fabric.io/cru/android/apps/org.keynote.godtools.android/issues/5be6cd6cf8b88c296356b961?time=last-ninety-days
https://fabric.io/cru/android/apps/org.keynote.godtools.android/issues/5be69175f8b88c296350b8af?time=last-ninety-days

Permission adjustment

---

library/xml-model/src/main/java/org/cru/godtools/xml/model/Manifest.java
ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/activity/AemArticleActivity.kt
ui/article-renderer/src/main/java/org/cru/godtools/article/activity/ArticlesActivity.kt
ui/article-renderer/src/main/java/org/cru/godtools/article/activity/CategoriesActivity.kt
ui/base-tool/src/main/java/org/cru/godtools/base/tool/activity/ArticleBaseSingleToolActivity.java
ui/base-tool/src/main/java/org/cru/godtools/base/tool/activity/BaseArticleActivity.java
ui/base-tool/src/main/java/org/cru/godtools/base/tool/activity/BaseSingleToolActivity.java
ui/base-tool/src/main/java/org/cru/godtools/base/tool/activity/BaseToolActivity.java
ui/tract-renderer/src/main/java/org/cru/godtools/tract/activity/TractActivity.java

https://jira.cru.org/browse/GT-552

GT-552 Invalid Tool for Tools with no data

---

ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/activity/AemArticleActivity.kt
ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/analytics/model/ArticleAnalyticsScreenEvent.kt
ui/article-renderer/src/main/java/org/cru/godtools/article/activity/ArticlesActivity.kt
ui/article-renderer/src/main/java/org/cru/godtools/article/activity/CategoriesActivity.kt
ui/article-renderer/src/main/java/org/cru/godtools/article/analytics/model/ArticlesAnalyticsScreenEvent.kt
ui/base-tool/src/main/java/org/cru/godtools/base/tool/activity/BaseSingleToolActivity.java
ui/base-tool/src/main/java/org/cru/godtools/base/tool/analytics/model/ToolAnalyticsScreenEvent.java
ui/tract-renderer/src/main/java/org/cru/godtools/tract/analytics/model/TractPageAnalyticsScreenEvent.java

https://jira.cru.org/browse/GT-545

GT-545 add analytics to articles

---

library/download-manager/src/main/java/org/cru/godtools/download/manager/GodToolsDownloadManager.java
library/initial-content/download_initial_content.gradle
library/initial-content/src/main/java/org/cru/godtools/init/content/task/InitialContentTasks.java

This makes the initial bundled tools more dynamic and fixes a bundled content race condition that presents itself in airplane mode.

Initial content improvements

---

app/src/main/res/layout/fragment_about.xml
app/src/main/res/layout/fragment_language_settings.xml
app/src/main/res/layout/fragment_tool_details.xml
ui/tract-renderer/src/main/res/layout/activity_modal.xml
ui/tract-renderer/src/main/res/layout/page_manifest_page.xml
ui/tract-renderer/src/main/res/layout/tract_content_card.xml

Addresses: https://console.firebase.google.com/u/0/project/godtools-b2f82/crashlytics/app/android:org.keynote.godtools.android/issues/586a39530aeb16625bad620e?time=last-ninety-days&sessionId=5BE0A80802A6000111EAC482B91C4546_DNE_0_v2

use the HackyNestedScrollView to handle processing buggy touch events

---

ui/article-aem-renderer/room-schemas/org.cru.godtools.article.aem.db.ArticleRoomDatabase/11.json
ui/article-aem-renderer/src/androidTest/java/org/cru/godtools/article/aem/db/ArticleRoomDatabaseMigrationIT.kt
ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/activity/AemArticleActivity.kt
ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/db/ArticleDao.kt
ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/db/ArticleRoomDatabase.kt
ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/service/AemArticleManger.java
ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/service/support/AemJsonParser.kt

We now have canonicalUrls in the article json meta-data

GT-568 Articles share link

---

ui/tract-renderer/src/main/java/org/cru/godtools/tract/viewmodel/InputViewHolder.java

See: https://console.firebase.google.com/u/0/project/godtools-b2f82/crashlytics/app/android:org.keynote.godtools.android/issues/5be5d8a6f8b88c29633e6a7f?time=last-ninety-days&sessionId=5C51BA2903E50001204EA37B63C45580_DNE_2_v2

replace unsupported deprecated method call

---

build.gradle

https://jira.cru.org/browse/GT-596

GT-596  Update App See

---

build.gradle
library/analytics/build.gradle
library/analytics/src/main/AndroidManifest.xml
library/analytics/src/main/java/org/cru/godtools/analytics/facebook/FacebookAnalyticsService.kt
library/analytics/src/main/java/org/cru/godtools/analytics/model/AnalyticsSystem.java
multidex-keep.pro
ui/base-app/src/main/java/org/cru/godtools/base/app/BaseGodToolsApplication.java
ui/tract-renderer/src/main/java/org/cru/godtools/tract/analytics/model/ToggleLanguageAnalyticsActionEvent.java

This logs events to Facebook Analytics

GT-604 Facebook analytics

---

ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/fragment/AemArticleFragment.kt

https://jira.cru.org/browse/GT-638

GT-638 : AemArticleFragment Crash

---

library/base/src/main/java/org/cru/godtools/base/util/LocaleUtils.java
ui/tract-renderer/build.gradle
ui/tract-renderer/src/main/java/org/cru/godtools/tract/viewmodel/CardViewHolder.java
ui/tract-renderer/src/main/java/org/cru/godtools/tract/viewmodel/PageViewHolder.java
ui/tract-renderer/src/main/res/layout/tract_content_card.xml
ui/tract-renderer/src/main/res/values/strings.xml
ui/tract-renderer/src/main/res/values/strings_tract_renderer.xml

https://jira.cru.org/browse/GT-601

GT-601  : include footer at bottom of cards to indicate next card

---

.idea/codeStyles/Project.xml

The project file keeps automatically updating, so I placed that change in a separate PR.

Project File Update

---

app/src/main/java/org/cru/godtools/fragment/ToolDetailsFragment.java
app/src/main/res/layout/tool_detail_text_view.xml
build.gradle
library/model-loader/src/main/java/org/cru/godtools/model/loader/LatestTranslationLoader.java
ui/tract-renderer/src/main/java/org/cru/godtools/tract/activity/TractActivity.java

https://jira.cru.org/browse/GT-641

GT-641 : jira requested changes

---

ui/tract-renderer/src/main/res/layout/tract_content_card.xml

This cleans up the styles for the next/previous buttons on a card

rework the next/prev navigation for cards

---

library/base/src/main/java/org/cru/godtools/base/Settings.java

This will allow us to check if the user had used a previous version of GodTools and prevent showing the onboarding tutorial to them

start tracking the first launch version in the GodTools settings

---

app/src/main/res/layout/tool_detail_text_view.xml

https://jira.cru.org/browse/GT-631

GT-631 : Add more space between Tab and text

---

app/build.gradle
build.gradle

this is to allow Justin to test it out before we deploy it to production

enable in app messaging for debug builds

---

app/src/main/java/org/cru/godtools/activity/BasePlatformActivity.kt
app/src/main/java/org/cru/godtools/fragment/ToolsFragment.java
library/base/src/main/java/org/cru/godtools/base/Settings.java

https://jira.cru.org/browse/GT-664

GT-664   english only tutorials 

---

app/src/main/java/org/cru/godtools/ui/tooldetails/ToolDetailsFragment.java
app/src/main/res/layout/fragment_tool_details.xml

https://jira.cru.org/browse/GT-631

GT-631 : Text being cut off

---

ui/article-renderer/build.gradle
ui/article-renderer/src/main/java/org/cru/godtools/article/adapter/ArticlesAdapter.kt
ui/article-renderer/src/main/java/org/cru/godtools/article/fragment/ArticlesFragment.kt

we've learned a lot about how to better leverage Kotlin, LiveData, RecylcerViews, and ViewModels since when we originally wrote this

Rework ArticlesFragment

---

ui/tutorial-renderer/src/main/java/org/cru/godtools/tutorial/PageSet.kt
ui/tutorial-renderer/src/main/java/org/cru/godtools/tutorial/analytics/model/Constants.kt
ui/tutorial-renderer/src/main/java/org/cru/godtools/tutorial/analytics/model/TutorialAnalyticsScreenEvent.kt

https://jira.cru.org/browse/GT-634

GT-661   fix site sub section

---

ui/tutorial-renderer/src/main/res/layout/tutorial_training_watch.xml

https://jira.cru.org/browse/GT-674

GT-674 : Add New Training Video

---

build.gradle

https://developer.android.com/jetpack/androidx/versions

GT-676  : resolve web player crash

---

app/src/main/java/org/cru/godtools/analytics/model/ToolDetailsScreenEvent.kt
app/src/main/java/org/cru/godtools/ui/tooldetails/ToolDetailsActivity.kt
library/analytics/src/main/java/org/cru/godtools/analytics/model/AnalyticsScreenEvent.kt

https://jira.cru.org/browse/GT-682

GT-682 : Tool info analytic screen name

---

app/src/main/java/org/cru/godtools/fragment/ToolsFragment.java
ui/tutorial-renderer/src/main/java/org/cru/godtools/tutorial/analytics/model/TutorialAnalyticsActionEvent.kt

https://jira.cru.org/browse/GT-682

Gt 682   analytics exit links

---

app/build.gradle
app/src/main/java/org/cru/godtools/ui/tooldetails/ToolDetailsFragment.kt
app/src/main/java/org/cru/godtools/ui/tooldetails/ToolDetailsPagerAdapter.kt
app/src/main/res/layout/tool_details_fragment.xml
build.gradle

- Switch to ViewPager2
- Utilize `ConstraintLayout` instead of `PercentRelativeLayout`

update Tool Details UI

---

app/src/main/res/values/strings_profile.xml

https://jira.cru.org/browse/GT-718

GT-718 : Changing My Activity to Global Activity

---

app/build.gradle
app/src/main/java/org/cru/godtools/ui/languages/LanguagesFragmentViewModel.kt
app/src/main/java/org/cru/godtools/ui/tooldetails/ToolDetailsFragmentDataModel.kt
build.gradle
library/base/build.gradle
library/base/src/main/java/org/cru/godtools/base/Settings.kt
library/db/build.gradle
library/db/src/main/java/org/keynote/godtools/android/db/GodToolsDao.kt
library/db/src/main/java/org/keynote/godtools/android/db/LanguageMapper.kt
ui/article-renderer/build.gradle
ui/article-renderer/src/main/java/org/cru/godtools/article/fragment/ArticlesFragment.kt
ui/base-tool/build.gradle
ui/base-tool/src/main/java/org/cru/godtools/base/tool/service/ManifestManager.kt
ui/base-tool/src/main/java/org/cru/godtools/base/tool/viewmodel/LatestPublishedManifestDataModel.kt

this fixes a LiveDataRegistry threading issue

GT-745 use release version of GTO Support

---

app/build.gradle
app/src/main/java/org/cru/godtools/GodToolsApplication.kt
app/src/main/java/org/cru/godtools/dagger/ApplicationComponent.kt
app/src/main/java/org/cru/godtools/dagger/ApplicationModule.kt
app/src/main/java/org/cru/godtools/dagger/EventBusModule.kt
app/src/main/java/org/cru/godtools/dagger/ServicesModule.kt
app/src/main/java/org/cru/godtools/ui/UiModule.kt
app/src/main/java/org/cru/godtools/ui/languages/LanguagesFragment.kt
app/src/main/java/org/cru/godtools/ui/languages/LanguagesFragmentViewModel.kt
app/src/main/java/org/cru/godtools/ui/languages/LanguagesModule.kt
app/src/main/java/org/cru/godtools/ui/profile/GlobalActivityFragment.kt
app/src/main/java/org/cru/godtools/ui/profile/ProfileModule.kt
build.gradle
library/analytics/build.gradle
library/analytics/src/main/java/org/cru/godtools/analytics/adobe/AdobeAnalyticsService.kt
library/analytics/src/main/java/org/cru/godtools/analytics/dagger/AnalyticsModule.kt
library/db/build.gradle
library/db/src/main/java/org/keynote/godtools/android/db/dagger/DatabaseModule.kt

GT-735 Configure Dagger

---

app/build.gradle
app/src/debug/java/org/cru/godtools/DebugGodToolsApplication.kt
app/src/debug/java/org/cru/godtools/dagger/DebugApplicationComponent.kt
app/src/debug/java/org/cru/godtools/dagger/DebugApplicationModule.kt
app/src/debug/java/org/cru/godtools/dagger/DebugServicesModule.kt
app/src/debug/java/org/cru/godtools/dagger/FlipperModule.kt
app/src/main/java/org/cru/godtools/dagger/ServicesModule.kt
library/analytics/src/debug/java/org/cru/godtools/analytics/DebugAnalyticsModule.kt
library/analytics/src/debug/java/org/cru/godtools/analytics/TimberAnalyticsService.kt
library/analytics/src/main/java/org/cru/godtools/analytics/AnalyticsModule.kt
library/analytics/src/main/java/org/cru/godtools/analytics/adobe/AdobeAnalyticsService.kt

GT-735 Dagger debug dependencies

---

app/src/main/java/org/cru/godtools/fragment/BasePlatformFragment.kt
app/src/main/java/org/cru/godtools/fragment/ToolsFragment.java
app/src/main/java/org/cru/godtools/ui/UiModule.kt
app/src/main/java/org/cru/godtools/ui/languages/LanguagesFragment.kt
app/src/main/java/org/cru/godtools/ui/languages/LanguagesModule.kt
app/src/main/java/org/cru/godtools/ui/profile/GlobalActivityFragment.kt
app/src/main/java/org/cru/godtools/ui/tooldetails/ToolDetailsFragment.kt
app/src/main/java/org/cru/godtools/ui/tooldetails/ToolDetailsModule.kt
app/src/main/java/org/cru/godtools/ui/tools/ToolsModule.kt
build.gradle
ui/article-aem-renderer/build.gradle
ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/AemArticleRendererModule.kt
ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/fragment/AemArticleFragment.kt
ui/article-renderer/build.gradle
ui/article-renderer/src/main/java/org/cru/godtools/article/ArticleRendererModule.kt
ui/base/build.gradle
ui/base/src/main/java/org/cru/godtools/base/ui/fragment/BaseFragment.kt

GT-735 Dagger fragment injection

---

app/src/main/java/org/cru/godtools/activity/BasePlatformActivity.kt
app/src/main/java/org/cru/godtools/ui/UiModule.kt
app/src/main/java/org/cru/godtools/ui/about/AboutModule.kt
app/src/main/java/org/cru/godtools/ui/languages/LanguagesModule.kt
app/src/main/java/org/cru/godtools/ui/profile/ProfileActivity.kt
app/src/main/java/org/cru/godtools/ui/profile/ProfileModule.kt
app/src/main/java/org/cru/godtools/ui/tooldetails/ToolDetailsModule.kt
ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/AemArticleRendererModule.kt
ui/article-renderer/src/main/java/org/cru/godtools/article/ArticleRendererModule.kt
ui/base/src/main/java/org/cru/godtools/base/ui/activity/BaseActivity.kt
ui/base/src/main/java/org/cru/godtools/base/ui/activity/BaseDesignActivity.kt
ui/tract-renderer/build.gradle
ui/tract-renderer/src/main/java/org/cru/godtools/tract/TractRendererModule.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/activity/ModalActivity.java
ui/tract-renderer/src/main/java/org/cru/godtools/tract/activity/TractActivity.java
ui/tutorial-renderer/build.gradle
ui/tutorial-renderer/src/main/java/org/cru/godtools/tutorial/TutorialRendererModule.kt

GT-735 Dagger activity injection

---

app/build.gradle
app/src/main/java/org/cru/godtools/ui/UiModule.kt
app/src/main/java/org/cru/godtools/ui/tooldetails/ToolDetailsFragmentDataModel.kt
app/src/main/java/org/cru/godtools/ui/tooldetails/ToolDetailsModule.kt
build.gradle
library/analytics/build.gradle
library/analytics/src/main/java/org/cru/godtools/analytics/AnalyticsModule.kt
library/analytics/src/main/java/org/cru/godtools/analytics/LaunchTrackingViewModel.kt
ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/AemArticleRendererModule.kt
ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/activity/AemArticleActivity.kt
ui/article-renderer/build.gradle
ui/article-renderer/src/main/java/org/cru/godtools/article/ArticleRendererModule.kt
ui/article-renderer/src/main/java/org/cru/godtools/article/fragment/ArticlesFragment.kt
ui/base-tool/build.gradle
ui/base-tool/src/main/java/org/cru/godtools/base/tool/BaseToolRendererModule.kt
ui/base-tool/src/main/java/org/cru/godtools/base/tool/activity/BaseSingleToolActivityDataModel.kt
ui/base-tool/src/main/java/org/cru/godtools/base/tool/viewmodel/LatestPublishedManifestDataModel.kt

GT-735 Dagger ViewModel injection

---

.travis.yml
app/build.gradle
ui/account/build.gradle

This is a cleaner way of implementing the QA build type

GT-760 rework the QA build to be it's own buildType

---

ui/tract-renderer/src/main/java/org/cru/godtools/tract/analytics/model/TractPageAnalyticsScreenEvent.kt

the couple pages that Ann cares about in AppsFlyer will be triggered via content xml analytics events

GT-743 don't send tract page events to AppsFlyer

---

app/src/main/java/org/cru/godtools/fragment/ToolsFragment.kt
build.gradle

GT-795 Fix broken interactions between SwipRefreshLayout and reorderable tools

---

.travis.yml

for some reason the API 24 emulator quit working in travis

switch android test API to 23 from 24

---

app/src/main/java/org/cru/godtools/ui/tools/ToolsFragment.kt

GT-803 detach the ToolsFragment from the ToolsAdapter when the fragment is being destroyed

---

ui/tract-renderer/src/main/java/org/cru/godtools/tract/activity/TractActivity.kt

We aren't ready to have this visible on production yet

only show live share functionality for debug builds

---

library/xml-model/src/main/java/org/cru/godtools/xml/model/Card.kt
library/xml-model/src/main/java/org/cru/godtools/xml/model/Content.kt
library/xml-model/src/main/java/org/cru/godtools/xml/model/Form.kt
library/xml-model/src/main/java/org/cru/godtools/xml/model/Hero.kt
library/xml-model/src/main/java/org/cru/godtools/xml/model/Image.kt
library/xml-model/src/main/java/org/cru/godtools/xml/model/Input.kt
library/xml-model/src/main/java/org/cru/godtools/xml/model/Link.kt
library/xml-model/src/main/java/org/cru/godtools/xml/model/Modal.kt
library/xml-model/src/main/java/org/cru/godtools/xml/model/Paragraph.kt
library/xml-model/src/main/java/org/cru/godtools/xml/model/Parent.kt
library/xml-model/src/main/java/org/cru/godtools/xml/model/Tab.kt
library/xml-model/src/main/java/org/cru/godtools/xml/model/Tabs.kt
library/xml-model/src/main/java/org/cru/godtools/xml/model/Text.kt

Reduce code duplication by creating a centralized content parsing extension function

Simplify nested content parsing

---

ui/tract-renderer/src/main/java/org/cru/godtools/tract/activity/ModalActivity.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/activity/TractActivity.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/adapter/ManifestPagerAdapter.java
ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/BaseController.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/ButtonController.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/CardController.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/HeroController.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/ModalController.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/PageController.kt

- Utilize Coroutines to delay execution of analytics events when requested
- Use Dagger to inject appropriate dependencies from the Dagger object graph

GT-860 Dagger & Coroutines

---

ui/tract-renderer/src/main/java/org/cru/godtools/tract/activity/TractActivity.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/liveshare/TractSubscriberController.kt
ui/tract-renderer/src/main/res/drawable/ic_tract_live_share.xml
ui/tract-renderer/src/main/res/menu/activity_tract_live_share.xml
ui/tract-renderer/src/main/res/values/strings_tract_renderer.xml

GT-857 Add an indicator to the toolbar when a live share session is running

---

ui/base-tool/src/main/java/org/cru/godtools/base/tool/activity/BaseArticleActivity.kt
ui/base-tool/src/main/java/org/cru/godtools/base/tool/activity/BaseSingleToolActivity.kt
ui/base-tool/src/main/java/org/cru/godtools/base/tool/activity/BaseToolActivity.kt
ui/base-tool/src/main/java/org/cru/godtools/base/tool/activity/ImmersiveActivity.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/activity/ModalActivity.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/activity/TractActivity.kt

Disable immersive mode and color the status bar when viewing a tool.
Dependent on:

GT-904 Disable immersive mode

---

library/xml-model/src/main/java/org/cru/godtools/xml/model/tips/Tip.kt
library/xml-model/src/main/java/org/cru/godtools/xml/model/tips/TipPage.kt
library/xml-model/src/main/res/values/styles_base_text_sizes.xml
library/xml-model/src/test/java/org/cru/godtools/xml/model/tips/TipTest.kt
ui/base/src/main/java/org/cru/godtools/base/ui/fragment/BaseBottomSheetDialogFragment.kt
ui/tract-renderer/build.gradle
ui/tract-renderer/src/main/java/org/cru/godtools/tract/TractRendererModule.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/activity/TractActivity.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/adapter/ManifestPagerAdapter.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/BaseController.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/PageController.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/tips/TipPageController.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/tips/TipBottomSheetDialogFragment.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/tips/TipCallbacks.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/tips/TipPageAdapter.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/util/TipType.kt
ui/tract-renderer/src/main/res/drawable-v21/bkg_tips_tip.xml
ui/tract-renderer/src/main/res/drawable/bkg_tips_tip.xml
ui/tract-renderer/src/main/res/drawable/bkg_tips_tip_done.xml
ui/tract-renderer/src/main/res/drawable/tips_progress_bar.xml
ui/tract-renderer/src/main/res/layout/tract_content_inline_tip.xml
ui/tract-renderer/src/main/res/layout/tract_tip.xml
ui/tract-renderer/src/main/res/layout/tract_tip_page.xml
ui/tract-renderer/src/main/res/values-h500dp/styles_tips.xml
ui/tract-renderer/src/main/res/values/strings_tract_renderer.xml
ui/tract-renderer/src/main/res/values/styles_tips.xml

This adds the UI to view tip content.
Dependent on:

GT-866 Add Tips UI

---

app/src/main/java/org/cru/godtools/ui/tooldetails/ToolDetailsFragment.kt
app/src/main/java/org/cru/godtools/ui/tools/ToolsAdapterCallbacks.kt
app/src/main/java/org/cru/godtools/ui/tools/ToolsFragment.kt
app/src/main/java/org/cru/godtools/ui/tools/analytics/model/ToolsAnalyticsActionEvent.kt
app/src/main/java/org/keynote/godtools/android/activity/MainActivity.java
library/analytics/src/main/java/org/cru/godtools/analytics/model/AnalyticsActionEvent.kt
library/analytics/src/main/java/org/cru/godtools/analytics/model/AnalyticsBaseEvent.kt
library/analytics/src/main/java/org/cru/godtools/analytics/model/AnalyticsScreenEvent.kt

https://docs.google.com/spreadsheets/d/1YLkGQ8ptXWn6xmB82kzUYIkXHsI-BsnA2iQanQdPcnw/edit?usp=sharing

GT-877 : Add missing Analytics

---

ui/tract-renderer/src/main/res/layout/tract_content_inline_tip.xml

GT-865 support compat shadow for inline tips on older android SDKs

---

library/xml-model/src/main/java/org/cru/godtools/xml/model/Header.kt
library/xml-model/src/test/java/org/cru/godtools/xml/model/HeaderTest.kt
library/xml-model/src/test/resources/org/cru/godtools/xml/model/header.xml
ui/tract-renderer/src/main/java/org/cru/godtools/tract/databinding/MaterialShapeBackgroundImageViewBindingAdapter.kt
ui/tract-renderer/src/main/res/layout/tract_page.xml
ui/tract-renderer/src/main/res/values/styles_tips.xml

GT-906 Header tips

---

build.gradle
library/initial-content/download_initial_content.gradle

Remove the bundled translations when GodTools is installed, this will decrease the APK size and let the tools be downloaded when actually needed

GT-938 don't bundle translations

---

app/build.gradle
app/src/main/java/org/cru/godtools/GodToolsApplication.kt
app/src/main/java/org/cru/godtools/dagger/ServicesModule.kt
app/src/main/java/org/cru/godtools/dagger/features/BundledContentFeatureDependencies.kt
app/src/main/java/org/cru/godtools/dagger/features/FeaturesModule.kt
app/src/main/res/values/strings_features.xml
build.gradle
feature/bundledcontent/build.gradle
feature/bundledcontent/src/main/AndroidManifest.xml
feature/bundledcontent/src/main/java/org/cru/godtools/feature/bundledcontent/dagger/BundledContentFeatureComponent.kt
library/initial-content/build.gradle
settings.gradle

Include the initial content via a `bundledcontent` dynamic feature. this will allow it to be excluded from the download when GodTools as an instant app.
Unfortunately in order to make this work I needed to create a new Dagger Component for the dynamic feature because the code in the feature is not visible from the app itself

GT-908 Bundled content dynamic feature

---

library/xml-model/src/main/java/org/cru/godtools/xml/model/Card.kt
library/xml-model/src/main/java/org/cru/godtools/xml/model/Page.kt
library/xml-model/src/test/java/org/cru/godtools/xml/model/CardTest.kt
ui/tract-renderer/src/main/res/layout/tract_content_card.xml
ui/tract-renderer/src/test/java/org/cru/godtools/tract/databinding/TractContentCardBindingTest.kt

Display presence of call-to-action tip in the last visible card header

GT-898 Indicate call-to-action tips in last visible card header

---

.travis.yml
app/build.gradle

Now that we are using dynamic features, we need to upload the universal APK to Firebase App Distribution.

GT-908 Firebase app distribution fix

---

app/src/main/java/org/cru/godtools/ui/tooldetails/ToolDetailsFragment.kt
library/base/src/main/java/org/cru/godtools/base/Settings.kt
ui/tutorial-renderer/src/main/java/org/cru/godtools/tutorial/PageSet.kt
ui/tutorial-renderer/src/main/java/org/cru/godtools/tutorial/activity/TutorialActivity.kt
ui/tutorial-renderer/src/main/res/menu/tutorial_tips_menu.xml
ui/tutorial-renderer/src/main/res/values/strings_tutorial_tips.xml

Show the tips tutorial 3 times per tool

GT-960 Tips tutorial frequency

---

build.gradle

the previous plugin was no longer maintained and didn't work with the latest version of Gradle

switch to a different jacoco gradle plugin

---

library/xml-model/src/main/java/org/cru/godtools/xml/model/Content.kt
library/xml-model/src/main/java/org/cru/godtools/xml/model/DeviceType.kt
library/xml-model/src/test/java/org/cru/godtools/xml/model/DeviceTypeTest.kt
library/xml-model/src/test/java/org/cru/godtools/xml/model/ParagraphTest.kt
library/xml-model/src/test/resources/org/cru/godtools/xml/model/paragraph_ignored_content.xml

This allows content elements to target android specifically and not be rendered on iOS

GT-973 Android restrict to

---

library/analytics/build.gradle
library/analytics/src/main/java/org/cru/godtools/analytics/snowplow/SnowplowAnalyticsService.kt

GT-971 Snowplow custom attributes fix

---

ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/BaseController.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/PageController.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/tips/InlineTipController.kt
ui/tract-renderer/src/main/res/layout/tract_content_inline_tip.xml
ui/tract-renderer/src/main/res/layout/tract_page.xml
ui/tract-renderer/src/test/java/org/cru/godtools/tract/ui/controller/PageControllerTest.kt

update tip indicators to display if the tip has been completed or not

GT-964 Completed tip icons

---

library/xml-model/src/main/java/org/cru/godtools/xml/model/Animation.kt
library/xml-model/src/main/java/org/cru/godtools/xml/model/Content.kt
library/xml-model/src/test/java/org/cru/godtools/xml/model/AnimationTest.kt
library/xml-model/src/test/resources/org/cru/godtools/xml/model/animation.xml
ui/tract-renderer/build.gradle
ui/tract-renderer/src/main/java/org/cru/godtools/tract/databinding/LottieAnimationViewBindingAdapter.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/AnimationController.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/UiControllerCache.kt
ui/tract-renderer/src/main/res/layout/tract_content_animation.xml

Dependent on:
Adds support for animations in tools, there is an animations page in the renderer test tool that has several examples using various attribute configurations

GT-996 Tool animations

---

.travis.yml

With Travis changing their billing model we should consolidate some tasks to reduce overall build time

Travis task consolidation

---

build.gradle
library/sync/build.gradle
library/sync/src/main/java/org/cru/godtools/sync/SyncModule.kt
library/sync/src/main/java/org/cru/godtools/sync/work/SyncFollowupWorker.kt
library/sync/src/main/java/org/cru/godtools/sync/work/SyncToolSharesWorker.kt
ui/tract-renderer/build.gradle
ui/tract-renderer/src/main/java/org/cru/godtools/tract/TractRendererModule.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/adapter/ManifestPagerAdapter.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/ModalController.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/PageController.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/tips/TipPageController.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/tips/TipPageAdapter.kt

Dagger 2.31 introduces its own assisted injection. We are transitioning away from squares assisted injection to the dagger assisted injection to simplify our dependencies

Upgrade to Dagger 2.31

---

library/xml-model/src/main/java/org/cru/godtools/xml/model/Manifest.kt
library/xml-model/src/test/java/org/cru/godtools/xml/model/ManifestTest.kt

This reworks part of the manifest parsing logic to make it more parallel and set it up to support parsing lesson pages soon

GT-1043 Manifest parsing adjustments

---

build.gradle

Reverts CruGlobal/godtools-android#1509

Revert "Bump deps.androidX.hilt from 1.0.0-alpha02 to 1.0.0-alpha03"

---

app/src/main/java/org/cru/godtools/GodToolsApplication.kt

see: https://stackoverflow.com/questions/50471888/android-app-bundle-introduces-resource-not-found-crash-in-android-app/56595941#56595941

GT-1068 add MissingSplits detection logic for Android 9 and earlier

---

library/xml-model/src/main/java/org/cru/godtools/xml/model/Manifest.kt
library/xml-model/src/test/java/org/cru/godtools/xml/model/ManifestTest.kt

Lesson nav bar colors should have different default colors, I already updated the spec to reflect this.

GT-1036 Lesson nav bar colors

---

app/src/main/java/org/cru/godtools/ui/dashboard/DashboardDataModel.kt
app/src/main/java/org/cru/godtools/ui/dashboard/Page.kt
app/src/main/java/org/cru/godtools/ui/tools/ToolsAdapter.kt
app/src/main/java/org/cru/godtools/ui/tools/ToolsAdapterViewModel.kt
app/src/main/java/org/cru/godtools/ui/tools/ToolsFragment.kt
app/src/main/java/org/cru/godtools/ui/tools/ToolsFragmentDataModel.kt
app/src/main/java/org/cru/godtools/util/ActivityUtils.kt
app/src/main/java/org/keynote/godtools/android/activity/MainActivity.kt
app/src/main/res/drawable/ic_bullet.xml
app/src/main/res/drawable/ic_lessons.xml
app/src/main/res/layout/tools_list_item_lesson.xml
app/src/main/res/menu/dashboard_bottom_nav.xml
app/src/main/res/values/strings_tools.xml
app/src/main/res/values/styles_tools.xml
library/model/src/main/java/org/cru/godtools/model/Tool.kt
ui/base/src/main/res/values/colors.xml

This is only visible for the stage environment currently because we have no published lessons in production.

GT-1050 First pass at the lesson list UI

---

.github/workflows/build.yml

this will allow caches to evolve over time

update github action cache names to leverage the branch and commit id

---

library/xml-model/src/main/java/org/cru/godtools/xml/model/Content.kt
library/xml-model/src/main/java/org/cru/godtools/xml/model/Spacer.kt
library/xml-model/src/test/java/org/cru/godtools/xml/model/ContentTest.kt
library/xml-model/src/test/java/org/cru/godtools/xml/model/SpacerTest.kt
library/xml-model/src/test/resources/org/cru/godtools/xml/model/spacer.xml
ui/base-tool/src/main/java/org/cru/godtools/base/tool/ui/controller/SpacerController.kt
ui/base-tool/src/main/java/org/cru/godtools/base/tool/ui/controller/cache/UiControllerModule.kt
ui/base-tool/src/main/res/layout/tool_content_spacer.xml
ui/tract-renderer/src/main/res/layout/tract_content_card.xml

This is still a draft until we know if iOS can support the spacer concept

Support a spacer content element in cards to space out content vertically

---

library/xml-model/src/main/java/org/cru/godtools/xml/model/Accordion.kt
library/xml-model/src/main/java/org/cru/godtools/xml/model/Content.kt
library/xml-model/src/test/java/org/cru/godtools/xml/model/AccordionTest.kt
library/xml-model/src/test/resources/org/cru/godtools/xml/model/accordion.xml
ui/base-tool/build.gradle
ui/base-tool/src/main/java/org/cru/godtools/base/tool/databinding/AccordionSectionVisibilityAdapters.kt
ui/base-tool/src/main/java/org/cru/godtools/base/tool/ui/controller/AccordionController.kt
ui/base-tool/src/main/java/org/cru/godtools/base/tool/ui/controller/BaseController.kt
ui/base-tool/src/main/java/org/cru/godtools/base/tool/ui/controller/ParentController.kt
ui/base-tool/src/main/java/org/cru/godtools/base/tool/ui/controller/cache/UiControllerModule.kt
ui/base-tool/src/main/res/drawable/ic_collapse_24dp.xml
ui/base-tool/src/main/res/drawable/ic_expand_24dp.xml
ui/base-tool/src/main/res/layout/tool_content_accordion.xml
ui/base-tool/src/main/res/layout/tool_content_accordion_section.xml
ui/base-tool/src/main/res/values/styles_content_accordion.xml
ui/base-tool/src/test/java/org/cru/godtools/base/tool/ui/controller/ParentControllerTest.kt
ui/lesson-renderer/src/main/java/org/cru/godtools/tool/lesson/ui/controller/LessonPageController.kt
ui/tract-renderer/src/test/java/org/cru/godtools/tract/ui/controller/HeroControllerTest.kt

You can find an accordion element in the lesson in the staging environment

GT-1028 Accordion Content Element

---

library/xml-model/src/main/java/org/cru/godtools/xml/model/Manifest.kt
library/xml-model/src/test/java/org/cru/godtools/xml/model/ManifestTest.kt
library/xml-model/src/test/resources/org/cru/godtools/xml/model/manifest_lesson.xml
ui/base-tool/src/main/java/org/cru/godtools/base/tool/activity/BaseToolActivity.kt
ui/lesson-renderer/src/main/java/org/cru/godtools/tool/lesson/ui/LessonActivity.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/activity/TractActivity.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/adapter/ManifestPagerAdapter.kt

This allows content events to trigger closure of a tool

GT-1117 Manifest Dismiss Listener

---

ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/db/AemImportDao.kt
ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/db/AemImportRepository.kt
ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/service/AemArticleManager.kt
ui/article-aem-renderer/src/test/java/org/cru/godtools/article/aem/db/TranslationRepositoryIT.kt

easy way to trigger the bug is swipe to refresh on the articles list UI before and after this PR

GT-1132 Allow syncAemImportsFromManifest to be called from the MainThread

---

library/analytics/src/main/java/org/cru/godtools/analytics/model/AnalyticsActionEvent.kt
library/analytics/src/main/java/org/cru/godtools/analytics/model/LaunchAnalyticsActionEvent.kt
library/analytics/src/test/java/org/cru/godtools/analytics/model/LaunchAnalyticsActionEventTest.kt

https://jira.cru.org/browse/GT-1140

GT-1140 Update Firebase launch event

---

build.gradle
gradle.properties

GT-1139 Remove Jetifier

---

build.gradle
ui/base-tool/src/main/java/org/cru/godtools/base/tool/BaseToolRendererModule.kt
ui/base-tool/src/main/java/org/cru/godtools/base/tool/service/ManifestManager.kt
ui/base-tool/src/test/java/org/cru/godtools/base/tool/service/ManifestManagerTest.kt

- use release build of shared library
- update logic to use coroutines with the shared library as appropriate

GT-1217 Switch to first release build of shared library

---

ui/base-tool/src/main/java/org/cru/godtools/base/tool/service/ManifestManager.kt
ui/base-tool/src/main/java/org/cru/godtools/base/tool/ui/controller/BaseController.kt
ui/base-tool/src/main/java/org/cru/godtools/base/tool/ui/controller/MultiselectController.kt
ui/base-tool/src/main/java/org/cru/godtools/base/tool/ui/controller/TextController.kt
ui/base-tool/src/main/java/org/cru/godtools/base/tool/ui/controller/cache/UiControllerModule.kt
ui/base-tool/src/main/java/org/cru/godtools/base/tool/viewmodel/ToolStateHolder.kt
ui/base-tool/src/main/res/layout/tool_content_multiselect.xml
ui/base-tool/src/main/res/layout/tool_content_multiselect_option.xml
ui/base-tool/src/main/res/layout/tool_content_text.xml
ui/lesson-renderer/src/main/java/org/cru/godtools/tool/lesson/ui/LessonActivity.kt
ui/lesson-renderer/src/main/java/org/cru/godtools/tool/lesson/ui/LessonPageAdapter.kt
ui/lesson-renderer/src/main/java/org/cru/godtools/tool/lesson/ui/controller/LessonPageController.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/activity/ModalActivity.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/activity/TractActivity.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/adapter/ManifestPagerAdapter.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/ModalController.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/PageController.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/tips/TipPageController.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/tips/TipBottomSheetDialogFragment.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/tips/TipPageAdapter.kt
ui/tract-renderer/src/test/java/org/cru/godtools/tract/ui/controller/PageControllerTest.kt

This PR adds renderer support for the Multiselect element.
You can test out this element in the lesson on the stage environment

GT-1164 GT-1165 Implement the Multiselect element for tools

---

build.gradle
ui/base-tool/src/main/java/org/cru/godtools/base/tool/databinding/MaterialButtonAdapters.kt
ui/base-tool/src/main/res/layout/tool_content_button.xml
ui/base-tool/src/main/res/layout/tool_content_button_outlined.xml

GT-1136 support rendering button icons

---

build.gradle
ui/base-tool/src/main/java/org/cru/godtools/base/tool/ui/controller/ButtonController.kt
ui/base-tool/src/main/java/org/cru/godtools/base/tool/ui/controller/ImageController.kt
ui/base-tool/src/main/java/org/cru/godtools/base/tool/ui/controller/ParagraphController.kt
ui/base-tool/src/main/java/org/cru/godtools/base/tool/ui/controller/TextController.kt
ui/base-tool/src/main/res/layout/tool_content_button.xml
ui/base-tool/src/main/res/layout/tool_content_button_outlined.xml
ui/base-tool/src/main/res/layout/tool_content_image.xml
ui/base-tool/src/main/res/layout/tool_content_paragraph.xml
ui/base-tool/src/main/res/layout/tool_content_text.xml

This PR will allow various content elements to have their visibility determined by state expressions in the tool model
Dependent on:

GT-1241 Support hiding content elements based upon tool state

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/cru/godtools/ui/dashboard/DashboardAppsFlyerDeepLinkResolver.kt
app/src/main/java/org/cru/godtools/ui/dashboard/DashboardDeepLinks.kt
app/src/main/java/org/cru/godtools/ui/dashboard/DashboardModule.kt
app/src/main/java/org/keynote/godtools/android/activity/MainActivity.kt
app/src/test/java/org/cru/godtools/ui/dashboard/DashboardDeepLinksTest.kt
ui/base-tool/src/main/java/org/cru/godtools/base/tool/activity/BaseSingleToolActivity.kt
ui/lesson-renderer/src/main/AndroidManifest.xml
ui/lesson-renderer/src/main/java/org/cru/godtools/tool/lesson/LessonModule.kt
ui/lesson-renderer/src/main/java/org/cru/godtools/tool/lesson/analytics/appsflyer/LessonAppsFlyerDeepLinkResolver.kt
ui/lesson-renderer/src/main/java/org/cru/godtools/tool/lesson/ui/LessonActivity.kt
ui/lesson-renderer/src/main/java/org/cru/godtools/tool/lesson/util/LessonDeepLinkUtils.kt

- add support for deeplinking to a specific lesson
- add AppsFlyer support for deep linking to a specific lesson
- support deep linking to the lessons list in the MainActivity
- support deeplinking to the dashboard from appsflyer

GT-1203 Support deep links to the list of lessons and a specific lesson

---

ui/base-tool/src/main/res/values/styles.xml
ui/base/src/main/java/org/cru/godtools/base/ui/databinding/YouTubePlayerViewBindingAdapter.kt
ui/base/src/main/res/values/ids.xml
ui/base/src/main/res/values/styles.xml
ui/tract-renderer/src/main/res/values/styles_modal.xml
ui/tutorial-renderer/build.gradle
ui/tutorial-renderer/src/main/AndroidManifest.xml
ui/tutorial-renderer/src/main/java/org/cru/godtools/tutorial/activity/TutorialActivity.kt
ui/tutorial-renderer/src/main/java/org/cru/godtools/tutorial/activity/YoutubePlayerActivity.kt
ui/tutorial-renderer/src/main/res/layout/tutorial_youtube_activity.xml

- make the modal UI styles reusable
- make it possible to add some youtube playback listeners in databinding
- make the status bar transparent for modal activities
- create a Youtube video playback activity
- launch the inapp youtube player

GT-1162 Support launching an in app youtube player for onboarding video

---

ui/base-tool/src/main/java/org/cru/godtools/base/tool/databinding/ConstraintLayoutAdapters.kt
ui/base-tool/src/main/java/org/cru/godtools/base/tool/ui/controller/MultiselectController.kt
ui/base-tool/src/main/res/layout/tool_content_image.xml
ui/base-tool/src/main/res/layout/tool_content_multiselect.xml
ui/base-tool/src/main/res/layout/tool_content_multiselect_option.xml

- add a binding adapter for dynamically setting the width percentage for a ConstraintLayout child
- update the multiselect UI to dynamically support columns using a ConstraintLayout Flow
- only make images clickable if they trigger events

GT-1275 Support rendering Multiselect columns

---

ui/base-tool/build.gradle
ui/base-tool/src/main/java/org/cru/godtools/base/tool/BaseToolRendererModule.kt
ui/base-tool/src/main/java/org/cru/godtools/base/tool/activity/BaseToolActivity.kt
ui/base-tool/src/main/java/org/cru/godtools/base/tool/analytics/model/ContentAnalyticsEventAnalyticsActionEvent.kt
ui/base-tool/src/main/java/org/cru/godtools/base/tool/analytics/model/ContentEventAnalyticsActionEvent.kt
ui/base-tool/src/main/java/org/cru/godtools/base/tool/service/ContentEventAnalyticsHandler.kt
ui/base-tool/src/main/java/org/cru/godtools/base/tool/ui/controller/BaseController.kt
ui/base-tool/src/test/java/org/cru/godtools/base/tool/analytics/model/ContentAnalyticsEventAnalyticsActionEventTest.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/activity/TractActivityDataModel.kt
ui/tract-renderer/src/test/java/org/cru/godtools/tract/ui/controller/HeroControllerTest.kt

This will monitor for any triggered content events, and convert those events into Analytics Events that are sent to firebase.

GT-1267 Push any triggered content events to firebase

---

ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/service/ManifestManager.kt
ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/ui/controller/BaseController.kt
ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/ui/controller/CardController.kt
ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/ui/controller/MultiselectController.kt
ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/ui/controller/cache/UiControllerModule.kt
ui/base-tool/src/main/res/layout/tool_content_accordion_section.xml
ui/base-tool/src/main/res/layout/tool_content_card.xml
ui/base-tool/src/main/res/layout/tool_content_multiselect_option.xml
ui/base-tool/src/main/res/layout/tool_content_text.xml
ui/base-tool/src/main/res/values/styles.xml
ui/base-tool/src/main/res/values/styles_content.xml
ui/base-tool/src/main/res/values/styles_content_accordion.xml
ui/base-tool/src/main/res/values/styles_content_card.xml

- standardize a few card properties
- create UI controller for content card
- enable content cards in the renderer

GT-1353 Support rendering content cards

---

ui/cyoa-renderer/src/main/res/layout/cyoa_page_content.xml

- add horizontal padding for content pages
- add support for background color and images on content pages

GT-1325 Add background support to content pages

---

app/build.gradle
app/src/main/java/org/cru/godtools/activity/BasePlatformActivity.kt

- send signup requests to okta login
- always prompt for login

GT-1320 Use okta login for creating an account

---

ui/cyoa-renderer/src/main/kotlin/org/cru/godtools/tool/cyoa/ui/CyoaActivity.kt
ui/cyoa-renderer/src/test/kotlin/org/cru/godtools/tool/cyoa/ui/CyoaActivityTest.kt

GT-1327 Implement up navigation respecting the parentPage property for pages

---

ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/databinding/LinearLayoutAdapters.kt
ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/databinding/ViewGroupAdapters.kt
ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/model/Dimension.kt
ui/base-tool/src/main/res/layout/tool_content_button.xml
ui/base-tool/src/main/res/layout/tool_content_button_outlined.xml
ui/base-tool/src/main/res/layout/tool_content_image.xml

GT-1395 Support custom widths for Images and Buttons

---

ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/ui/controller/FlowController.kt
ui/base-tool/src/main/res/layout/tool_content_flow_item.xml

GT-1405 support gone-if and invisible-if for flow items

---

app/build.gradle
library/analytics/src/main/java/org/cru/godtools/analytics/model/AnalyticsActionEvent.kt
library/analytics/src/main/java/org/cru/godtools/analytics/model/AnalyticsBaseEvent.kt
library/analytics/src/main/java/org/cru/godtools/analytics/model/AnalyticsScreenEvent.kt
library/analytics/src/main/java/org/cru/godtools/analytics/model/AnalyticsSystem.kt
library/model/src/main/kotlin/org/cru/godtools/model/UserCounter.kt
library/sync/src/main/java/org/cru/godtools/sync/task/UserCounterSyncTasks.kt
library/user-data/build.gradle.kts
library/user-data/src/main/kotlin/org/cru/godtools/user/data/Counters.kt
library/user-data/src/main/kotlin/org/cru/godtools/user/data/UserDataModule.kt
library/user-data/src/main/kotlin/org/cru/godtools/user/data/analytics/UserAnalyticsService.kt
ui/article-renderer/src/main/java/org/cru/godtools/article/ui/ArticlesActivity.kt
ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/activity/BaseToolActivity.kt
ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/analytics/model/ContentAnalyticsEventAnalyticsActionEvent.kt
ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/analytics/model/ToolOpenedAnalyticsActionEvent.kt
ui/cyoa-renderer/src/main/kotlin/org/cru/godtools/tool/cyoa/ui/CyoaActivity.kt
ui/lesson-renderer/src/main/java/org/cru/godtools/tool/lesson/ui/LessonActivity.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/activity/TractActivity.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/analytics/model/ShareScreenActionEvents.kt

GT-1382 Create UserAnalyticsService that will log user counters

---

library/db/src/main/kotlin/org/keynote/godtools/android/db/Contract.kt
library/db/src/main/kotlin/org/keynote/godtools/android/db/GodToolsDatabase.kt
library/db/src/main/kotlin/org/keynote/godtools/android/db/ToolMapper.kt
library/model/src/main/kotlin/org/cru/godtools/model/Tool.kt
library/sync/src/main/java/org/cru/godtools/sync/task/BaseDataSyncTasks.kt
ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/activity/MultiLanguageToolActivityDataModel.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/activity/TractActivity.kt

- track a screen-share-disabled attribute for tools
- update visibility of screen share option based on setting in tool

Support disabling screen sharing for specific tools

---

ui/lesson-renderer/src/main/java/org/cru/godtools/tool/lesson/analytics/model/LessonPageAnalyticsScreenEvent.kt
ui/lesson-renderer/src/test/kotlin/org/cru/godtools/tool/lesson/analytics/model/LessonPageAnalyticsScreenEventTest.kt
ui/tract-renderer/src/main/java/org/cru/godtools/tract/analytics/model/TractPageAnalyticsScreenEvent.kt
ui/tract-renderer/src/test/java/org/cru/godtools/tract/analytics/model/TractPageAnalyticsScreenEventTest.kt

we don't want to record user counters for tract and lesson page views

GT-1382 Don't send tract & lesson page views to user analytics

---

library/api/src/main/java/org/cru/godtools/api/ApiModule.kt

Also, add a session retry interceptor to retry requests that fail due to a session error

Fix a couple minor authenticated API issues

---

gradle/libs.versions.toml
ui/base-tool/build.gradle.kts
ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/databinding/ConstraintLayoutAdapters.kt
ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/databinding/ViewGroupAdapters.kt
ui/base-tool/src/main/res/layout/tool_content_video.xml

GT-1390 Support video aspect-ratio, width, and gravity

---

build.gradle
ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/service/ManifestManager.kt
ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/ui/share/model/DefaultShareItem.kt

- workaround ktlint gradle bug
- fix a couple ktlint violations

Workaround a bug in the ktlint gradle plugin

---

library/db/src/main/kotlin/org/keynote/godtools/android/db/GodToolsDao.kt
ui/base-tool/src/main/AndroidManifest.xml
ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/activity/BaseToolActivity.kt
ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/model/shareable/ShareableImage.kt
ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/service/ManifestManager.kt
ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/service/ToolFileProvider.kt
ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/ui/share/model/ShareItem.kt
ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/ui/shareable/ShareableImageBottomSheetDialogFragment.kt
ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/ui/shareable/ShareableImageBottomSheetDialogFragmentDataModel.kt
ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/ui/shareable/model/ShareableImageShareItem.kt
ui/base-tool/src/main/res/layout/tool_share_item_shareable_image.xml
ui/base-tool/src/main/res/layout/tool_share_sheet.xml
ui/base-tool/src/main/res/layout/tool_shareable_image_sheet.xml
ui/base-tool/src/main/res/values/strings_tool_renderer.xml
ui/base-tool/src/main/res/xml/file_paths_tool.xml

- create initial shareables bottom sheet
- provide a method to get the latest translation as a Flow from the database
- create a getLatestPublishedManifestFlow to return the latest available manifest in a coroutines Flow
- enable a FileProvider for tools
- attempt to resolve the mime-type from a custom displayName
- create a bottom sheet for ShareableImages
- add shareable images to the custom share dialog

GT-1437 Create Shareables bottom sheet for tools

---

app/src/main/kotlin/org/cru/godtools/ui/dashboard/DashboardAppsFlyerDeepLinkResolver.kt
app/src/test/kotlin/org/cru/godtools/ui/dashboard/DashboardAppsFlyerDeepLinkResolverTest.kt
library/analytics/src/main/kotlin/org/cru/godtools/analytics/appsflyer/AppsFlyerAnalyticsService.kt
ui/article-renderer/src/main/kotlin/org/cru/godtools/article/ArticlesModule.kt
ui/article-renderer/src/main/kotlin/org/cru/godtools/article/analytics/appsflyer/ArticlesAppsFlyerDeepLinkResolver.kt
ui/article-renderer/src/test/kotlin/org/cru/godtools/article/analytics/appsflyer/ArticlesAppsFlyerDeepLinkResolverTest.kt
ui/base/src/main/kotlin/org/cru/godtools/base/ui/Activities.kt
ui/cyoa-renderer/src/main/kotlin/org/cru/godtools/tool/cyoa/analytics/appsflyer/CyoaAppsFlyerDeepLinkResolver.kt
ui/cyoa-renderer/src/main/kotlin/org/cru/godtools/tool/cyoa/ui/CyoaActivity.kt
ui/cyoa-renderer/src/test/kotlin/org/cru/godtools/tool/cyoa/analytics/appsflyer/CyoaAppsFlyerDeepLinkResolverTest.kt
ui/cyoa-renderer/src/test/kotlin/org/cru/godtools/tool/cyoa/ui/CyoaActivityTest.kt
ui/lesson-renderer/src/main/kotlin/org/cru/godtools/tool/lesson/analytics/appsflyer/LessonAppsFlyerDeepLinkResolver.kt
ui/lesson-renderer/src/test/kotlin/org/cru/godtools/tool/lesson/analytics/appsflyer/LessonAppsFlyerDeepLinkResolverTest.kt
ui/tract-renderer/src/main/kotlin/org/cru/godtools/tract/activity/TractActivity.kt
ui/tract-renderer/src/main/kotlin/org/cru/godtools/tract/analytics/appsflyer/TractAppsFlyerDeepLinkResolver.kt
ui/tract-renderer/src/test/kotlin/org/cru/godtools/tract/analytics/appsflyer/TractAppsFlyerDeepLinkResolverRobolectricTest.kt
ui/tract-renderer/src/test/kotlin/org/cru/godtools/tract/analytics/appsflyer/TractAppsFlyerDeepLinkResolverTest.kt

- configure the AppsFlyer DeepLinkListener
- update CyoaAppsFlyerDeepLinkResolver to leverage DeepLinkListener
- make it possible to deep link to a specific CYOA page
- add dashboard AppsFlyer deep link support
- add support for lesson deep link values from AppsFlyer

GT-1465 GT-1473 Update AppsFlyer Deep Link support

---

library/download-manager/src/main/kotlin/org/cru/godtools/download/manager/DownloadManagerModule.kt
library/download-manager/src/main/kotlin/org/cru/godtools/download/manager/GodToolsDownloadManager.kt
library/download-manager/src/test/kotlin/org/cru/godtools/download/manager/GodToolsDownloadManagerDispatcherTest.kt
library/download-manager/src/test/kotlin/org/cru/godtools/download/manager/GodToolsDownloadManagerTest.kt

- Move some automatic triggers for the DownloadManager to a separate Dispatcher singleton
- Refactor tests to utilize MockK instead of Mockito
- Refactor tests to use the latest version of coroutines tests

GT-1361 GT-1447 Update the DownloadManager tests

---

ui/base/src/main/kotlin/org/cru/godtools/base/ui/languages/LanguagesDropdownAdapter.kt
ui/tips-renderer/src/main/res/drawable/ic_disable_tips.xml
ui/tract-renderer/src/main/kotlin/org/cru/godtools/tract/ui/settings/SettingsBottomSheetDialogFragment.kt
ui/tract-renderer/src/main/res/layout/tract_settings_sheet.xml
ui/tract-renderer/src/main/res/values/strings_tract_renderer.xml

This makes a few requested UI adjustments for the tract settings

GT-1391 Tract Settings Adjustments

---

app/src/main/kotlin/org/cru/godtools/ui/dashboard/tools/ToolsFragment.kt
app/src/main/kotlin/org/cru/godtools/ui/tools/ToolsListFragment.kt
app/src/main/kotlin/org/cru/godtools/ui/tools/ToolsListFragmentDataModel.kt
library/analytics/src/main/kotlin/org/cru/godtools/analytics/firebase/model/FirebaseIamActionEvent.kt

- trigger the all tools analytics event from the new all tools UI
- remove the unused MODE_ALL for ToolsListFragment
- add a couple new analytics events to be targeted by iam

GT-1501 Add a couple new analytics events for IAM targetting

---

app/src/main/kotlin/org/cru/godtools/ui/tools/ToolsListFragment.kt
library/db/src/main/kotlin/org/keynote/godtools/android/db/GodToolsDao.kt
library/download-manager/src/main/kotlin/org/cru/godtools/download/manager/GodToolsDownloadManager.kt
library/download-manager/src/test/kotlin/org/cru/godtools/download/manager/GodToolsDownloadManagerTest.kt
library/initial-content/build.gradle.kts
library/initial-content/src/main/kotlin/org/cru/godtools/init/content/task/Tasks.kt
library/initial-content/src/test/kotlin/org/cru/godtools/init/content/task/TasksTest.kt
library/model/src/main/kotlin/org/cru/godtools/model/event/Events.kt
library/model/src/main/kotlin/org/cru/godtools/model/event/ToolUsedEvent.kt
library/sync/src/main/kotlin/org/cru/godtools/sync/task/AnalyticsSyncTasks.kt
library/sync/src/main/kotlin/org/cru/godtools/sync/task/BaseDataSyncTasks.kt
library/sync/src/main/kotlin/org/cru/godtools/sync/task/BaseSyncTasks.kt
library/sync/src/main/kotlin/org/cru/godtools/sync/task/FollowupSyncTasks.kt
library/sync/src/main/kotlin/org/cru/godtools/sync/task/LanguagesSyncTasks.kt
library/sync/src/main/kotlin/org/cru/godtools/sync/task/ToolSyncTasks.kt
library/sync/src/test/kotlin/org/cru/godtools/sync/task/BaseDataSyncTasksTest.kt
ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/service/ManifestManager.kt
ui/base-tool/src/test/kotlin/org/cru/godtools/base/tool/service/ManifestManagerTest.kt

Remove several events that are no longer being listened for anywhere
- remove unnecessary AttachmentUpdateEvent
- remove unnecessary ToolUpdateEvent

EventBus Event Cleanup

---

app/src/main/kotlin/org/cru/godtools/util/ActivityUtils.kt
library/db/src/main/kotlin/org/keynote/godtools/android/db/Contract.kt
library/db/src/main/kotlin/org/keynote/godtools/android/db/GodToolsDatabase.kt
library/db/src/main/kotlin/org/keynote/godtools/android/db/ToolMapper.kt
library/download-manager/build.gradle.kts
library/download-manager/src/main/kotlin/org/cru/godtools/download/manager/GodToolsDownloadManager.kt
library/download-manager/src/test/kotlin/org/cru/godtools/download/manager/GodToolsDownloadManagerQueriesTest.kt
library/model/src/main/kotlin/org/cru/godtools/model/Tool.kt
library/sync/src/main/kotlin/org/cru/godtools/sync/task/BaseDataSyncTasks.kt
library/sync/src/main/kotlin/org/cru/godtools/sync/task/ToolSyncTasks.kt

GT-1556 Metatool models and sync

---

app/src/main/kotlin/org/cru/godtools/adapter/BannerAdapter.kt
app/src/main/kotlin/org/cru/godtools/ui/dashboard/lessons/LessonsLayout.kt
app/src/main/kotlin/org/cru/godtools/ui/tools/ToolsListFragment.kt
app/src/main/res/layout/dashboard_lessons_header.xml
app/src/main/res/values/strings_dashboard.xml
ui/base/src/main/kotlin/org/cru/godtools/base/ui/theme/GodToolsTheme.kt

- make BannerAdapter a normal RecyclerView Adapter and utilize ComposedAdapter to combine it with other adapters
- add some header text to the lessons UI

GT-1526 Add some text to the lessons UI

---

ui/tutorial-renderer/src/main/java/org/cru/godtools/tutorial/Page.kt
ui/tutorial-renderer/src/main/java/org/cru/godtools/tutorial/activity/TutorialActivity.kt

also, we support deeplinking to all available languages for Questions About God

GT-1596 enable quick links screen for Latvian and Vietnamese

---

app/src/main/kotlin/org/cru/godtools/ui/tooldetails/ToolDetailsPagerAdapter.kt
app/src/main/kotlin/org/cru/godtools/ui/tools/ToolsAdapterViewModel.kt
build.gradle
library/download-manager/src/main/kotlin/org/cru/godtools/download/manager/GodToolsDownloadManager.kt
library/download-manager/src/test/kotlin/org/cru/godtools/download/manager/GodToolsDownloadManagerQueriesTest.kt
ui/base-tool/src/test/kotlin/org/cru/godtools/base/tool/databinding/ToolGenericFragmentActivityBindingTest.kt
ui/base/src/main/kotlin/org/cru/godtools/base/ui/languages/LanguagesDropdownAdapter.kt
ui/lesson-renderer/src/main/kotlin/org/cru/godtools/tool/lesson/util/LessonDeepLinkUtils.kt

- make sure the ktlint hack is executed after the project has been configured
- fix several ktlint violations

ktlint fixes

---

app/src/main/kotlin/org/cru/godtools/ui/tools/ToolsAdapterViewModel.kt
app/src/main/res/layout/activity_dashboard.xml
app/src/test/kotlin/org/cru/godtools/databinding/ToolsListItemToolBindingTest.kt
buildSrc/src/main/kotlin/AndroidConfiguration.kt
gradle/libs.versions.toml
library/download-manager/build.gradle.kts
library/download-manager/src/main/kotlin/org/cru/godtools/download/manager/GodToolsDownloadManager.kt
library/download-manager/src/test/kotlin/org/cru/godtools/download/manager/GodToolsDownloadManagerTest.kt
library/model/src/main/kotlin/org/cru/godtools/model/Translation.kt
ui/base/src/main/kotlin/org/cru/godtools/base/ui/theme/GodToolsTheme.kt
ui/base/src/main/kotlin/org/cru/godtools/base/ui/util/LocaleTypefaceUtils.kt
ui/base/src/main/kotlin/org/cru/godtools/base/ui/util/ModelUtils.kt

This PR contains a bunch of updates to underlying framework functionality in preparation for the Compose layout for the home screen

GT-1529 Prep work for the Dashboard Home Composable

---

app/src/main/kotlin/org/cru/godtools/ui/tools/ToolsListFragment.kt
app/src/main/kotlin/org/cru/godtools/ui/tools/ToolsListFragmentDataModel.kt
library/base/src/main/kotlin/org/cru/godtools/base/Settings.kt
library/db/build.gradle.kts
library/db/src/main/kotlin/org/keynote/godtools/android/db/GodToolsDao.kt
library/db/src/main/kotlin/org/keynote/godtools/android/db/repository/ToolsRepository.kt
library/db/src/test/kotlin/org/keynote/godtools/android/db/repository/ToolsRepositoryTest.kt
library/download-manager/src/main/kotlin/org/cru/godtools/download/manager/GodToolsDownloadManager.kt
library/download-manager/src/test/kotlin/org/cru/godtools/download/manager/GodToolsDownloadManagerTest.kt
library/initial-content/src/main/kotlin/org/cru/godtools/init/content/task/Tasks.kt
library/initial-content/src/test/kotlin/org/cru/godtools/init/content/task/TasksTest.kt

- move tool reordering logic into a ToolsRepository object
- utilize coroutine flows for loading the data on a tool list

GT-1529 Create a ToolsRepository

---

.github/workflows/build.yml
gradle.properties

Make some adjustments to hopefully prevent the gradle daemon from crashing within GHA runners

Attempt to improve GHA reliability

---

app/build.gradle.kts
app/src/main/kotlin/org/cru/godtools/ui/dashboard/home/HomeLayout.kt
app/src/main/kotlin/org/cru/godtools/ui/dashboard/home/HomeViewModel.kt
app/src/test/kotlin/org/cru/godtools/ExternalSingletonsModule.kt
gradle/libs.versions.toml
library/sync/src/main/kotlin/org/cru/godtools/sync/GodToolsSyncService.kt
library/sync/src/test/kotlin/org/cru/godtools/sync/GodToolsSyncServiceTest.kt

- make it possible to trigger tools sync from a coroutine and suspend until the sync completes
- support swipe refresh for the Home UI

GT-1529 Support Swipe Refresh for the new Home Screen

---

gradle/libs.versions.toml
ui/tutorial-renderer/build.gradle.kts
ui/tutorial-renderer/src/main/java/org/cru/godtools/tutorial/TutorialCallbacks.kt
ui/tutorial-renderer/src/main/java/org/cru/godtools/tutorial/TutorialPageFragment.kt
ui/tutorial-renderer/src/main/java/org/cru/godtools/tutorial/activity/TutorialActivity.kt
ui/tutorial-renderer/src/main/java/org/cru/godtools/tutorial/layout/TipsLayout.kt
ui/tutorial-renderer/src/main/res/layout/tutorial_tips_learn.xml
ui/tutorial-renderer/src/main/res/layout/tutorial_tips_light.xml
ui/tutorial-renderer/src/main/res/layout/tutorial_tips_start.xml
ui/tutorial-renderer/src/main/res/values/ids.xml

Compose has been added to the last two pages for the tutorial tips.

Adding compose to the last two tutorial tips pages.

---

app/src/main/kotlin/org/cru/godtools/ui/banner/Banner.kt
app/src/main/kotlin/org/cru/godtools/ui/banner/TutorialFeaturesBanner.kt
app/src/main/kotlin/org/cru/godtools/ui/dashboard/home/HomeLayout.kt
app/src/main/kotlin/org/cru/godtools/ui/dashboard/home/HomeViewModel.kt
ui/tutorial-renderer/src/main/java/org/cru/godtools/tutorial/activity/TutorialActivity.kt

- create a Composable TutorialFeaturesBanner
- display the features tutorial banner on the home layout

GT-1529 Implement the favorites tutorial banner

---

ui/tutorial-renderer/src/main/java/org/cru/godtools/tutorial/TutorialPageFragment.kt
ui/tutorial-renderer/src/main/java/org/cru/godtools/tutorial/layout/TutorialLiveShareLayout.kt
ui/tutorial-renderer/src/main/res/layout/tutorial_live_share_description.xml
ui/tutorial-renderer/src/main/res/layout/tutorial_live_share_mirrored.xml
ui/tutorial-renderer/src/main/res/layout/tutorial_live_share_start.xml
ui/tutorial-renderer/src/main/res/values/ids.xml

Compose is being added for the Live share tutorial

Compose for Live Share Tutorial

---

app/build.gradle.kts
app/src/main/kotlin/org/cru/godtools/adapter/BannerAdapter.kt
app/src/main/kotlin/org/cru/godtools/ui/dashboard/DashboardActivity.kt
app/src/main/kotlin/org/cru/godtools/ui/dashboard/tools/ToolsFragment.kt
app/src/main/kotlin/org/cru/godtools/ui/dashboard/tools/ToolsFragmentDataModel.kt
app/src/main/kotlin/org/cru/godtools/ui/tooldetails/ToolDetailsFragment.kt
app/src/main/kotlin/org/cru/godtools/ui/tools/ToolViewModels.kt
app/src/main/kotlin/org/cru/godtools/widget/Banners.kt
app/src/main/res/layout/widget_banner.xml
gradle/libs.versions.toml

This banner was never ported to the new all tools UI when it was built.

GT-1675 Restore banner on All Tools

---

ui/article-aem-renderer/src/main/kotlin/org/cru/godtools/article/aem/service/AemArticleManager.kt
ui/article-aem-renderer/src/test/kotlin/org/cru/godtools/article/aem/db/AbstractArticleRoomDatabaseTest.kt
ui/article-aem-renderer/src/test/kotlin/org/cru/godtools/article/aem/db/ArticleRepositoryTest.kt
ui/article-aem-renderer/src/test/kotlin/org/cru/godtools/article/aem/db/TranslationRepositoryTest.kt
ui/article-aem-renderer/src/test/kotlin/org/cru/godtools/article/aem/service/AemArticleManagerDispatcherTest.kt
ui/article-aem-renderer/src/test/kotlin/org/cru/godtools/article/aem/service/AemArticleManagerFileManagerTest.kt
ui/article-aem-renderer/src/test/kotlin/org/cru/godtools/article/aem/service/AemArticleManagerTest.kt
ui/base/src/test/kotlin/org/cru/godtools/base/ui/databinding/YouTubePlayerViewBindingAdapterTest.kt

- convert article-aem-renderer tests to use MockK
- convert ui:base tests to use MockK

Update several tests to use MockK instead of Mockito

---

app/src/main/kotlin/org/cru/godtools/ui/banner/Banner+Preview.kt
app/src/main/kotlin/org/cru/godtools/ui/banner/Banner.kt

- use a custom Layout to provide a more dynamic Material Banner layout
- add icon support to banners

Update Compose Material Banners to better follow spec

---

ui/tutorial-renderer/src/main/java/org/cru/godtools/tutorial/Page.kt
ui/tutorial-renderer/src/main/java/org/cru/godtools/tutorial/layout/onboarding/TutorialOnboardingLayout+Preview.kt
ui/tutorial-renderer/src/main/java/org/cru/godtools/tutorial/layout/onboarding/TutorialOnboardingLayout.kt
ui/tutorial-renderer/src/main/java/org/cru/godtools/tutorial/layout/onboarding/TutorialOnboardingLinksLayout.kt
ui/tutorial-renderer/src/main/java/org/cru/godtools/tutorial/layout/onboarding/TutorialOnboardingPositioning.kt

- track the action button label in the Page enum
- utilize the TutorialMedia composable for onboarding
- create previews for the onboarding tutorial
- make TutorialPositionReferences reusable by a few different layouts
- make some layout adjustments to the onboarding layout

GT-1600 Make some updates to the Onboarding Composables

---

library/api/src/main/kotlin/org/cru/godtools/api/ToolsApi.kt
library/sync/build.gradle.kts
library/sync/src/main/kotlin/org/cru/godtools/sync/GodToolsSyncService.kt
library/sync/src/main/kotlin/org/cru/godtools/sync/task/SyncTaskModule.kt
library/sync/src/main/kotlin/org/cru/godtools/sync/task/ToolSyncTasks.kt
ui/article-renderer/src/test/kotlin/org/cru/godtools/article/ExternalSingletonsModule.kt
ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/activity/BaseToolActivity.kt
ui/cyoa-renderer/src/test/kotlin/org/cru/godtools/tool/cyoa/ExternalSingletonsModule.kt
ui/lesson-renderer/src/test/kotlin/org/cru/godtools/tool/lesson/ExternalSingletonsModule.kt
ui/tract-renderer/src/test/kotlin/org/cru/godtools/tract/ExternalSingletonsModule.kt

- add logic to sync an individual tool only using it's code
- update tool renderers to only sync the tool being loaded and not all tools

Support syncing an individual tool

---

app/src/test/kotlin/org/cru/godtools/ExternalSingletonsModule.kt
library/sync/src/main/kotlin/org/cru/godtools/sync/GodToolsSyncService.kt
library/sync/src/main/kotlin/org/cru/godtools/sync/task/ToolSyncTasks.kt

- more directly trigger tools sync
- update syncTool to use executeSync which will handle IOExceptions

Tweaks to the sync service

---

app/src/main/kotlin/org/cru/godtools/ui/account/AccountLayout.kt
app/src/main/kotlin/org/cru/godtools/ui/account/AccountViewModel.kt
app/src/main/res/values/strings_profile.xml
library/account/src/main/kotlin/org/cru/godtools/account/GodToolsAccountManager.kt
library/account/src/main/kotlin/org/cru/godtools/account/provider/AccountProvider.kt
library/account/src/main/kotlin/org/cru/godtools/account/provider/okta/OktaAccountProvider.kt
library/account/src/test/kotlin/org/cru/godtools/account/provider/okta/OktaAccountProviderTest.kt
library/db/src/main/kotlin/org/cru/godtools/db/repository/UserRepository.kt
library/db/src/main/kotlin/org/cru/godtools/db/room/dao/UserDao.kt
library/db/src/main/kotlin/org/cru/godtools/db/room/repository/UserRoomRepository.kt
library/model/src/main/kotlin/org/cru/godtools/model/User.kt
library/user-data/build.gradle.kts
library/user-data/src/main/kotlin/org/cru/godtools/user/data/UserManager.kt
library/user-data/src/test/kotlin/org/cru/godtools/user/data/UserManagerTest.kt

- create a UserManager that will manage User related data
- add a unit test for UserManager.userFlow
- utilize tagsFlow to update AccountInfo if the userId changes
- merge AccountInfo into the User object
- display the account creation time on the Account UI

GT-1824 Display the Account Creation Date on the Account UI

---

library/analytics/src/main/kotlin/org/cru/godtools/analytics/firebase/FirebaseAnalyticsService.kt
library/analytics/src/main/kotlin/org/cru/godtools/analytics/snowplow/SnowplowAnalyticsService.kt
library/analytics/src/test/kotlin/org/cru/godtools/analytics/firebase/FirebaseAnalyticsServiceTest.kt
library/analytics/src/test/kotlin/org/cru/godtools/analytics/snowplow/SnowplowAnalyticsServiceTest.kt
library/model/src/main/kotlin/org/cru/godtools/model/User.kt
library/user-data/src/main/kotlin/org/cru/godtools/user/data/UserManager.kt

- expose the grMasterPersonId via the User object
- update FirebaseAnalyticsService to utilize the userFlow
- utilize the userFlow for SnowplowAnalyticsService

GT-1263 Consolidate AccountInfo and the User object

---

ui/tutorial-renderer/src/main/kotlin/org/cru/godtools/tutorial/TutorialActivity.kt
ui/tutorial-renderer/src/main/kotlin/org/cru/godtools/tutorial/layout/TutorialLayout.kt
ui/tutorial-renderer/src/main/kotlin/org/cru/godtools/tutorial/layout/onboarding/TutorialOnboardingLinksLayout.kt
ui/tutorial-renderer/src/main/kotlin/org/cru/godtools/tutorial/theme/GodToolsTutorialTheme.kt

- use the Material3 Scaffold class
- create a GodToolsTutorialTheme that sets the lineBreak style

GT-1831 Utilize new LineBreak configuration for the tutorial

---

app/build.gradle.kts
app/src/main/kotlin/org/cru/godtools/ui/tooldetails/ToolDetailsAbout.kt
app/src/main/kotlin/org/cru/godtools/ui/tooldetails/ToolDetailsLayout.kt
app/src/main/res/values/strings_tool_details.xml
app/src/testDebug/kotlin/org/cru/godtools/ui/tooldetails/ToolDetailsLayoutTest.kt
gradle/libs.versions.toml
library/db/src/main/kotlin/org/keynote/godtools/android/db/Contract.kt
library/db/src/main/kotlin/org/keynote/godtools/android/db/GodToolsDatabase.kt
library/db/src/main/kotlin/org/keynote/godtools/android/db/TranslationMapper.kt
library/model/src/main/kotlin/org/cru/godtools/model/Translation.kt
library/model/src/test/kotlin/org/cru/godtools/model/TranslationTest.kt
library/model/src/test/resources/org/cru/godtools/model/translation.json
library/sync/src/main/kotlin/org/cru/godtools/sync/task/BaseDataSyncTasks.kt

GT-1864 Utilize an Accordion on the Tool Details UI

---

library/base/build.gradle.kts
library/base/src/main/kotlin/org/cru/godtools/base/Settings.kt
library/base/src/test/kotlin/org/cru/godtools/base/SettingsTest.kt
library/initial-content/src/main/kotlin/org/cru/godtools/init/content/InitialContentImporter.kt
library/initial-content/src/main/kotlin/org/cru/godtools/init/content/task/Tasks.kt

This use case was accidentally removed when implementing GT-1716 in this PR: #2430

GT-1885 Initialize the primaryLanguage on first use

---

library/download-manager/src/main/kotlin/org/cru/godtools/download/manager/GodToolsDownloadManager.kt
library/download-manager/src/test/kotlin/org/cru/godtools/download/manager/GodToolsDownloadManagerTest.kt
ui/article-renderer/src/test/kotlin/org/cru/godtools/article/ExternalSingletonsModule.kt
ui/cyoa-renderer/src/test/kotlin/org/cru/godtools/tool/cyoa/ExternalSingletonsModule.kt
ui/lesson-renderer/src/test/kotlin/org/cru/godtools/tool/lesson/ExternalSingletonsModule.kt
ui/tract-renderer/src/test/kotlin/org/cru/godtools/tract/ExternalSingletonsModule.kt

This method was only used in tests and no longer in any shipping code

remove unused getDownloadProgressLiveData()

---

library/db/src/main/kotlin/org/cru/godtools/db/DatabaseModule.kt
library/db/src/main/kotlin/org/cru/godtools/db/repository/DownloadedFilesRepository.kt
library/db/src/main/kotlin/org/keynote/godtools/android/db/repository/LegacyDownloadedFilesRepository.kt
library/db/src/test/kotlin/org/cru/godtools/db/repository/DownloadedFilesRepositoryIT.kt
library/db/src/test/kotlin/org/keynote/godtools/android/db/repository/GodToolsDaoRule.kt
library/db/src/test/kotlin/org/keynote/godtools/android/db/repository/LegacyDownloadedFilesRepositoryIT.kt
library/download-manager/src/main/kotlin/org/cru/godtools/download/manager/GodToolsDownloadManager.kt
library/download-manager/src/test/kotlin/org/cru/godtools/download/manager/GodToolsDownloadManagerDispatcherTest.kt
library/download-manager/src/test/kotlin/org/cru/godtools/download/manager/GodToolsDownloadManagerTest.kt
library/model/src/main/kotlin/org/cru/godtools/model/DownloadedFile.kt
library/model/src/main/kotlin/org/cru/godtools/model/DownloadedTranslationFile.kt
library/model/src/main/kotlin/org/cru/godtools/model/LocalFile.kt
library/model/src/main/kotlin/org/cru/godtools/model/TranslationFile.kt

This repository is used to track which files have been downloaded by the download manager

GT-1913 Create a DownloadedFilesRepository

---

library/sync/src/main/kotlin/org/cru/godtools/sync/GodToolsSyncService.kt
library/sync/src/test/kotlin/org/cru/godtools/sync/GodToolsSyncServiceTest.kt

when a coroutine is cancelled it triggers a `CancellationException`, this is normal behavior for coroutines.
This specific cancellation was primarily being triggered because we launch a sync of the available tools within the lifecycle of the dashboard activity, if the user leaves the dashboard (e.g. exiting the app) it cancels the sync.
We still schedule the sync to happen in the background later by using workManager

GT-1912 Don't log cancellation exceptions

---

build.gradle
buildSrc/src/main/kotlin/AndroidConfiguration.kt
buildSrc/src/main/kotlin/godtools.library-conventions.gradle.kts
gradle/libs.versions.toml
library/account/build.gradle.kts
library/analytics/build.gradle.kts
library/api/build.gradle.kts
library/base/build.gradle.kts
library/db/build.gradle.kts
library/download-manager/build.gradle.kts
library/initial-content/build.gradle.kts
library/model/build.gradle.kts
library/sync/build.gradle.kts
library/user-data/build.gradle.kts
ui/article-aem-renderer/build.gradle.kts
ui/article-renderer/build.gradle.kts
ui/base-tool/build.gradle.kts
ui/base/build.gradle.kts
ui/cyoa-renderer/build.gradle.kts
ui/lesson-renderer/build.gradle.kts
ui/shortcuts/build.gradle.kts
ui/tips-renderer/build.gradle.kts
ui/tract-renderer/build.gradle.kts
ui/tutorial-renderer/build.gradle.kts

- utilize a convention plugin for configuring library subprojects
- configure common dependencies via buildSrc

Create convention plugin for build scripts

---

app/build.gradle.kts
app/src/main/kotlin/org/cru/godtools/GodToolsApplication.kt
gradle/libs.versions.toml

- remove unnecessary missing splits detection
- replace play core with the newer feature delivery core split

Upgrade play services core

---

app/build.gradle.kts
app/src/main/kotlin/org/cru/godtools/ui/account/AccountActivity.kt
app/src/main/kotlin/org/cru/godtools/ui/account/AccountLayout.kt
app/src/main/kotlin/org/cru/godtools/ui/drawer/DrawerMenuLayout.kt
gradle/libs.versions.toml

- move Header layout to a separate composable
- Switch to the material PullRefresh component
- add the Drawer Menu to the Account UI

Improvements to the Account UI layout

---

.github/workflows/onesky-upload.yml

Dependent on:
Test run: https://github.com/CruGlobal/godtools-android/actions/runs/4533621661

Update the OneSky upload workflow to load OneSky secrets from AWS

---

library/db/room-schemas/org.cru.godtools.db.room.GodToolsRoomDatabase/7.json
library/db/src/main/kotlin/org/cru/godtools/db/room/GodToolsRoomDatabase.kt
library/db/src/main/kotlin/org/cru/godtools/db/room/entity/UserEntity.kt
library/db/src/test/kotlin/org/cru/godtools/db/room/GodToolsRoomDatabaseMigrationIT.kt
library/model/src/main/kotlin/org/cru/godtools/model/User.kt

fetch and track a user name from the API in the room database

---

app/build.gradle.kts
app/src/main/AndroidManifest.xml
app/src/main/kotlin/org/cru/godtools/activity/BasePlatformActivity.kt
app/src/test/kotlin/org/cru/godtools/ExternalSingletonsModule.kt
gradle/libs.versions.toml
library/account/build.gradle.kts
library/account/src/main/kotlin/org/cru/godtools/account/AccountType.kt
library/account/src/main/kotlin/org/cru/godtools/account/GodToolsAccountManager.kt
library/account/src/main/kotlin/org/cru/godtools/account/provider/AccountProvider.kt
library/account/src/main/kotlin/org/cru/godtools/account/provider/facebook/FacebookAccountProvider.kt
library/account/src/main/kotlin/org/cru/godtools/account/provider/facebook/FacebookModule.kt
library/account/src/main/kotlin/org/cru/godtools/account/provider/okta/OktaAccountProvider.kt
library/account/src/test/kotlin/org/cru/godtools/account/provider/facebook/FacebookAccountProviderTest.kt
library/account/src/test/kotlin/org/cru/godtools/account/provider/okta/OktaAccountProviderTest.kt
library/analytics/build.gradle.kts
library/analytics/src/main/AndroidManifest.xml
library/api/build.gradle.kts
library/api/src/main/kotlin/org/cru/godtools/api/model/AuthToken.kt
library/api/src/test/kotlin/org/cru/godtools/api/model/AuthTokenTest.kt
library/api/src/test/resources/org/cru/godtools/api/model/auth_token.json

GT-1950 Add support for facebook login

---

library/db/src/main/kotlin/org/cru/godtools/db/repository/AttachmentsRepository.kt
library/db/src/main/kotlin/org/keynote/godtools/android/db/Contract.kt
library/db/src/main/kotlin/org/keynote/godtools/android/db/repository/LegacyAttachmentsRepository.kt
library/db/src/test/kotlin/org/cru/godtools/db/repository/AttachmentsRepositoryIT.kt
library/sync/src/main/kotlin/org/cru/godtools/sync/repository/SyncRepository.kt

- pass the tool object to removeAttachmentsMissingFromSync()
- remove some dead code from the GodToolsDao Contract

db cleanup

---

app/src/main/kotlin/org/cru/godtools/ui/languages/LanguagesFragmentViewModel.kt
app/src/main/kotlin/org/cru/godtools/ui/languages/paralleldialog/ParallelLanguageDialogFragment.kt
app/src/main/kotlin/org/cru/godtools/ui/tools/ToolViewModels.kt
library/db/src/main/kotlin/org/keynote/godtools/android/db/TranslationMapper.kt
library/db/src/test/kotlin/org/cru/godtools/db/repository/TranslationsRepositoryIT.kt
library/download-manager/src/main/kotlin/org/cru/godtools/download/manager/GodToolsDownloadManager.kt
library/download-manager/src/test/kotlin/org/cru/godtools/download/manager/GodToolsDownloadManagerDispatcherTest.kt
library/initial-content/src/main/kotlin/org/cru/godtools/init/content/task/Tasks.kt
library/initial-content/src/test/kotlin/org/cru/godtools/init/content/task/TasksTest.kt
library/model/src/main/kotlin/org/cru/godtools/model/Translation.kt
library/sync/src/main/kotlin/org/cru/godtools/sync/repository/SyncRepository.kt
ui/tract-renderer/src/main/kotlin/org/cru/godtools/tract/ui/settings/SettingsBottomSheetDialogFragmentDataModel.kt

- only store valid translations
- remove isPublished checks because we only store published translations

remove unnecessary Translation.isPublished property

---

library/db/src/main/kotlin/org/cru/godtools/db/repository/TranslationsRepository.kt
library/db/src/main/kotlin/org/keynote/godtools/android/db/Contract.kt
library/db/src/main/kotlin/org/keynote/godtools/android/db/TranslationMapper.kt
library/db/src/main/kotlin/org/keynote/godtools/android/db/repository/LegacyTranslationsRepository.kt
library/db/src/test/kotlin/org/cru/godtools/db/repository/TranslationsRepositoryIT.kt
library/model/src/main/kotlin/org/cru/godtools/model/Translation.kt
ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/activity/BaseSingleToolActivityDataModel.kt
ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/activity/MultiLanguageToolActivityDataModel.kt
ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/service/ManifestManager.kt
ui/base-tool/src/test/kotlin/org/cru/godtools/base/tool/activity/MultiLanguageToolActivityDataModelTest.kt
ui/cyoa-renderer/src/test/kotlin/org/cru/godtools/tool/cyoa/MockDatabaseModule.kt
ui/tract-renderer/src/test/kotlin/org/cru/godtools/tool/tract/MockDatabaseModule.kt
ui/tract-renderer/src/test/kotlin/org/cru/godtools/tract/activity/TractActivityTest.kt

we no longer use this property for anything

GT-1949 Remove Translation.lastAccessed

---

library/db/src/main/kotlin/org/cru/godtools/db/repository/TranslationsRepository.kt
library/db/src/main/kotlin/org/keynote/godtools/android/db/repository/LegacyTranslationsRepository.kt
library/db/src/test/kotlin/org/cru/godtools/db/repository/TranslationsRepositoryIT.kt
library/download-manager/src/main/kotlin/org/cru/godtools/download/manager/GodToolsDownloadManager.kt
library/download-manager/src/test/kotlin/org/cru/godtools/download/manager/GodToolsDownloadManagerDispatcherTest.kt

- s/Languages/Locales/
- add a unit test for getTranslationsForToolsAndLanguagesFlow()

GT-1949 Add test for getTranslationsForToolsAndLocalesFlow()

---

.github/workflows/build.yml
build.gradle
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/AndroidTestConfiguration.kt
gradle/libs.versions.toml

This is currently blocked on Kotlin Kover fully supporting Android projects.
Relevant issues:

GT-1966 Enable Kotlin Kover

---

library/db/room-schemas/org.cru.godtools.db.room.GodToolsRoomDatabase/12.json
library/db/src/main/kotlin/org/cru/godtools/db/repository/LanguagesRepository.kt
library/db/src/main/kotlin/org/cru/godtools/db/room/GodToolsRoomDatabase.kt
library/db/src/main/kotlin/org/cru/godtools/db/room/dao/LanguagesDao.kt
library/db/src/main/kotlin/org/cru/godtools/db/room/entity/LanguageEntity.kt
library/db/src/main/kotlin/org/cru/godtools/db/room/entity/partial/SyncLanguage.kt
library/db/src/main/kotlin/org/cru/godtools/db/room/repository/LanguagesRoomRepository.kt
library/db/src/test/kotlin/org/cru/godtools/db/repository/LanguagesRepositoryIT.kt
library/db/src/test/kotlin/org/cru/godtools/db/room/GodToolsRoomDatabaseMigrationIT.kt
library/model/src/main/kotlin/org/cru/godtools/model/Language.kt
library/model/src/testFixtures/java/org/cru/godtools/model/LanguageMatchers.java

- remove equals and hashCode implementations from the Language model
- track an isAdded flag for languages
- add repository methods to pin/unpin a language
- don't overwrite the isAdded flag when updating a language from sync

GT-1988 Track which languages have been added

---

gradle/libs.versions.toml
settings.gradle.kts

- use rtl-viewpager from jitpack now that jcenter redirects to repo1 which does not have this library
- remove the jcenter repository

Remove jcenter repository

---

library/db/src/main/kotlin/org/cru/godtools/db/repository/LanguagesRepository.kt
library/db/src/main/kotlin/org/cru/godtools/db/room/dao/LanguagesDao.kt
library/db/src/main/kotlin/org/cru/godtools/db/room/repository/LanguagesRoomRepository.kt
library/db/src/test/kotlin/org/cru/godtools/db/repository/LanguagesRepositoryIT.kt
library/download-manager/src/main/kotlin/org/cru/godtools/download/manager/GodToolsDownloadManager.kt
library/download-manager/src/test/kotlin/org/cru/godtools/download/manager/GodToolsDownloadManagerDispatcherTest.kt

Update the `GodToolsDownloadManager.Dispatcher` to trigger downloads for the app language and any pinned languages

GT-1988 Download any pinned languages

---

app/src/main/kotlin/org/cru/godtools/ui/languages/downloadable/DownloadableLanguagesLayout.kt
ui/base/src/main/kotlin/org/cru/godtools/base/ui/theme/GodToolsTheme+Preview.kt

- add previews for SearchBar colors
- use the GodToolsTheme property to set search bar colors

Add previews for searchBarColors

---

.github/workflows/build.yml
build-logic/build.gradle.kts
build-logic/src/main/kotlin/AndroidConfiguration.kt
build-logic/src/main/kotlin/AndroidTestConfiguration.kt
build-logic/src/main/kotlin/EventBusConfiguration.kt
build-logic/src/main/kotlin/org/cru/godtools/gradle/bundledcontent/BundledContentConfiguration.kt
build-logic/src/main/kotlin/org/cru/godtools/gradle/bundledcontent/ExtractTranslationTask.kt
gradle/libs.versions.toml

- enable ktlint for the build-logic included build
- ktlint fixes

Enable ktlint for build-logic

---

library/download-manager/src/main/kotlin/org/cru/godtools/downloadmanager/GodToolsDownloadManager.kt
library/download-manager/src/test/kotlin/org/cru/godtools/downloadmanager/GodToolsDownloadManagerDispatcherTest.kt

- download all tools for pinned languages
- remove some duplciated logic for dispatching attachment downloads

GT-2161 Adjust download logic for pinned languages

---

app/src/testDebug/kotlin/org/cru/godtools/ui/dashboard/AppUpdateSnackbarTest.kt
library/analytics/src/test/kotlin/org/cru/godtools/analytics/appsflyer/AppsFlyerAnalyticsServiceTest.kt
library/analytics/src/test/kotlin/org/cru/godtools/analytics/firebase/FirebaseAnalyticsServiceTest.kt
library/analytics/src/test/kotlin/org/cru/godtools/analytics/model/LaunchAnalyticsActionEventTest.kt
library/api/src/test/kotlin/org/cru/godtools/api/model/AuthTokenTest.kt
library/base/src/test/kotlin/org/cru/godtools/base/FileSystemTest.kt
library/base/src/test/kotlin/org/cru/godtools/base/SettingsTest.kt
library/base/src/test/kotlin/org/cru/godtools/base/util/LocaleUtilsGetDisplayNameTest.kt
library/download-manager/src/test/kotlin/org/cru/godtools/downloadmanager/GodToolsDownloadManagerDispatcherTest.kt
library/download-manager/src/test/kotlin/org/cru/godtools/downloadmanager/GodToolsDownloadManagerTest.kt

- convert library analytics tests to use Kotlin Test
- update AuthTokenTest to utilize kotlin-test
- move several DownloadManager tests to utilize kotlin-test
- convert several tests to utilize kotlin-test

kotlin-test updates

---

app/src/main/kotlin/org/cru/godtools/ui/dashboard/DashboardLayout.kt
app/src/main/kotlin/org/cru/godtools/ui/languages/LanguageSettingsLayout.kt
app/src/main/kotlin/org/cru/godtools/ui/languages/app/AppLanguageLayout.kt
ui/lesson-renderer/src/main/res/drawable/ic_action_next.xml
ui/lesson-renderer/src/main/res/drawable/ic_action_previous.xml

- auto-mirror the Up navigation arrow
- set the next and previous buttons to auto-mirror

GT-2068 Several RTL fixes

---

app/config/ktlint/baseline.xml
app/src/main/kotlin/org/cru/godtools/ui/account/activity/AccountActivityBadges.kt
app/src/main/kotlin/org/cru/godtools/ui/dashboard/lessons/LessonsLayout.kt
app/src/main/kotlin/org/cru/godtools/ui/drawer/DrawerMenuLayout.kt
app/src/main/kotlin/org/cru/godtools/ui/languages/LanguageLayouts+Previews.kt
build-logic/build.gradle.kts
build-logic/src/main/kotlin/KtlintConfiguration.kt
build-logic/src/main/kotlin/Project.kt
build-logic/src/main/kotlin/godtools.application-conventions.gradle.kts
build-logic/src/main/kotlin/godtools.dynamic-feature-conventions.gradle.kts
build-logic/src/main/kotlin/godtools.library-conventions.gradle.kts
build.gradle
gradle/libs.versions.toml
library/account/config/ktlint/baseline.xml
library/base/config/ktlint/baseline.xml
ui/base/src/main/kotlin/org/cru/godtools/base/ui/compose/CompositionLocals.kt
ui/base/src/main/kotlin/org/cru/godtools/base/ui/theme/GodToolsTheme.kt

This PR adds some additional ktlint rules to look for some bad compose practices.
For now I added several of our existing violations to the ktlint baseline, but over time as we refactor logic hopefully these violations will be replaced by better practices.

Enable Jetpack Compose ktlint rules

---

app/src/main/kotlin/org/cru/godtools/ui/dashboard/tools/ToolsPresenter.kt
app/src/main/kotlin/org/cru/godtools/ui/languages/app/AppLanguagePresenter.kt
app/src/main/kotlin/org/cru/godtools/ui/tools/ToolCardPresenter.kt
app/src/testDebug/kotlin/org/cru/godtools/ui/dashboard/tools/ToolsPresenterTest.kt
library/base/src/main/kotlin/org/cru/godtools/base/Settings.kt
library/base/src/test/kotlin/org/cru/godtools/base/SettingsTest.kt
library/db/build.gradle.kts
library/db/src/main/kotlin/org/cru/godtools/db/repository/AttachmentsRepository.kt
library/db/src/main/kotlin/org/cru/godtools/db/repository/LanguagesRepository.kt
library/db/src/main/kotlin/org/cru/godtools/db/repository/TranslationsRepository.kt
library/db/src/test/kotlin/org/cru/godtools/db/repository/AttachmentsRepositoryTest.kt
library/db/src/test/kotlin/org/cru/godtools/db/repository/TranslationsRepositoryTest.kt

- **create a produceAppLocaleState Composable**
- **move rememberLanguage() composable to library:db so it can be reused**
- **extract a common rememberAttachmentFile() Composable method**
- **create a produceLatestTranslationState composable**

Extract some common compose State producers

---

app/src/main/kotlin/org/cru/godtools/ui/account/delete/DeleteAccountLayout.kt
app/src/test/snapshots/images/org.cru.godtools.ui.account.delete_DeleteAccountLayoutPaparazziTest_DeleteAccountLayout() - Deleting[Nexus 5,NIGHT,NO_ACCESSIBILITY].png
app/src/test/snapshots/images/org.cru.godtools.ui.account.delete_DeleteAccountLayoutPaparazziTest_DeleteAccountLayout() - Deleting[Nexus 5,NOTNIGHT,ACCESSIBILITY].png
app/src/test/snapshots/images/org.cru.godtools.ui.account.delete_DeleteAccountLayoutPaparazziTest_DeleteAccountLayout() - Deleting[Nexus 5,NOTNIGHT,NO_ACCESSIBILITY].png
app/src/test/snapshots/images/org.cru.godtools.ui.account.delete_DeleteAccountLayoutPaparazziTest_DeleteAccountLayout() - Deleting[Pixel 6 Pro,NIGHT,NO_ACCESSIBILITY].png
app/src/test/snapshots/images/org.cru.godtools.ui.account.delete_DeleteAccountLayoutPaparazziTest_DeleteAccountLayout() - Deleting[Pixel 6 Pro,NOTNIGHT,NO_ACCESSIBILITY].png
app/src/test/snapshots/images/org.cru.godtools.ui.account.delete_DeleteAccountLayoutPaparazziTest_DeleteAccountLayout() - Display[Nexus 5,NIGHT,NO_ACCESSIBILITY].png
app/src/test/snapshots/images/org.cru.godtools.ui.account.delete_DeleteAccountLayoutPaparazziTest_DeleteAccountLayout() - Display[Nexus 5,NOTNIGHT,ACCESSIBILITY].png
app/src/test/snapshots/images/org.cru.godtools.ui.account.delete_DeleteAccountLayoutPaparazziTest_DeleteAccountLayout() - Display[Nexus 5,NOTNIGHT,NO_ACCESSIBILITY].png
app/src/test/snapshots/images/org.cru.godtools.ui.account.delete_DeleteAccountLayoutPaparazziTest_DeleteAccountLayout() - Display[Pixel 6 Pro,NIGHT,NO_ACCESSIBILITY].png
app/src/test/snapshots/images/org.cru.godtools.ui.account.delete_DeleteAccountLayoutPaparazziTest_DeleteAccountLayout() - Display[Pixel 6 Pro,NOTNIGHT,NO_ACCESSIBILITY].png
app/src/test/snapshots/images/org.cru.godtools.ui.dashboard.tools_ToolFiltersPaparazziTest_LanguageFilter - Button - English Selected[NIGHT,ACCESSIBILITY].png
app/src/test/snapshots/images/org.cru.godtools.ui.dashboard.tools_ToolFiltersPaparazziTest_LanguageFilter - Button - No Language Selected[NIGHT,ACCESSIBILITY].png
app/src/test/snapshots/images/org.cru.godtools.ui.tools_SquareToolCardPaparazziTest_SquareToolCard() - Default[NIGHT,ACCESSIBILITY].png
app/src/test/snapshots/images/org.cru.godtools.ui.tools_SquareToolCardPaparazziTest_SquareToolCard() - Downloading[NIGHT,ACCESSIBILITY].png
app/src/test/snapshots/images/org.cru.godtools.ui.tools_SquareToolCardPaparazziTest_SquareToolCard() - Favorite Tool[NIGHT,ACCESSIBILITY].png
app/src/test/snapshots/images/org.cru.godtools.ui.tools_SquareToolCardPaparazziTest_SquareToolCard() - Show Second Language[NIGHT,ACCESSIBILITY].png
app/src/test/snapshots/images/org.cru.godtools.ui.tools_VariantToolCardPaparazziTest_VariantToolCard() - App Language Not Available[NIGHT,ACCESSIBILITY].png
app/src/test/snapshots/images/org.cru.godtools.ui.tools_VariantToolCardPaparazziTest_VariantToolCard() - Default[NIGHT,ACCESSIBILITY].png
app/src/test/snapshots/images/org.cru.godtools.ui.tools_VariantToolCardPaparazziTest_VariantToolCard() - No second Language[NIGHT,ACCESSIBILITY].png
app/src/test/snapshots/images/org.cru.godtools.ui.tools_VariantToolCardPaparazziTest_VariantToolCard() - Second Language Not Available[NIGHT,ACCESSIBILITY].png
app/src/test/snapshots/images/org.cru.godtools.ui.tools_VariantToolCardPaparazziTest_VariantToolCard() - Selected[NIGHT,ACCESSIBILITY].png
app/src/testDebug/kotlin/org/cru/godtools/ui/BasePaparazziTest.kt
app/src/testDebug/kotlin/org/cru/godtools/ui/account/delete/DeleteAccountLayoutPaparazziTest.kt

- **exclude redundant accessibility tests**
- **add paparazzi tests for the DeleteAccountLayout**

Add Paparazzi tests for DeleteAccountLayout

---

app/src/main/kotlin/org/cru/godtools/ui/languages/app/AppLanguagePresenter.kt
app/src/main/kotlin/org/cru/godtools/ui/languages/app/AppLanguageScreen.kt
app/src/test/snapshots/images/org.cru.godtools.ui.languages.app_AppLanguageLayoutPaparazziTest_AppLanguageLayout() - Searching[Nexus 5,NIGHT,NO_ACCESSIBILITY].png
app/src/test/snapshots/images/org.cru.godtools.ui.languages.app_AppLanguageLayoutPaparazziTest_AppLanguageLayout() - Searching[Nexus 5,NOTNIGHT,ACCESSIBILITY].png
app/src/test/snapshots/images/org.cru.godtools.ui.languages.app_AppLanguageLayoutPaparazziTest_AppLanguageLayout() - Searching[Nexus 5,NOTNIGHT,NO_ACCESSIBILITY].png
app/src/test/snapshots/images/org.cru.godtools.ui.languages.app_AppLanguageLayoutPaparazziTest_AppLanguageLayout() - Searching[Pixel 6 Pro,NIGHT,NO_ACCESSIBILITY].png
app/src/test/snapshots/images/org.cru.godtools.ui.languages.app_AppLanguageLayoutPaparazziTest_AppLanguageLayout() - Searching[Pixel 6 Pro,NOTNIGHT,NO_ACCESSIBILITY].png
app/src/test/snapshots/images/org.cru.godtools.ui.languages.app_AppLanguageLayoutPaparazziTest_AppLanguageLayout()[Nexus 5,NIGHT,NO_ACCESSIBILITY].png
app/src/test/snapshots/images/org.cru.godtools.ui.languages.app_AppLanguageLayoutPaparazziTest_AppLanguageLayout()[Nexus 5,NOTNIGHT,ACCESSIBILITY].png
app/src/test/snapshots/images/org.cru.godtools.ui.languages.app_AppLanguageLayoutPaparazziTest_AppLanguageLayout()[Nexus 5,NOTNIGHT,NO_ACCESSIBILITY].png
app/src/test/snapshots/images/org.cru.godtools.ui.languages.app_AppLanguageLayoutPaparazziTest_AppLanguageLayout()[Pixel 6 Pro,NIGHT,NO_ACCESSIBILITY].png
app/src/test/snapshots/images/org.cru.godtools.ui.languages.app_AppLanguageLayoutPaparazziTest_AppLanguageLayout()[Pixel 6 Pro,NOTNIGHT,NO_ACCESSIBILITY].png
app/src/testDebug/kotlin/org/cru/godtools/ui/languages/app/AppLanguageLayoutPaparazziTest.kt
app/src/testDebug/kotlin/org/cru/godtools/ui/languages/app/AppLanguageLayoutTest.kt

- **use an ImmutableList for the list of languages on the App Language UI**
- **add paparazzi tests for AppLanguageLayout**

Add Paparazzi tests for AppLanguageLayout

---

library/base/src/main/kotlin/org/cru/godtools/base/util/Locale.kt
library/base/src/main/res/values/strings_language_names.xml
library/base/src/test/kotlin/org/cru/godtools/base/util/LocaleUtilsGetDisplayNameTest.kt

- **add interface string for Sidama language name**
- **add Taglish language name interface string**

GT-2299 Add Sidama and Taglish language name overrides

---

app/src/main/kotlin/org/cru/godtools/ui/languages/LanguageSettingsPresenter.kt
app/src/main/kotlin/org/cru/godtools/ui/languages/app/AppLanguagePresenter.kt
app/src/main/kotlin/org/cru/godtools/ui/tooldetails/ToolDetailsPresenter.kt
app/src/main/kotlin/org/cru/godtools/ui/tools/ToolCardPresenter.kt
app/src/testDebug/kotlin/org/cru/godtools/ui/languages/LanguageSettingsPresenterTest.kt
app/src/testDebug/kotlin/org/cru/godtools/ui/languages/app/AppLanguagePresenterTest.kt
app/src/testDebug/kotlin/org/cru/godtools/ui/tooldetails/ToolDetailsPresenterTest.kt
app/src/testDebug/kotlin/org/cru/godtools/ui/tools/ToolCardPresenterTest.kt
library/base/src/main/kotlin/org/cru/godtools/base/Settings.kt
library/base/src/test/kotlin/org/cru/godtools/base/SettingsTest.kt
library/download-manager/src/test/kotlin/org/cru/godtools/downloadmanager/GodToolsDownloadManagerDispatcherTest.kt

- **convert Settings.appLanguageFlow to a StateFlow**
- **make produceAppLanguageState() an actual method on the Settings object**

improve Settings app locale APIs

---

app/src/main/kotlin/org/cru/godtools/ui/account/activity/AccountActivityBadges.kt
app/src/test/snapshots/images/org.cru.godtools.ui.account.activity_AccountActivityBadgesPaparazziTest_AccountActivityBadges() - All Complete[NIGHT].png
app/src/test/snapshots/images/org.cru.godtools.ui.account.activity_AccountActivityBadgesPaparazziTest_AccountActivityBadges() - All Complete[NOTNIGHT].png
app/src/test/snapshots/images/org.cru.godtools.ui.account.activity_AccountActivityBadgesPaparazziTest_AccountActivityBadges() - All Incomplete[NIGHT].png
app/src/test/snapshots/images/org.cru.godtools.ui.account.activity_AccountActivityBadgesPaparazziTest_AccountActivityBadges() - All Incomplete[NOTNIGHT].png
app/src/test/snapshots/images/org.cru.godtools.ui.account.activity_AccountActivityBadgesPaparazziTest_AccountActivityBadges() - Some Complete[NIGHT].png
app/src/test/snapshots/images/org.cru.godtools.ui.account.activity_AccountActivityBadgesPaparazziTest_AccountActivityBadges() - Some Complete[NOTNIGHT].png
app/src/testDebug/kotlin/org/cru/godtools/ui/account/activity/AccountActivityBadgesPaparazziTest.kt

- **add paparazzi tests for activity badges**
- **use the official minLines property**

Add AccountActivityBadges Paparazzi tests

---

app/src/main/kotlin/org/cru/godtools/ui/tools/ToolCardPresenter.kt
app/src/testDebug/kotlin/org/cru/godtools/ui/tools/ToolCardPresenterTest.kt

- **add a unit test for ToolCard.State.isLoaded**
- **create an isLoaded mutable state to track when the initial translation is loaded**
- **update ToolCardPresenter to more directly use coroutines flows to load the translation**

Update ToolCardPresenter logic

---

library/db/src/main/kotlin/org/cru/godtools/db/room/repository/TranslationsRoomRepository.kt
library/db/src/test/kotlin/org/cru/godtools/db/repository/TranslationsRepositoryIT.kt
library/initial-content/src/main/kotlin/org/cru/godtools/init/content/InitialContentImporter.kt
library/initial-content/src/main/kotlin/org/cru/godtools/init/content/task/Tasks.kt
library/initial-content/src/test/kotlin/org/cru/godtools/init/content/InitialContentImporterTest.kt

- **update storeInitialTranslations to filter translations with missing tools or languages**
- **rework the InitialContentImporter to not load bundled translations until tools and languages are loaded**

GT-2370 Fix race conditions and a FK constraint issue for importing initial content

---

build-logic/src/main/kotlin/AndroidConfiguration.kt
gradle/libs.versions.toml
ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/BaseToolRendererModule.kt

- **upgrade to robolectric 4.14-beta-1**
- **bump the Android SDK to 35**

Upgrade to Android 35

---

app/google-services.json
app/src/main/kotlin/org/cru/godtools/ui/account/AccountLayout.kt
app/src/main/kotlin/org/cru/godtools/ui/account/AccountViewModel.kt
app/src/main/kotlin/org/cru/godtools/ui/dashboard/home/HomePresenter.kt
app/src/test/kotlin/org/cru/godtools/MockBaseModule.kt
app/src/testDebug/kotlin/org/cru/godtools/ui/dashboard/home/HomePresenterTest.kt
gradle/libs.versions.toml
library/base/build.gradle.kts
library/base/src/main/kotlin/org/cru/godtools/base/BaseModule.kt
library/base/src/main/kotlin/org/cru/godtools/base/Config.kt

Adds a Firebase Remote Config option to enable/disable global activity

GT-2494 Support disabling global activity via Remote Config

---

app/src/test/kotlin/org/cru/godtools/MockBaseModule.kt
library/base/build.gradle.kts
library/base/src/main/kotlin/org/cru/godtools/base/Config.kt
ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/BaseToolRendererModule.kt
ui/cyoa-renderer/src/main/kotlin/org/cru/godtools/tool/cyoa/ui/CyoaActivity.kt
ui/cyoa-renderer/src/main/kotlin/org/cru/godtools/tool/cyoa/ui/CyoaCardCollectionPageFragment.kt
ui/cyoa-renderer/src/main/kotlin/org/cru/godtools/tool/cyoa/ui/CyoaContentPageFragment.kt
ui/cyoa-renderer/src/main/kotlin/org/cru/godtools/tool/cyoa/ui/CyoaPageCollectionPageFragment.kt
ui/cyoa-renderer/src/main/kotlin/org/cru/godtools/tool/cyoa/ui/CyoaPageFragment.kt
ui/cyoa-renderer/src/main/kotlin/org/cru/godtools/tool/cyoa/ui/PageInsets.kt
ui/cyoa-renderer/src/main/kotlin/org/cru/godtools/tool/cyoa/ui/controller/CardCollectionPageController.kt
ui/cyoa-renderer/src/main/kotlin/org/cru/godtools/tool/cyoa/ui/controller/ContentPageController.kt
ui/cyoa-renderer/src/main/kotlin/org/cru/godtools/tool/cyoa/ui/controller/PageCollectionPageController.kt
ui/cyoa-renderer/src/main/res/layout/cyoa_page_card_collection.xml
ui/cyoa-renderer/src/main/res/layout/cyoa_page_content.xml
ui/cyoa-renderer/src/main/res/layout/cyoa_page_page_collection.xml
ui/cyoa-renderer/src/test/kotlin/org/cru/godtools/tool/cyoa/ui/CyoaActivityTest.kt

GT-2451 Add Support for Page Collection Pages in CYOA tools

---

.github/workflows/build.yml
app/build.gradle.kts
app/google-services.json
build-logic/src/main/kotlin/AndroidConfiguration.kt

- **update the application id and version name for stage builds**
- **update the qa_build job to deploy a stage & production QA build**

GT-2540 Enable a Stage QA build

---

.github/workflows/build.yml
app/build.gradle.kts

- **use artifactType instead of a raw path to the apk**
- **temporarily enable QA builds for pull requests**

GT-2540 Fix QA builds of multiple build variants

---

app/src/main/kotlin/org/cru/godtools/ui/dashboard/optinnotification/OptInNotificationModalOverlay.kt

Quick fix for layout issues raised here:
https://deepspacerobots.slack.com/archives/C08D70VG98S/p1747086736622299
P.S. -- I thought the feature branch had already been merged in, so I updated with the latest from develop.  Let me know if you would like me to revert that merge

Added .navigationBarsPadding modifier to respect safe area
