CruGlobal/godtools-android

- build.gradle
This reverts commit 2bb52f8087ba3ddd475d6d39e0d3942b19926f39.
alpha 6 of the android build plugin introduced a crash on ICS.
> Revert "upgrade to latest plugin version"

- build.gradle
- library/tract-renderer/src/main/res/layout/tract_content_image.xml
Depends on https://github.com/CruGlobal/android-gto-support/pull/167
we have no need of the `TractPicassoImageView` specific behavior, but we do need the underlying `SimplePicassoImageView` behavior.
> Fix <content:image> rendering

- app/src/main/java/org/keynote/godtools/android/activity/TourActivity.java
- app/src/main/res/layout/fragment_tour_languages.xml
The "Now" button which took the user to the pick languages activity proved frustrating/distracting for users. Now just one "Okay" button.
> Remove "now" & "later" buttons in favor of one "Okay" button during onboarding tour

- library/tract-renderer/src/main/AndroidManifest.xml
https://www.knowgod.com/.well-known/assetlinks.json issues a 301 redirect. This is invalid according to the verification file requirements listed here: https://developer.android.com/training/app-links/verify-site-associations.html#publish-json
> disable www.knowgod.com deep links to fix app link behavior

- app/src/main/java/org/cru/godtools/adapter/LanguagesAdapter.java
Use the `else` as a fallback in case mCallbacks is null for some reason. At least the language will be downloaded, but the activity just won't pop.
(maybe the null check isn't needed, but it's done elsewhere, so I did it here)
> Pop back to previous activity after downloading language

- build.gradle
- library/tract-renderer/build.gradle
- library/tract-renderer/src/main/java/org/cru/godtools/tract/Constants.java
- library/tract-renderer/src/main/java/org/cru/godtools/tract/activity/TractActivity.java
- library/tract-renderer/src/main/java/org/cru/godtools/tract/model/Manifest.java
- library/tract-renderer/src/test/java/org/cru/godtools/tract/activity/TractActivityUpdateHiddenLanguagesTest.java
Within the Android TractActivity we already store an array of languages we are attempting to show. This PR leverages this arbitrary list of languages to display to implement the primary language fallback functionality.
1. We parse a list of primary language candidates (with fallbacks) from the deep link
2. We trigger a background download for all of these potential languages
3. We pick which of the primary language options we actually make visible in the UI via `updateHiddenLanguages()`
- If one of the potential primary languages is currently active we use that as the primary language. (This prevents unexpected state changes in the UI for the end user)
- Otherwise the first potential primary language that we haven't determined to be missing is used.
- This state is refreshed every time we …
> Deep Link updates for JF

- app/src/main/AndroidManifest.xml
The legacy location permission we are maintaining adds a location hardware requirement that we don't want to actually enforce
> Don't require location hardware

- library/tract-renderer/src/main/AndroidManifest.xml
https://fabric.io/cru/android/apps/org.keynote.godtools.android/issues/5af9be3a11e9fa0aa58b13fa
> don't restrict Modal orientation to prevent crash on 8.0.0

- ui/tract-renderer/src/main/java/org/cru/godtools/tract/activity/TractActivity.java
This will fix the initial page for tracts when using an RTL device language
> set initial page for tract to 0

- ui/tract-renderer/src/main/java/org/cru/godtools/tract/model/Base.java
we can't assume that onBind() will evaluate the same way because the base object didn't change. Also, this fixes an initialization bug where we bind `null` to the view holder before anything else is bound.
> always call `onBind()`

- library/analytics/src/main/java/org/cru/godtools/analytics/model/AnalyticsScreenEvent.java
The screen_view portion of the URI was being used as the host, in which underscore is an invalid character. This led to the data not getting through to Redshift. This should fix any data we are sending going forward. The other data will need to be fixed using SQL.
Replaces #439
> Fix Snowplow Screen View URIs

- library/analytics/src/main/java/org/cru/godtools/analytics/model/AnalyticsActionEvent.java
- library/analytics/src/main/java/org/cru/godtools/analytics/model/AnalyticsScreenEvent.java
This PR fixes an issue where we were sending URIs like `godtools:/screenview/...` to snowplow instead of `godtools://screenview/...`.
> Fix Snowplow URIs

- analysis/checkstyle/checkstyle.xml
- app/src/main/java/org/cru/godtools/adapter/ToolsAdapter.java
- library/analytics/src/debug/java/org/cru/godtools/analytics/TimberAnalyticsService.java
- library/analytics/src/main/java/org/cru/godtools/analytics/AdobeAnalyticsService.java
- library/analytics/src/main/java/org/cru/godtools/analytics/AnalyticsDispatcher.java
- library/analytics/src/main/java/org/cru/godtools/analytics/GoogleAnalyticsService.java
- library/analytics/src/main/java/org/cru/godtools/analytics/SnowplowAnalyticsService.java
- library/api/src/main/java/org/cru/godtools/api/GodToolsApi.java
- library/base/src/main/java/org/cru/godtools/base/Settings.java
- library/db/src/main/java/org/keynote/godtools/android/db/GodToolsDao.java
- library/db/src/main/java/org/keynote/godtools/android/db/GodToolsDatabase.java
- library/download-manager/src/main/java/org/cru/godtools/download/manager/GodToolsDownloadManager.java
- library/xml-model/src/androidTest/java/org/cru/godtools/xml/model/UtilsIT.java
- library/xml-model/src/main/java/org/cru/godtools/xml/service/ManifestManager.java
- ui/articles-aem-renderer/src/androidTest/java/org/cru/godtools/articles/aem/db/ArticleRoomDatabaseTest.java
- ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/db/ArticleDao.java
- ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/db/ArticleRepository.java
- ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/db/ArticleRoomDatabase.java
- ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/db/AttachmentRepository.java
- ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/db/ManifestAssociationDao.java
- ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/view_model/ArticleViewModel.java
- ui/base/src/main/java/org/cru/godtools/base/ui/util/LocaleTypefaceUtils.java
- ui/shortcuts/src/main/java/org/cru/godtools/shortcuts/GodToolsShortcutManager.java
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/service/FollowupService.java
This updates the checkstyle rules to enforce an `EmptyLineSeparator` policy.
The rationale behind the rule is to make whitespace more consistent across our code base. Extra whitespace lines may provide benefit while you are working on a feature to keep your modified code separate from existing code, but once you merge that code I feel it reduces readability and utilizing regions is a better mechanism for grouping related functionality together.
In addition, constant thrashing in number of empty lines between logic messes with git history, which has an impact on merging diverging branches back together.
> Checkstyle updates

- build.gradle
- ui/articles-aem-renderer/build.gradle
This PR configures multidex for debug builds only.
We were already utilizing Multi-Dex with debug app builds, and androidTest runs against debug builds only. So, we leverage these facts to enable multidex for all library androidTest builds and not enable multidex for release builds
> Multidex debug builds only

- build.gradle
- gradle.properties
- multidex-keep.pro
This is accomplished by including any class containing junit test related annotations in the main dex file
> fix androidTest issue on older versions of android

- app/src/main/res/values-sq/strings.xml
Fixes https://fabric.io/cru/android/apps/org.keynote.godtools.android/issues/5b5db3046007d59fcd220c28?time=last-ninety-days
> fix a number format for the Albanian translation

- library/xml-model/src/main/java/org/cru/godtools/xml/model/Category.java
- ui/article-renderer/build.gradle
- ui/article-renderer/src/main/java/org/cru/godtools/article/fragment/ArticlesFragment.java
- ui/articles-aem-renderer/room-schemas/org.cru.godtools.articles.aem.db.ArticleRoomDatabase/7.json
- ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/db/AemImportRepository.kt
- ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/db/ArticleDao.kt
- ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/db/ArticleRoomDatabase.java
- ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/model/Article.java
- ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/service/support/AemJsonParser.java
- Parse AEM tags for a category from the manifest xml
- Track all tags for an article in the AEM article cache database
- Load articles based on the AEM tags in a specific category
> AEM tags support

- ui/articles-aem-renderer/src/androidTest/assets/tests/article-test.json
- ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/service/support/AemJsonParser.java
long term we might shift definition of which template to use into the manifest xml, but for now we are just hardcoding it in the parser
> update AEM JSON parser to look for articles using the production cru template

- ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/db/AemImportDao.kt
- ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/db/AemImportRepository.kt
- ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/db/ArticleDao.kt
- ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/db/ArticleRepository.kt
- ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/db/ResourceDao.kt
- ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/db/TranslationRepository.kt
- ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/fragment/AemArticleFragment.java
- ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/model/Constants.kt
- ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/model/Resource.kt
- ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/service/AEMDownloadManger.java
- Prunes any orphaned database objects that are no longer referenced (aem imports, articles, resources)
- has a low priority cleaner process that remove any cached files that are not referenced in the resources table
> Prune orphaned records

- analysis/checkstyle/checkstyle.xml
- library/api/src/main/java/org/cru/godtools/api/model/ToolViews.java
The desire behind a fixed import order is to prevent churn within git history.
We can adjust what import order we are enforcing as needs change
> Checkstyle import order

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/cru/godtools/activity/AboutActivity.java
- app/src/main/java/org/cru/godtools/activity/LanguageSelectionActivity.java
- app/src/main/java/org/cru/godtools/activity/LanguageSettingsActivity.java
- app/src/main/java/org/cru/godtools/activity/ToolDetailsActivity.java
- ui/article-renderer/src/main/java/org/cru/godtools/article/activity/ArticlesActivity.java
- ui/article-renderer/src/main/java/org/cru/godtools/article/activity/CategoriesActivity.java
- ui/articles-aem-renderer/src/main/java/org/cru/godtools/articles/aem/activity/AemArticleActivity.kt
- ui/base-tool/src/main/java/org/cru/godtools/base/tool/activity/BaseSingleToolActivity.java
- ui/base/src/main/java/org/cru/godtools/base/ui/activity/BaseActivity.java
This PR reworks some of the Activity navigation logic.
- Track the launching activity so that up navigation can be short-circuited to back navigation when possible
- utilize REORDER_TO_FRONT flag to handle navigating back and forth between about and language settings activities
- pass along any common extras an activity knows about when processing up navigation
> Rework activity navigation

- ui/tract-renderer/src/main/AndroidManifest.xml
this crash: https://fabric.io/cru/android/apps/org.keynote.godtools.android/issues/5be6cfe6f8b88c29635700f5?time=last-ninety-days
I had fixed this in the past, but I re-introduced the bug when I adjusted orientations for all activities.
> we can't specify an orientation for a transparent activity

- app/proguard-appsee.pro
- app/src/debug/java/org/cru/godtools/DebugGodToolsApplication.kt
- app/src/main/java/org/cru/godtools/service/AppseeAnalyticService.kt
- ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/activity/AemArticleActivity.kt
- ui/base/src/main/java/org/cru/godtools/base/ui/activity/BaseActivity.java
- Enable Appsee debug logging for debug builds
- pause recording when AemArticleActivity or LoginDialogFragment are active
- trimmed down the proguard rules
> Appsee tweaks

- app/src/main/java/org/cru/godtools/fragment/LanguagesFragment.java
The sync process will eventually resolve this inconsistent data, for now let's just present the language once
Fixes: https://console.firebase.google.com/u/0/project/godtools-b2f82/crashlytics/app/android:org.keynote.godtools.android/issues/5c031232f8b88c29632fa55a
> Don't crash on a duplicate language in the language table

- library/analytics/src/main/AndroidManifest.xml
We have another permission related to performance monitoring that is required, so we are biting the bullet with this upgrade and prompting for all deferred permissions with this single upgrade.
> remove our block on new permissions for older versions of Android

- library/analytics/src/main/java/org/cru/godtools/analytics/AdobeAnalyticsService.java
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/analytics/model/ToggleLanguageAnalyticsActionEvent.java
It appears that Adobe Analytics drops fields that don't have values
> GT-573 send a value with the analytics event

- app/src/main/java/org/cru/godtools/service/AppseeAnalyticService.kt
The `K$c` screen being recorded was the automatic screen name for activities when they started. using the official Appsee proguard rules did fix the name, but it was still events that we did not want to track.
`onAppseeScreenDetected` is triggered only for automatic screen detection, and setting the screenName to null will skip tracking that screen event which is the desired behavior.
see: https://support.appsee.com/customer/en/portal/articles/2686094-how-can-i-join-rename-or-ignore-specific-screens-
> Disable automatic screen detection in Appsee

- ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/fragment/AemArticleFragment.java
on Android Q there is a request for a `data:` uri that was causing it to display a not found UI for any article that was being loaded. Since `data:` URIs are completely self-contained we don't need to override processing.
> don't intercept requests for data URIs

- ui/tract-renderer/src/main/java/org/cru/godtools/tract/viewmodel/InputViewHolder.java
https://jira.cru.org/browse/GT-639
On the prayer screen of the 4SL, KGP and THE FOUR, when a user goes to sign up for follow up, it's hard to figure out how to dismiss the keyboard. And it's hard to access the SEND option. If I choose No Thanks, it's really hard to figure out how to dismiss the keyboard - I never could figure out how to do it.
> GT-639 : Keyboard Not Dismissing appropriately

- ui/tract-renderer/src/main/java/org/cru/godtools/tract/viewmodel/CardViewHolder.java
- ui/tract-renderer/src/main/res/layout/tract_content_card.xml
https://jira.cru.org/browse/GT-601
Two issues: 
1. Can you increase the buffer space between the footer of the card and the text on the card? The words Previous and Next are sometimes too close to the text on the card and I think it might be confusing. Is this easy to do?
2. Is there any way on the prayer screens to say 1/2 cards? Right now, it only shows that there is one card on that screen and I think a lot of people will miss the prayer screen sign up for follow up
> GT-601 : Requested Changes from QA

- ui/tract-renderer/src/main/java/org/cru/godtools/tract/widget/PageContentLayout.java
Previously in immersive mode if the user swiped from the bottom of the screen to reveal the phone UI it would also trigger a fling of the tract page content.
This PR prevents that fling from triggering by establishing a "gutter" at the bottom of the screen that is ignored for fling operations.
> GT-722 Prevent flings in Tracts when initiated at the very bottom of the screen

- app/src/main/res/layout/tool_details_fragment.xml
previously on really tall screens (e.g. tablets) the gray color would stop after the view pager content and you would end up with a white background below the view pager. This addresses the issue by making the base background gray.
There still exists an issue where you can not swipe between pages from below the ViewPager content.
I tried addressing this by getting the ViewPager to fill the remaining space. this fixed the background color, but didn't solve the swiping issue because of how the ViewPager wraps an inner RecyclerView.
I opted to go with changing the background on the LinearLayout because the other solution didn't gain us anything and adds additional layout overhead of wrapping content or growing the content to fill the LinearLayout
> make sure the gray background fills any empty space at the bottom

- app/src/main/java/org/cru/godtools/activity/BasePlatformActivity.kt
- app/src/main/java/org/cru/godtools/fragment/BasePlatformFragment.kt
- app/src/main/java/org/cru/godtools/fragment/ToolsFragment.java
- app/src/main/java/org/cru/godtools/ui/languages/LanguagesFragment.kt
- app/src/main/java/org/cru/godtools/ui/profile/GlobalActivityFragment.kt
- app/src/main/java/org/cru/godtools/ui/profile/ProfileActivity.kt
- app/src/main/java/org/keynote/godtools/android/activity/MainActivity.java
- app/src/main/res/layout/profile_activity.xml
This PR refactors the sync framework for activities and fragments to allow them to work together and share a common SwipeRefreshLayout. We then utilize this logic to have a SwipeRefreshLayout on the ProfileActivity that triggers the sync in the GlobalActivityFragment
> GT-765 Add SwipeRefreshLayout to Profile

- library/download-manager/src/main/java/org/cru/godtools/download/manager/GodToolsDownloadManager.java
The actual disk space usage for GodTools data is very minimal, so removing translations isn't really necessary at this time.
We still remove translations if a newer version of the translation has been downloaded
> GT-793 don't remove translations that aren't favorited

- ui/article-aem-renderer/src/main/AndroidManifest.xml
this is a minor QOL improvement that will allow users to use landscape mode when reading an article if they desire
> always allow "user" screenOrientation for AEM articles

- ui/article-aem-renderer/build.gradle
- ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/ui/AemArticleActivity.kt
- ui/base-tool/src/main/java/org/cru/godtools/base/tool/activity/BaseSingleToolActivity.kt
- ui/base-tool/src/main/java/org/cru/godtools/base/tool/activity/BaseToolActivity.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/activity/TractActivity.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/activity/TractActivityDataModel.kt
- ui/tract-renderer/src/test/java/org/cru/godtools/tract/activity/TractActivityDataModelTest.kt
- ui/tract-renderer/src/test/java/org/cru/godtools/tract/activity/TractActivityTest.kt
This shifts some logic around the active tool and tool state to utilize LiveData for the observer pattern instead of having to manually trigger re-evaluation whenever the underlying data changes.
> GT-808 utilize LiveData for activeManifest and activeToolState

- ui/tract-renderer/src/main/java/org/cru/godtools/tract/activity/TractActivity.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/adapter/ManifestPagerAdapter.java
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/viewmodel/PageViewHolder.java
When the language toggle was used navigation events were only being triggered if no card was active, but not when a card was active.
The trigger if no card was present was actually a bug in when we triggered `onActiveCardChanged`, it would incorrectly be triggered when no card was selected and we re-bound the cards to the layout.
Once this was fixed, I added an explicit trigger for analytics and navigation events when the language was toggled.
> GT-849 Fix toggling language not consistently triggering analytics and navigation events

- library/xml-model/src/main/java/org/cru/godtools/xml/model/Base.kt
- library/xml-model/src/main/java/org/cru/godtools/xml/model/Button.kt
- library/xml-model/src/main/java/org/cru/godtools/xml/model/Content.kt
- library/xml-model/src/main/java/org/cru/godtools/xml/model/Text.kt
- library/xml-model/src/test/java/org/cru/godtools/xml/model/ButtonTest.kt
somehow the textColor -> primaryTextColor function was deleted when converting this logic to Kotlin. now there is a test in place to guarantee this behavior
> fix button color behavior

- build.gradle
This change is being made because Android 17 and 18 don't support auto-mirroring for images when
viewed in a RTL language. This causes the dynamic call to action arrow image to not correctly
display in RTL languages. The effort required to work around this issue isn't worth the percentage
of users this affects going forward.
This change will drop support for 0.4% of our current users. These users will continue to be able to
install and use the current version of GodTools, they just won't be able to get any new updates.
> Increase the minimum version of Android required

- ui/base-tool/src/main/java/org/cru/godtools/base/tool/activity/ImmersiveActivity.kt
the share submenu can be rendered behind the top cutout, for now we just disable immersive mode when there is a display cutout to avoid this behavior.
> disable immersive mode when there are display cutouts

- ui/base/build.gradle
- ui/base/src/main/java/org/cru/godtools/base/ui/fragment/DialogFragment.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/activity/TractActivity.kt
This dialog could be triggered from onActivityResult which is after onInstanceSaveState(), but is meant as a transient dialog so we don't really need to track it's state
> GT-925 utilize showAllowingStateLoss when displaying the Live Share connecting dialog

- ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/ui/AemArticleActivity.kt
- ui/base-tool/src/main/java/org/cru/godtools/base/tool/activity/BaseToolActivity.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/activity/TractActivity.kt
Don't show the share menu icon when the user is in training mode
> GT-928 Tips share menu item

- app/src/main/AndroidManifest.xml
This makes the entire app an Instant App. This is a functional first step, over time we may want to move some functionality out into other dynamic features. The 2 that immediately come to mind are: move tutorial content to its own feature, and move the tract logic into its own feature.
the tutorial dynamic feature would reduce instant app size by probably 30-40% due to all the large images in the tutorial. the tract dynamic feature wouldn't have a functional benefit at this time, but could long term if we start making other parts of the app instant-app capable
> GT-908 enable instant app functionality for the core app

- ui/tract-renderer/src/main/java/org/cru/godtools/tract/adapter/ManifestPagerAdapter.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/BaseController.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/HeroController.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/PageController.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/widget/PageContentLayout.java
- ui/tract-renderer/src/main/res/layout/tract_page.xml
- ui/tract-renderer/src/test/java/org/cru/godtools/tract/ExternalSingletonsModule.kt
- ui/tract-renderer/src/test/java/org/cru/godtools/tract/ui/controller/PageControllerTest.kt
Eventually I want to switch the manual management of an isVisible flag to utilizing `LifecycleOwners`
> GT-964 expose a LifecycleOwner within the tract tool renderer

- ui/shortcuts/src/main/java/org/cru/godtools/shortcuts/GodToolsShortcutManager.kt
- ui/shortcuts/src/test/java/org/cru/godtools/shortcuts/GodToolsShortcutManagerTest.kt
On older versions of android there was a non-fatal exception thrown anytime the shortcut manager would have ran because the `updateShortcutActor` would finish processing and shutdown on launch.
> GT-986 the updateShortcutActor should always accept requests

- library/db/build.gradle
- library/db/src/main/java/org/keynote/godtools/android/db/GodToolsDao.kt
- ui/base-tool/src/main/java/org/cru/godtools/base/tool/activity/BaseToolActivity.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/tips/TipBottomSheetDialogFragment.kt
`AsyncDao` utilizes Google Gauva and Futures. Modern android development relies on coroutines to asynchronously execute logic.
This PR removes `AsyncDao` in favor of coroutine alternatives
> Remove AsyncDao

- ui/tract-renderer/src/main/java/org/cru/godtools/tract/activity/LanguageToggleController.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/activity/TractActivity.kt
- ui/tract-renderer/src/test/java/org/cru/godtools/tract/activity/LanguageToggleControllerTest.kt
This fixes misfires of the toggle language analytics event. the event should only fire when the ToggleController isn't updating the visible language tabs.
> GT-998 Toggle language analytics event

- app/build.gradle
- app/src/main/java/org/cru/godtools/activity/BasePlatformActivity.kt
Since Okta self-service registration is still not enabled we are going with the temporary solution of using the key account creation form to create a user account, and then the user will have to know to use login after creating the account to continue.
> launch the key signup page instead of Okta

- ui/shortcuts/build.gradle
- ui/shortcuts/src/main/java/org/cru/godtools/shortcuts/GodToolsShortcutManager.kt
- ui/shortcuts/src/test/java/org/cru/godtools/shortcuts/GodToolsShortcutManagerTest.kt
This prevents the updateDynamicShortcuts try-catch from intercepting the `CancellationException` that could be thrown if the coroutine is cancelled while processing
> GT-1002 Shortcuts crash

- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/BaseController.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/tips/TipPageController.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/tips/TipBottomSheetDialogFragment.kt
- ui/tract-renderer/src/main/res/layout/tract_content_video.xml
There was a memory leak when leaving a youtube video in a tip. This registers the YoutubePlayerView with the LIfecycleOwner so that the youtube player can cleanup after itself once the lifecycle is destroyed
> GT-1001 Fix Youtube player memory leak

- .travis.yml
robolectric downloads the various android SDKs to the local maven repo
> include the maven directory in the travis cache

- ui/tract-renderer/src/main/java/org/cru/godtools/tract/dagger/ContentKey.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/dagger/UiControllerModule.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/AnimationController.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/BaseController.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/ButtonController.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/CardController.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/FallbackController.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/FormController.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/HeroController.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/ImageController.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/InputController.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/LinkController.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/ModalController.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/PageController.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/ParagraphController.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/ParentController.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/TabController.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/TabsController.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/TextController.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/UiControllerCache.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/VideoController.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/tips/InlineTipController.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/tips/TipPageController.kt
- ui/tract-renderer/src/main/res/layout/tract_content_tab.xml
- ui/tract-renderer/src/main/res/layout/tract_page_hero.xml
- ui/tract-renderer/src/test/java/org/cru/godtools/tract/ui/controller/HeroControllerTest.kt
- ui/tract-renderer/src/test/java/org/cru/godtools/tract/ui/controller/PageControllerTest.kt
- ui/tract-renderer/src/test/java/org/cru/godtools/tract/ui/controller/ParentControllerTest.kt
This updates all the tool UI controllers to utilize Dagger for creation. The long term goal of this is to allow the controllers to be split between the various renderer modules based on where they are actually used
> GT-1043 Update tool UI controllers to be created via Dagger

- build.gradle
- ui/base-tool/build.gradle
- ui/base-tool/src/main/java/org/cru/godtools/base/tool/ui/controller/BaseController.kt
- ui/base-tool/src/main/java/org/cru/godtools/base/tool/ui/controller/ParentController.kt
- ui/base-tool/src/main/java/org/cru/godtools/base/tool/ui/controller/cache/UiControllerCache.kt
- ui/base-tool/src/main/java/org/cru/godtools/base/tool/ui/controller/cache/UiControllerModule.kt
- ui/base-tool/src/main/java/org/cru/godtools/base/tool/ui/controller/cache/UiControllerType.kt
- ui/base-tool/src/main/java/org/cru/godtools/base/tool/ui/controller/cache/VariationResolver.kt
- ui/base-tool/src/test/java/org/cru/godtools/base/tool/ui/controller/ParentControllerTest.kt
- ui/base-tool/src/test/java/org/cru/godtools/base/tool/ui/controller/cache/UiControllerCacheTest.kt
- ui/base-tool/src/test/java/org/cru/godtools/base/tool/ui/controller/cache/UiControllerTypeTest.kt
When rendering an outlined button it has different base styles automatically applied to it. This means it is hard to switch a button view between normal and outlined mode. To accommodate for this difference we will have 2 different `ButtonControllers`, one for normal buttons and one for outlined buttons.
This PR introduces the framework to define a `VariationResolver` that will allow us to define the 2 button variations we support.
Long term this can also be used if we need to support a different video platform via the `video` element
> GT-1055 Allow the same type of model to have UI controller variations

- app/build.gradle
android app bundles allows the play store to install only the resources that a user's device needs. This is normally a good thing.
but in GodTools we occasionally use a language that isn't the device language, this means it needs access to language resources that might not be installed. The `language.enableSplits` setting should force the play store to always install all the languages.
I believe this will fix the split language issue, but I won't know for sure until we get this change into a version uploaded to the play store.
> GT-1062 don't perform language splits, just install all languages

- ui/shortcuts/src/main/java/org/cru/godtools/shortcuts/GodToolsShortcutManager.kt
- ui/shortcuts/src/test/java/org/cru/godtools/shortcuts/GodToolsShortcutManagerTest.kt
Instant Apps don't have access to the ShortcutManager system service. This led to a crash where updating dynamic shortcuts would utilize `ShortcutManagerCompat` which assumes the `ShortcutManager` is available on newer versions of Android. This led to an NPE.
we now only attempt to update dynamic shortcuts if we have an actual `ShortcutManager`
> GT-1044 Fix ShortcutManager crash on Instant App

- ui/base-tool/src/main/java/org/cru/godtools/base/tool/model/view/ManifestViewUtils.kt
- ui/base-tool/src/main/java/org/cru/godtools/base/tool/model/view/ResourceViewUtils.kt
- ui/base-tool/src/main/java/org/cru/godtools/base/tool/widget/ScaledPicassoImageView.kt
- ui/base-tool/src/main/java/org/cru/godtools/base/tool/widget/SimpleScaledPicassoImageView.kt
- ui/base-tool/src/test/java/org/cru/godtools/base/tool/widget/ScaledPicassoImageViewTest.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/activity/TractActivity.kt
- ui/tract-renderer/src/main/res/layout/tract_activity.xml
- ui/tract-renderer/src/main/res/layout/tract_content_card.xml
- ui/tract-renderer/src/main/res/layout/tract_page.xml
- ui/tract-renderer/src/test/java/org/cru/godtools/tract/databinding/TractActivityBindingTest.kt
utilize a matrix scale type to position/scale background images for tools, pages, and cards.
I'm not totally happy with how I had to write tests, but I'm not sure of a better way to programmatically test how an ImageView renders a drawable without needing to run an emulator.
Instead I'm testing to make sure that the Matrix transform is generated in an expected manner based upon the drawable and image size
> GT-1048 GT-1060 Card background images

- ui/tutorial-renderer/src/main/java/org/cru/godtools/tutorial/PageSet.kt
@frett This seemed pretty straightforward and worked when I tested locally. The ticket says the files are on OneSky but they appeared to be in the ```res``` folder under ```values-hi```. Not sure if there is anything else I need to add so just let me know!
> GT-1072-Add-Hindi-To-Onboarding

- ui/base-tool/src/main/java/org/cru/godtools/base/tool/ui/controller/BaseController.kt
- ui/base-tool/src/main/java/org/cru/godtools/base/tool/ui/controller/ButtonController.kt
- ui/base-tool/src/main/java/org/cru/godtools/base/tool/ui/controller/ParentController.kt
- ui/lesson-renderer/src/main/java/org/cru/godtools/tool/lesson/ui/controller/LessonPageController.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/ModalController.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/PageController.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/tips/InlineTipController.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/tips/TipPageController.kt
Buttons inside lessons didn't have access to EventBus to trigger the appropriate EventBus events.
Long term I'm moving towards Dagger directly injecting controller dependencies where they are used instead of relying on them being in the base controller for the current hierarchy.
> GT-1083 Fix buttons using EventBus in lessons

- app/build.gradle
- app/src/main/res/layout/activity_dashboard.xml
- app/src/main/res/layout/activity_generic_fragment_with_nav_drawer.xml
> GT-1108 use HackyDrawerLayout to workaround a framework crash relating to MotionEvents

- build.gradle
firebase in-app messaging has a transitive dependency on an older version of grpc. On Android 11 some of the internal android APIs grpc accesses are no longer available. newer versions of grpc fix this by utilizing new public APIs, but FIAM has not been updated to use the newer version of grpc yet.
> GT-1122 force an upgrade of grpc to address a rare crash on newer versions of Android

- gradle/wrapper/gradle-wrapper.properties
Reverts CruGlobal/godtools-android#1641
firebase app distribution doesn't currently support gradle 7. https://github.com/firebase/firebase-android-sdk/issues/2580
> Revert "Update Gradle Wrapper from 6.8.3 to 7.0"

- ui/article-renderer/src/main/res/layout/list_item_category.xml
- ui/base-tool/src/main/java/org/cru/godtools/base/tool/databinding/TextViewAdapters.kt
- ui/base-tool/src/main/res/layout/tool_content_button.xml
- ui/base-tool/src/main/res/layout/tool_content_button_outlined.xml
- ui/base-tool/src/main/res/layout/tool_content_link.xml
- ui/base-tool/src/test/java/org/cru/godtools/base/tool/databinding/TextViewAdaptersTest.kt
- ui/tract-renderer/src/main/res/layout/tract_content_card.xml
- ui/tract-renderer/src/main/res/layout/tract_page_hero.xml
- The category label should automatically resolve the correct label color
- no need to define a default text color for buttons, the model correctly represents this already
- no need to define a default color for links
- no need to define the default text color for card labels
- no need to define a default color for the hero heading
- remove defaultTextColor parameter from the bindTextNode method
Dependent on:
> Allow model to define default text-colors

- analysis/lint/lint.xml
This reverts commit 0fc01925b91a5eb2c8b12061fb7f5e575cadf4a6.
> Revert "disable Timber lint checks until it is updated for AGP 7.0.0"

- ui/base-tool/src/main/res/layout/tool_content_multiselect_option.xml
when the multiselect option is created the `layout_constraintWidth_percentage` wouldn't initially be set. This would cause all options to be rendered in a single row.
Once databinding runs it would attempt to set the percentage to 100%, but would short-circuit because the unset internal value is 100%. This would result in the view not being re-laid out.
> GT-1275 Fix multiselect layout when rendering a single column

- app/src/main/java/org/cru/godtools/ui/tooldetails/ToolDetailsFragment.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/activity/TractActivity.kt
- ui/tutorial-renderer/src/main/java/org/cru/godtools/tutorial/TutorialActivityResultContract.kt
- create a Tutorial AcitvityResultContract for launching tutorials expecting results
- update ToolDetailsFragment to use tutorial ActivityResultContract
- use the ActivityResultContract for launching the tutorial activity
> Switch from onActivityResult to new ActivityResultContract API

- library/base/src/main/java/org/cru/godtools/base/Settings.kt
- ui/base-tool/src/main/java/org/cru/godtools/base/tool/activity/BaseToolActivity.kt
- ui/lesson-renderer/build.gradle
- ui/lesson-renderer/src/main/java/org/cru/godtools/tool/lesson/analytics/model/LessonFeedbackAnalyticsEvent.kt
- ui/lesson-renderer/src/main/java/org/cru/godtools/tool/lesson/ui/LessonActivity.kt
- ui/lesson-renderer/src/main/java/org/cru/godtools/tool/lesson/ui/feedback/LessonFeedbackDialogFragment.kt
- ui/lesson-renderer/src/main/res/layout/lesson_feedback_dialog.xml
- ui/lesson-renderer/src/main/res/values/strings_lesson_feedback.xml
- create a lesson feedback dialog fragment
- submit the lesson feedback via an AnalyticsEvent
- track lesson feedback using the feature discovery subsystem
- make it possible to override the checkForManifestEvent behavior
- show the lesson feedback dialog fragment when finishing a lesson
- mark the lesson feedback as discovered when dismissing the dialog
> GT-1189 Support providing lesson feedback

- library/base/build.gradle
- library/base/src/main/java/org/cru/godtools/base/Settings.kt
- ui/shortcuts/src/main/java/org/cru/godtools/shortcuts/GodToolsShortcutManager.kt
- ui/shortcuts/src/test/java/org/cru/godtools/shortcuts/GodToolsShortcutManagerTest.kt
- expose the primary and parallel languages as coroutine flows
- update the GodToolsShortcutManager to monitor primary & parallel language changes via coroutine flows
- remove unused register/unregister listener methods
> Use coroutines Flow to monitor for primary/parallel language changes

- build.gradle
- settings.gradle.kts
This reverts commit 881dd2a8d361dfc02526b40ff300166409a152ee.
This is dependent on v0.17.0+ of the vanniktech jacoco plugin being released
> Revert "temporarily use the snapshot build of the vanniktech jacoco plugin"

- ui/base-tool/src/main/java/org/cru/godtools/base/tool/activity/BaseSingleToolActivity.kt
- ui/base-tool/src/main/java/org/cru/godtools/base/tool/activity/BaseToolActivity.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/activity/TractActivity.kt
The last thing we were using `onUpdateActiveManifest()` for was to trigger feature discovery for the share menu. This refactors the logic to more directly monitor share menu visibility to trigger feature discovery.
> GT-1306 Remove unnecessary onUpdateActiveManifest() lifecycle event

- library/analytics/build.gradle.kts
- library/analytics/src/debug/AndroidManifest.xml
- library/analytics/src/main/java/org/cru/godtools/analytics/appsflyer/AppsFlyerSpringboardActivity.kt
- library/analytics/src/release/AndroidManifest.xml
- ui/base-tool/build.gradle.kts
- ui/base/build.gradle.kts
- ui/tutorial-renderer/build.gradle.kts
AppsFlyer deep links are not being captured by MainActivity when we use the `singleTask` launch mode. This PR introduces an intermediary SpringBoard activity that will handle appsflyer deep links and not be affected by the MainActivity launch mode.
> GT-1317 Fix AppsFlyer deep links when GodTools is already running

- ui/shortcuts/src/main/java/org/cru/godtools/shortcuts/GodToolsShortcutManager.kt
- ui/shortcuts/src/main/java/org/cru/godtools/shortcuts/ShortcutModule.kt
- ui/shortcuts/src/test/java/org/cru/godtools/shortcuts/GodToolsShortcutManagerDispatcherTest.kt
- ui/shortcuts/src/test/java/org/cru/godtools/shortcuts/GodToolsShortcutManagerTest.kt
This splits some of the ShortcutManager functionality to make it easier to test certain behaviors. This is in preparation for Kotlin Coroutines 1.6.0 which changes how coroutines tests run
> GT-1363 Separate Dispatcher logic from ShortcutManager

- app/src/main/java/org/cru/godtools/databinding/PicassoImageViewBindingAdapter.kt
- library/base/build.gradle.kts
- library/base/src/main/kotlin/org/cru/godtools/base/FileManager.kt
- library/base/src/main/kotlin/org/cru/godtools/base/FileSystem.kt
- library/base/src/main/kotlin/org/cru/godtools/base/ToolFileSystem.kt
- library/base/src/test/kotlin/org/cru/godtools/base/FileManagerTest.kt
- library/base/src/test/kotlin/org/cru/godtools/base/FileSystemTest.kt
- library/download-manager/src/main/java/org/cru/godtools/download/manager/GodToolsDownloadManager.kt
- library/download-manager/src/test/java/org/cru/godtools/download/manager/GodToolsDownloadManagerTest.kt
- library/model/src/main/kotlin/org/cru/godtools/model/Attachment.kt
- library/model/src/main/kotlin/org/cru/godtools/model/LocalFile.kt
- ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/model/Resource.kt
- ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/service/AemArticleManager.kt
- ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/ui/ArticleWebViewClient.kt
- ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/util/AemFileSystem.kt
- ui/article-aem-renderer/src/test/java/org/cru/godtools/article/aem/service/AemArticleManagerTest.kt
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/BaseToolRendererModule.kt
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/databinding/LottieAnimationViewBindingAdapter.kt
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/databinding/MaterialButtonAdapters.kt
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/databinding/PicassoImageViewAdapters.kt
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/databinding/TextViewAdapters.kt
- ui/shortcuts/src/main/java/org/cru/godtools/shortcuts/GodToolsShortcutManager.kt
- ui/shortcuts/src/test/java/org/cru/godtools/shortcuts/GodToolsShortcutManagerTest.kt
- simplify the base FileManager class
- rename FileManager to FileSystem
> Rename FileManager to FileSystem

- library/analytics/src/test/java/org/cru/godtools/analytics/firebase/FirebaseAnalyticsServiceTest.kt
- ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/service/AemArticleManager.kt
- ui/article-aem-renderer/src/test/java/org/cru/godtools/article/aem/service/AemArticleManagerTest.kt
- stop using deprecated receiveOrNull() method
- replace offer with trySend
- close the userInfoChannel when cleaning up FirebaseAnalyticsServiceTest
> GT-1361 Cleanup some coroutines functionality

- ui/cyoa-renderer/src/main/kotlin/org/cru/godtools/tool/cyoa/ui/CyoaActivity.kt
- ui/cyoa-renderer/src/main/kotlin/org/cru/godtools/tool/cyoa/ui/controller/CardCollectionPageController.kt
- Enable the language toggle UI for cyoa tools
- no need to re-set the lifecycleOwner to the binding
- stay on the currently selected card when toggling languages
> GT-1379 fix card behavior when toggling languages

- ui/cyoa-renderer/src/main/kotlin/org/cru/godtools/tool/cyoa/ui/CyoaActivity.kt
- ui/cyoa-renderer/src/main/kotlin/org/cru/godtools/tool/cyoa/ui/CyoaCardCollectionPageFragment.kt
- ui/cyoa-renderer/src/main/kotlin/org/cru/godtools/tool/cyoa/ui/CyoaContentPageFragment.kt
- ui/cyoa-renderer/src/main/kotlin/org/cru/godtools/tool/cyoa/ui/CyoaPageFragment.kt
- ui/cyoa-renderer/src/test/kotlin/org/cru/godtools/tool/cyoa/ui/CyoaActivityTest.kt
- have the CyoaPageFragment notify a listener if it is no longer valid
- add some unit tests dealing with varying invalid/missing pages when changing the manifest
- execute any pending transactions before asserting the page stack
- finish the tool if the initial page disappears and the stack goes to show it
> GT-1328 GT-1329 Reload/dismiss pages when they change

- ui/cyoa-renderer/src/main/kotlin/org/cru/godtools/tool/cyoa/analytics/model/CyoaCardCollectionPageAnalyticsScreenEvent.kt
- ui/cyoa-renderer/src/main/kotlin/org/cru/godtools/tool/cyoa/analytics/model/CyoaPageAnalyticsScreenEvent.kt
- ui/cyoa-renderer/src/main/kotlin/org/cru/godtools/tool/cyoa/ui/CyoaActivity.kt
- ui/cyoa-renderer/src/main/kotlin/org/cru/godtools/tool/cyoa/ui/CyoaCardCollectionPageFragment.kt
- ui/cyoa-renderer/src/main/kotlin/org/cru/godtools/tool/cyoa/ui/CyoaContentPageFragment.kt
- ui/cyoa-renderer/src/main/kotlin/org/cru/godtools/tool/cyoa/ui/CyoaPageFragment.kt
- ui/cyoa-renderer/src/main/kotlin/org/cru/godtools/tool/cyoa/ui/controller/CardCollectionPageController.kt
- ui/cyoa-renderer/src/main/kotlin/org/cru/godtools/tool/cyoa/ui/controller/ContentPageController.kt
- ui/cyoa-renderer/src/test/kotlin/org/cru/godtools/tool/cyoa/analytics/model/CyoaPageAnalyticsScreenEventTest.kt
- ui/cyoa-renderer/src/test/kotlin/org/cru/godtools/tool/cyoa/ui/CyoaActivityTest.kt
- fire off any analytics events defined in the content xml for content pages and card collection pages
- initial pass at a CYOA analytics screen event
- add a controller generic to CyoaPageFragment
- create a screen analytics event for card collection cards
- trigger screen analytics events when viewing cyoa pages
> GT-1384 Fire screen analytics events for CYOA renderer

- ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/AemArticleRendererModule.kt
- ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/service/AemArticleManager.kt
- ui/article-aem-renderer/src/test/java/org/cru/godtools/article/aem/service/AemArticleManagerDispatcherTest.kt
- ui/article-aem-renderer/src/test/java/org/cru/godtools/article/aem/service/AemArticleManagerFileManagerTest.kt
- ui/article-aem-renderer/src/test/java/org/cru/godtools/article/aem/service/AemArticleManagerTest.kt
- Split off file manager and dispatcher logic from core `AemArticleManager`
- Split up tests to test dispatcher and file manager parts independently
> GT-1385 Refactor AemArticleManager to be more easily tested

- app/src/main/java/org/cru/godtools/GodToolsApplication.kt
- app/src/main/java/org/cru/godtools/dagger/ServicesModule.kt
- library/download-manager/build.gradle.kts
- library/download-manager/src/main/java/org/cru/godtools/download/manager/GodToolsDownloadManager.kt
- library/download-manager/src/main/java/org/cru/godtools/download/manager/work/DownloadLatestPublishedTranslationWorker.kt
- library/download-manager/src/test/java/org/cru/godtools/download/manager/GodToolsDownloadManagerTest.kt
- library/sync/src/main/java/org/cru/godtools/sync/GodToolsSyncService.kt
- library/sync/src/main/java/org/cru/godtools/sync/task/LanguagesSyncTasks.kt
- library/sync/src/main/java/org/cru/godtools/sync/task/ToolSyncTasks.kt
- library/sync/src/main/java/org/cru/godtools/sync/work/SyncFollowupWorker.kt
- library/sync/src/main/java/org/cru/godtools/sync/work/SyncLanguagesWorker.kt
- library/sync/src/main/java/org/cru/godtools/sync/work/SyncToolSharesWorker.kt
- library/sync/src/main/java/org/cru/godtools/sync/work/SyncToolsWorker.kt
- support deferred initialization of WorkManager
- keep existing work to avoid reseting backoff timers
- when syncing tools fails, reschedule with workmanager
- use WorkManager to retry languages sync the next time the device is online
- use WorkManager to reschedule a tool download if it failed
> GT-1349 Use WorkManager to update tools when the user is online

- gradle/libs.versions.toml
- library/api/build.gradle.kts
- library/api/src/main/java/org/cru/godtools/api/ApiModule.kt
- library/api/src/main/java/org/cru/godtools/api/AuthApi.kt
- library/api/src/main/java/org/cru/godtools/api/GodToolsSessionInterceptor.kt
- library/api/src/main/java/org/cru/godtools/api/UserCountersApi.kt
- library/api/src/main/java/org/cru/godtools/api/model/AuthToken.kt
- library/db/src/main/kotlin/org/keynote/godtools/android/db/Contract.kt
- library/db/src/main/kotlin/org/keynote/godtools/android/db/GodToolsDao.kt
- library/db/src/main/kotlin/org/keynote/godtools/android/db/GodToolsDatabase.kt
- library/db/src/main/kotlin/org/keynote/godtools/android/db/UserCounterMapper.kt
- library/model/src/main/kotlin/org/cru/godtools/model/UserCounter.kt
- library/model/src/test/kotlin/org/cru/godtools/model/UserCounterTest.kt
- library/model/src/test/resources/org/cru/godtools/model/user_counter.json
- library/sync/build.gradle.kts
- library/sync/src/main/java/org/cru/godtools/sync/GodToolsSyncService.kt
- library/sync/src/main/java/org/cru/godtools/sync/task/BaseSyncTasks.kt
- library/sync/src/main/java/org/cru/godtools/sync/task/SyncTaskModule.kt
- library/sync/src/main/java/org/cru/godtools/sync/task/UserCounterSyncTasks.kt
- library/user-data/build.gradle.kts
- library/user-data/src/main/AndroidManifest.xml
- library/user-data/src/main/kotlin/org/cru/godtools/user/data/Counters.kt
- settings.gradle.kts
- create a UserCounter model for syncing UserCounters from the API
- track user counters in the database
- Add support for authenticated APIs on mobile-content-api
- add API interface for reading user counters from the API
- add logic to sync user counters from the API
- add a db method to update a UserCounter delta
- add logic to sync dirty user counters to the API
- create Counters singleton for updating a user counter
> GT-1382 Track & Sync User counters with the API

- ui/cyoa-renderer/src/main/kotlin/org/cru/godtools/tool/cyoa/ui/controller/CardCollectionPageController.kt
this works around a visual issue when changing the cards being rendered
Dependent on:
> GT-1379 use the PageTransformerFix from gto-support

- ui/cyoa-renderer/src/main/kotlin/org/cru/godtools/tool/cyoa/ui/CyoaActivity.kt
- ui/cyoa-renderer/src/test/kotlin/org/cru/godtools/tool/cyoa/ui/CyoaActivityTest.kt
- when asserting a page stack, assert that only 1 fragment is currently visible
- rename parameter to replaceCurrentPage to model the functionality without exposing the internals of how it's working
- rework the replace logic to always use the back stack (except for replacing the root page)
> GT-1329 Fix fragment back stack bug when replacing a page

- library/download-manager/build.gradle.kts
- library/download-manager/src/main/java/org/cru/godtools/download/manager/GodToolsDownloadManager.kt
- library/download-manager/src/test/java/org/cru/godtools/download/manager/GodToolsDownloadManagerTest.kt
- if nothing changes about an attachment, don't update it in the database
- This caused an infinite loop when the device was offline and unable to download an attachment
- fix the DownloadLatestPublishedTranslationWorker
- This prevented the Worker from correctly starting when the device came back online
> GT-1423 GT-1349 Fix DownloadManager issues

- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/activity/MultiLanguageToolActivity.kt
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/activity/MultiLanguageToolActivityDataModel.kt
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/ui/controller/BaseController.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/activity/TractActivity.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/adapter/ManifestPagerAdapter.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/CardController.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/PageController.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/tips/InlineTipController.kt
- ui/tract-renderer/src/test/java/org/cru/godtools/tract/activity/TractActivityTest.kt
- utilize new menu livedata observer extension function
- disable tips menu item if there are no tips available for this tool
> GT-1432 Only show tips when they are actually available

- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/controller/PageController.kt
- ui/tract-renderer/src/main/res/layout/tract_page.xml
in the tips refactor I accidentally stopped setting the enableTips boolean on the page data binding
> GT-1432 fix showing tips for headers and call to actions

- ui/article-aem-renderer/src/main/java/org/cru/godtools/article/aem/ui/AemArticleActivity.kt
- ui/base-tool/build.gradle.kts
- ui/base-tool/src/main/AndroidManifest.xml
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/activity/BaseToolActivity.kt
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/activity/MultiLanguageToolActivityDataModel.kt
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/ui/share/OtherActionsAdapter.kt
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/ui/share/ShareAppsAdapter.kt
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/ui/share/ShareBottomSheetDialogFragment.kt
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/ui/share/model/DefaultShareItem.kt
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/ui/share/model/ShareItem.kt
- ui/base-tool/src/main/res/drawable/ic_more_horiz_24dp.xml
- ui/base-tool/src/main/res/layout/tool_share_item_app.xml
- ui/base-tool/src/main/res/layout/tool_share_item_more.xml
- ui/base-tool/src/main/res/layout/tool_share_sheet.xml
- ui/base-tool/src/main/res/values/strings_tool_renderer.xml
- ui/base-tool/src/main/res/values/styles_share_sheet.xml
- ui/base-tool/src/test/kotlin/org/cru/godtools/base/tool/activity/MultiLanguageToolActivityDataModelTest.kt
- ui/base-tool/src/test/kotlin/org/cru/godtools/base/tool/databinding/ToolShareSheetBindingTest.kt
- ui/base/src/main/res/values/colors.xml
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/activity/TractActivity.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/ui/share/model/LiveShareItem.kt
- ui/tract-renderer/src/main/res/layout/tract_share_item_live_share.xml
- ui/tract-renderer/src/main/res/menu/activity_tract_live_share.xml
- ui/tract-renderer/src/test/java/org/cru/godtools/tract/activity/TractActivityTest.kt
- wrap shareToolUri into LiveData to be able to observe changes
- get rid of unnecessary updateShareMenuItem method
- remove unnecessary message for share message subject
- create ShareBottomSheetDialogFragment
- trigger the new share sheet when there is more than 1 share item
- add Live Share item to custom share sheet
> GT-1446 Create a custom Tool Share Sheet

- app/src/main/java/org/cru/godtools/ui/dashboard/tools/ToolCategoriesAdapter.kt
- app/src/main/res/layout/dashboard_tools_spotlight.xml
Requested Changes from Jira Ticket https://jira.cru.org/browse/GT-1441 
> Hi Gyasi, we met with Lucas and Justin this morning and we have some feedback on the tickets that are ready for QA. Everything is functioning properly and for the most part looks great, but we wanted to request a few minor changes and had a few questions. I’m going to list them here but please advise us how to best communicate this through Jira - Do we make a new ticket with requested tweaks or do we fail the current tickets?
> 
> - Can we please swap the order of the category boxes so that All Tools appears in the top left instead of the bottom right?
> - Can we add a small bit of padding between top blue bar and the “Tool Spotlight” top line? Should match the padding between bottom of spotlighted tools and the …
> Gt 1441   UI change request

- ui/shortcuts/src/main/kotlin/org/cru/godtools/shortcuts/GodToolsShortcutManager.kt
- ui/shortcuts/src/test/kotlin/org/cru/godtools/shortcuts/GodToolsShortcutManagerDispatcherTest.kt
in rare situations eventbus can be triggered with an event before initialization has finished
> GT-1484 Avoid a race condition between EventBus and ShortcutManager initialization

- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/activity/BaseSingleToolActivity.kt
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/activity/BaseToolActivity.kt
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/activity/MultiLanguageToolActivity.kt
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/activity/MultiLanguageToolActivityDataModel.kt
- ui/base-tool/src/test/kotlin/org/cru/godtools/base/tool/activity/MultiLanguageToolActivityDataModelTest.kt
- ui/tract-renderer/src/main/java/org/cru/godtools/tract/activity/TractActivity.kt
- ui/tract-renderer/src/test/java/org/cru/godtools/tract/activity/TractActivityTest.kt
This PR adjusts logic within multi language tools so that the languages can be adjusted dynamically after the activity is initially created.
This does not add any UI for actually adjusting the languages, this is just adjustmenets to the underlying data model
> GT-1433 Make it possible to adjust the locales for an active tool

- build.gradle
- gradle/libs.versions.toml
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/activity/MultiLanguageToolActivity.kt
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/activity/MultiLanguageToolActivityDataModel.kt
- ui/base-tool/src/test/kotlin/org/cru/godtools/base/tool/activity/MultiLanguageToolActivityDataModelTest.kt
- ui/tract-renderer/src/test/kotlin/org/cru/godtools/tract/ExternalSingletonsModule.kt
- ui/tract-renderer/src/test/kotlin/org/cru/godtools/tract/activity/TractActivityTest.kt
This moves the logic that initializes and manages `activeLocale` into the DataModel and adds tests for the logic.
Changing the primary and parallel language while viewing a tool may have an impact on this logic if the `activeLocale` no longer references the primary or parallel language
> GT-1433 Manage the activeLocale within the Data Model itself

- app/build.gradle
we recently moved the debug source to a kotlin source directory, this fixes the cross-reference from the QA build
> include the debug kotlin source directory

- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/activity/BaseToolActivity.kt
- ui/tract-renderer/build.gradle.kts
- ui/tract-renderer/src/main/kotlin/org/cru/godtools/tract/activity/TractActivity.kt
- ui/tract-renderer/src/main/kotlin/org/cru/godtools/tract/databinding/TractSettingsSheetCallbacks.kt
- ui/tract-renderer/src/main/kotlin/org/cru/godtools/tract/ui/settings/SettingsBottomSheetDialogFragment.kt
- ui/tract-renderer/src/main/kotlin/org/cru/godtools/tract/ui/settings/ShareablesAdapter.kt
- ui/tract-renderer/src/main/res/layout/tract_settings_item_shareable_image.xml
- ui/tract-renderer/src/main/res/layout/tract_settings_sheet.xml
- ui/tract-renderer/src/main/res/values/strings_tract_renderer.xml
- display tool shareables in the tract settings dialog
- make sure deviceLocale is up to date for the Settings dialog
- remove LiveShareItem from the share items for tracts
- don't include Shareables in the Share dialog for tract tools
- the ShareMenuItem no longer exists for TractActivities, so make it never visible
> GT-1391 Enable Shareables in new tool settings UI

- app/build.gradle
- app/src/main/kotlin/org/cru/godtools/ui/dashboard/RemoveFavoriteConfirmationDialogFragment.kt
- app/src/main/kotlin/org/cru/godtools/ui/dashboard/tools/ToolsFragment.kt
- app/src/main/kotlin/org/cru/godtools/ui/tools/ToolsAdapter.kt
- app/src/main/kotlin/org/cru/godtools/ui/tools/ToolsAdapterCallbacks.kt
- app/src/main/kotlin/org/cru/godtools/ui/tools/ToolsAdapterViewModel.kt
- app/src/main/kotlin/org/cru/godtools/ui/tools/ToolsListFragment.kt
- app/src/main/kotlin/org/keynote/godtools/android/activity/MainActivity.kt
- app/src/main/res/layout/dashboard_list_item_tool.xml
- app/src/main/res/layout/dashboard_tools_spotlight_tool.xml
- app/src/main/res/layout/tools_list_item_lesson.xml
- app/src/main/res/layout/tools_list_item_tool.xml
- app/src/test/kotlin/org/cru/godtools/databinding/ToolsListItemToolBindingTest.kt
- set the ToolViewModel directly to the data binding
- update tool list item to utilize ToolViewModel
- update the dashboard tool layout to use toolViewModel
- update the spotlight tool layout to use the ToolViewModel directly
- consolidate some duplication in tool selection callbacks
- trigger the RemoveFavorite confirmation dialog on the favorites dashboard UI
> GT-1488 Make some tweaks to ToolsAdapter binding and callbacks

- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/activity/MultiLanguageToolActivityDataModel.kt
- ui/base-tool/src/test/kotlin/org/cru/godtools/base/tool/activity/MultiLanguageToolActivityDataModelTest.kt
- add a unit test that replicates the crash during application restart
- initialize LiveData caches before they get used later in initialization
> GT-1507 Fix DataModel crash

- library/analytics/build.gradle.kts
- library/analytics/src/main/AndroidManifest.xml
the client_token is required starting with Facebook SDK 13.2.0
> GT-1540 Fix Crash caused by misconfigured Facebook SDK

- ui/shortcuts/src/main/kotlin/org/cru/godtools/shortcuts/GodToolsShortcutManager.kt
- ui/shortcuts/src/test/kotlin/org/cru/godtools/shortcuts/GodToolsShortcutManagerDispatcherTest.kt
- monitor db invalidations instead of relying on EventBus events for updating pending events
- we no longer need to use an actor to trigger pending shortcut updates
- use a dao invalidation flow instead of eventbus to monitor for changes to attachments, tools, and translations
- we no longer need to use eventbus with the shortcut manager dispatcher
- convert shortcut manager dispatcher tests to MockK
- utilize runTest for all the dispatcher tests
- model the fact that the various flows emit initial values when collecting
- updateShortcutsJob no longer needs to be an actor
> Refactor the ShortcutManager Dispatcher to no longer use EventBus

- app/src/main/kotlin/org/cru/godtools/ui/dashboard/tools/ToolsFragmentDataModel.kt
- app/src/test/kotlin/org/cru/godtools/ui/dashboard/tools/ToolsFragmentDataModelQueriesTest.kt
- library/db/src/main/kotlin/org/keynote/godtools/android/db/Contract.kt
- update all tools queries to filter based on meta-tools
- add a couple unit tests around `QUERY_TOOLS` behavior
- add a unit test to ensure spotlight tools can include non-default variants
> GT-1559 Handle Meta-tools within the All Tools UI

- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/analytics/model/ContentEventAnalyticsActionEvent.kt
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/analytics/model/ShareShareableAnalyticsActionEvent.kt
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/analytics/model/ToolAnalyticsActionEvent.kt
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/analytics/model/ToolOpenedAnalyticsActionEvent.kt
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/ui/shareable/ShareableImageBottomSheetDialogFragment.kt
- ui/lesson-renderer/src/main/kotlin/org/cru/godtools/tool/lesson/analytics/model/LessonFeedbackAnalyticsEvent.kt
- introduce an intermediary ToolAnalyticsActionEvent that will handle common metadata for tool action events
- trigger analytics event for sharing a shareable
> GT-1588 Add analytics events to shareables

- app/src/main/kotlin/org/cru/godtools/ui/dashboard/DashboardActivity.kt
transitions cause the app to crash if the app is transitioning to/from a view hierarchy containing a ComposableView
> GT-1616 Transitions crash when they interact with a ComposeView

- app/src/main/kotlin/org/cru/godtools/ui/dashboard/home/HomeViewModel.kt
- library/db/build.gradle.kts
- library/db/src/main/kotlin/org/keynote/godtools/android/db/repository/Constants.kt
- library/db/src/main/kotlin/org/keynote/godtools/android/db/repository/LessonsRepository.kt
- library/db/src/main/kotlin/org/keynote/godtools/android/db/repository/ToolsRepository.kt
- library/db/src/test/kotlin/org/keynote/godtools/android/db/repository/ToolsRepositoryTest.kt
- cleanup db dependencies
- use a SharedFlow for favoriteTools
- move spotlightLessons query into LessonsRepository
> enable caching of several DB queries

- app/src/main/kotlin/org/cru/godtools/activity/BasePlatformActivity.kt
- app/src/main/kotlin/org/cru/godtools/ui/dashboard/DashboardActivity.kt
- app/src/main/kotlin/org/cru/godtools/ui/dashboard/home/HomeFragment.kt
- app/src/main/kotlin/org/cru/godtools/ui/dashboard/home/HomeLayout.kt
- app/src/main/kotlin/org/cru/godtools/ui/dashboard/home/HomeViewModel.kt
- app/src/main/kotlin/org/cru/godtools/ui/tools/AvailableInLanguage.kt
- app/src/main/kotlin/org/cru/godtools/ui/tools/DownloadProgressIndicator.kt
- app/src/main/kotlin/org/cru/godtools/ui/tools/FavoriteAction.kt
- app/src/main/kotlin/org/cru/godtools/ui/tools/ToolCardActions.kt
- app/src/main/kotlin/org/cru/godtools/ui/tools/ToolCardLayouts.kt
- app/src/main/res/drawable/ic_language_available.xml
- app/src/main/res/drawable/ic_language_unavailable.xml
- app/src/testDebug/kotlin/org/cru/godtools/ui/tools/FavoriteActionTest.kt
- ui/base/src/main/kotlin/org/cru/godtools/base/ui/util/ProvideLayoutDirectionFromLocale.kt
- apply the Theme in the Fragment, not in the HomeLayout
- update AvailableInLanguage Composable to fit better in multiple different layouts
- move ProvideLayoutDirectionFromLocale to :ui:base module
- trigger analytics events from within the HomeLayout
- allow lesson names to overflow 2 lines if necessary for a language or acccessibility settings
- move AvailableInLanguage Composable to it's own source file
- move FavoriteAction composable to it's own source file
- animate the download progress indicator
- display an up affordance when the user is on the list of favorites
- create a ToolCardActions composable that renders the open and tool details buttons
> GT-1529 Adjust the composables for the Home UI

- app/build.gradle.kts
- library/base/src/main/kotlin/org/cru/godtools/base/util/LocaleUtils.kt
- ui/base/src/main/kotlin/org/cru/godtools/base/ui/util/ModelUtils.kt
- ui/tract-renderer/src/main/kotlin/org/cru/godtools/tract/activity/TractActivity.kt
- enable minification for QA builds
- disable Facebook Flipper on Android Lollipop
- disable resource shrinking
- we no longer need to enable support vector drawables due to not supporting Android pre-Lollipop
- use the newer method for installing from the instant app
- utilize localizeIfPossible method from gto-support
- stop using deprecated LocaleUtils.getFallbacks
- use release build of gto-support library
> GT-1677 GT-1649 Fix several code shrinking related crashes

- app/build.gradle.kts
- build.gradle
- buildSrc/src/main/kotlin/AndroidConfiguration.kt
- feature/bundledcontent/build.gradle.kts
- gradle/libs.versions.toml
- library/initial-content/build.gradle.kts
- settings.gradle.kts
- ui/base/build.gradle.kts
- tweak how DynamicFeatures are configured via buildSrc
- configure the default test framework dependencies via the test configuration in buildSrc
- auto-accept build scans on GHA via settings.gradle.kts
- there is no need to configure androidx-annotations for every module anymore
- we no longer need to force the version of androidx-lifecycle-viewmodel-ktx
- use register instead of create for lazy creation
- there is no need to use delegates for productFlavors or signingConfigs
- consolidate the firebase app distribution configuration
- Move common QA buildType configuration to buildSrc
- force the newer version of hamcrest in our Android Test config
- use new APIs for filtering stage flavors when flavors are configured
> Various Build Adjustments

- app/src/main/kotlin/org/cru/godtools/ui/dashboard/DashboardActivity.kt
- app/src/main/kotlin/org/cru/godtools/ui/dashboard/analytics/model/DashboardToolClickedAnalyticsActionEvent.kt
- app/src/main/kotlin/org/cru/godtools/ui/dashboard/home/HomeLayout.kt
- app/src/main/kotlin/org/cru/godtools/ui/dashboard/home/HomeViewModel.kt
- app/src/main/kotlin/org/cru/godtools/ui/dashboard/lessons/LessonsLayout.kt
- app/src/main/kotlin/org/cru/godtools/ui/dashboard/lessons/LessonsViewModel.kt
- app/src/main/kotlin/org/cru/godtools/ui/dashboard/tools/ToolsLayout.kt
- app/src/main/kotlin/org/cru/godtools/ui/dashboard/tools/ToolsViewModel.kt
- app/src/main/kotlin/org/cru/godtools/ui/tools/analytics/model/AboutToolButtonAnalyticsActionEvent.kt
- track clicks on lesson cards and on the tools UI in analytics
- record tool clicks in analytics for the home UI
- remove old open tool analytics event object
> GT-1691 GT-1692 Include a source when recording open tool analytics events

- ui/base-tool/build.gradle.kts
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/ui/controller/AccordionController.kt
- ui/base-tool/src/test/kotlin/org/cru/godtools/base/tool/ui/controller/AccordionControllerTest.kt
- ui/base-tool/src/test/kotlin/org/cru/godtools/base/tool/ui/controller/AccordionSectionControllerTest.kt
- add an isActiveSection method to the AccordionController
- utilize a ConstrainedLifecycleOwner for accordion sections to reflect whether the section is selected or not
- trigger visible analytics events for accordion sections
> GT-1604 Support triggering VISIBLE analytics events on accordion sections

- app/src/main/kotlin/org/cru/godtools/ui/dashboard/DashboardLayout.kt
- app/src/main/kotlin/org/cru/godtools/ui/dashboard/DashboardViewModel.kt
- library/analytics/build.gradle.kts
- library/analytics/src/main/kotlin/org/cru/godtools/analytics/compose/RecordAnalyticsScreen.kt
- library/analytics/src/main/kotlin/org/cru/godtools/analytics/model/AnalyticsBaseEvent.kt
- library/analytics/src/main/kotlin/org/cru/godtools/analytics/model/AnalyticsScreenEvent.kt
- ui/base/src/main/kotlin/org/cru/godtools/base/ui/compose/CompositionLocals.kt
- ui/base/src/main/kotlin/org/cru/godtools/base/ui/theme/GodToolsTheme.kt
- create an EventBus composition local for use within Compose
- provide an EventBus object when in Android Studio Preview mode
- create a RecordAnalyticsScreen composable that will record screen analytics events when the composable is resumed
- update DashboardLayout to use RecordAnalyticsEvent composable
> GT-1600 Update how screen analytics events are recorded within compose

- gradle/libs.versions.toml
- ui/article-aem-renderer/src/test/kotlin/org/cru/godtools/article/aem/db/AbstractArticleRoomDatabaseTest.kt
- ui/article-aem-renderer/src/test/kotlin/org/cru/godtools/article/aem/db/AemImportRepositoryTest.kt
- ui/article-aem-renderer/src/test/kotlin/org/cru/godtools/article/aem/db/ArticleRepositoryTest.kt
- ui/article-aem-renderer/src/test/kotlin/org/cru/godtools/article/aem/db/TranslationRepositoryTest.kt
- ui/base-tool/build.gradle.kts
- ui/base/build.gradle.kts
- ui/cyoa-renderer/build.gradle.kts
- ui/lesson-renderer/build.gradle.kts
- ui/shortcuts/src/test/kotlin/org/cru/godtools/shortcuts/GodToolsShortcutManagerTest.kt
- ui/tract-renderer/build.gradle.kts
- update Dao mock to utilize MockK
- use MockK to provide the ShortcutManager spy
- use MockK for the PackageManager spy
- use MockK to provide the Application spy
- update article-aem-renderer tests to use MockK
- move Mockito dependency to only projects that still depend on it
- move Mockito Kotlin dependency to projects that still depend on it
> GT-1819 Migrate tests to use MockK

- library/db/src/main/kotlin/org/cru/godtools/db/repository/LastSyncTimeRepository.kt
- library/db/src/main/kotlin/org/cru/godtools/db/room/dao/LastSyncTimeDao.kt
- library/db/src/main/kotlin/org/cru/godtools/db/room/entity/LastSyncTimeEntity.kt
- library/db/src/main/kotlin/org/cru/godtools/db/room/repository/LastSyncTimeRoomRepository.kt
- library/db/src/test/kotlin/org/cru/godtools/db/repository/LastSyncTimeRepositoryIT.kt
- library/sync/src/main/kotlin/org/cru/godtools/sync/GodToolsSyncService.kt
- library/sync/src/main/kotlin/org/cru/godtools/sync/task/SyncTaskModule.kt
- library/sync/src/main/kotlin/org/cru/godtools/sync/task/UserCounterSyncTasks.kt
- library/sync/src/test/kotlin/org/cru/godtools/db/repository/InMemoryLastSyncTimeRepository.kt
- library/sync/src/test/kotlin/org/cru/godtools/sync/task/UserCounterSyncTasksTest.kt
The main thing this PR is attempting to workaround is a corner-case with non-forced syncs when the app user switches which Okta account they are logged into between 2 accounts. This could lead to stale user counters being used for up to 24 hours until fresh data would be transparently synced.
Potential flow of events:
- app logged in as User A
- app syncs counters, app marks that counters for user A have been synced and don't attempt another sync for 24 hours
- app logs out of User A & into User B
- app syncs counters, replaces User A counters in the database, app marks User B counters as having been synced
- app logs out of User B & back into User A
- app attempts to sync counters, but short-circuits because user A counters were synced less than 24 hours ago
> GT-1263 Update UserCounterSync logic to handle multiple users

- README.md
- app/build.gradle.kts
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/OneSkyConfiguration.kt
- gradle/libs.versions.toml
- library/base/build.gradle.kts
- ui/base-tool/build.gradle.kts
- ui/base/build.gradle.kts
- ui/cyoa-renderer/build.gradle.kts
- ui/lesson-renderer/build.gradle.kts
- ui/tips-renderer/build.gradle.kts
- ui/tract-renderer/build.gradle.kts
- ui/tutorial-renderer/build.gradle.kts
This configures the `uploadTranslations` and `downloadTranslations` tasks for all subprojects that contain translation files.
There are a few outstanding issues that prevent us from using a GHA workflow for this currently:
- The plugin doesn't support downloading changes to the base language from OneSky. I have opened a PR with the plugin to address this use case
- OneSky currently uses an older version of the CLDR database than Android. This means that exporting French plurals from OneSky will not pass Android lint checks. Manual intervention is required in these cases to fix the broken French plurals
- You have to use the `--no-parallel` command line option when downloading translations to avoid hitting OneSky API rate limits. It might be possible to use `--max-workers #` to restrict …
> GT-1828 Configure OneSky gradle plugin

- ui/article-aem-renderer/src/main/kotlin/org/cru/godtools/article/aem/ui/AemArticleActivity.kt
- ui/article-renderer/src/main/kotlin/org/cru/godtools/article/ui/ArticlesActivity.kt
- ui/base-tool/build.gradle.kts
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/activity/BaseSingleToolActivity.kt
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/activity/BaseSingleToolActivityDataModel.kt
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/activity/BaseToolActivity.kt
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/activity/BaseToolRendererViewModel.kt
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/activity/MultiLanguageToolActivity.kt
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/activity/MultiLanguageToolActivityDataModel.kt
- ui/base-tool/src/test/kotlin/org/cru/godtools/base/tool/activity/BaseToolRendererViewModelTest.kt
- ui/base-tool/src/test/kotlin/org/cru/godtools/base/tool/activity/MultiLanguageToolActivityDataModelTest.kt
- ui/cyoa-renderer/src/main/kotlin/org/cru/godtools/tool/cyoa/ui/CyoaActivity.kt
- ui/cyoa-renderer/src/main/kotlin/org/cru/godtools/tool/cyoa/ui/CyoaPageFragment.kt
- ui/cyoa-renderer/src/test/kotlin/org/cru/godtools/tool/cyoa/ExternalSingletonsModule.kt
- ui/cyoa-renderer/src/test/kotlin/org/cru/godtools/tool/cyoa/ui/CyoaActivityTest.kt
- ui/lesson-renderer/src/main/kotlin/org/cru/godtools/tool/lesson/ui/LessonActivity.kt
- ui/tract-renderer/src/main/kotlin/org/cru/godtools/tract/activity/TractActivity.kt
- ui/tract-renderer/src/main/kotlin/org/cru/godtools/tract/ui/settings/SettingsBottomSheetDialogFragment.kt
This PR extracts some common tool render view model business logic. It then ties into this business logic to record when a tool is actually used in a language with the user counters framework.
> GT-1854 Track which languages are used to render tools

- library/model/src/main/kotlin/org/cru/godtools/model/Tool.kt
- library/sync/src/main/kotlin/org/cru/godtools/sync/task/BaseDataSyncTasks.kt
In theory the api should never return an invalid tool...
> GT-1856 Fix a crash if an invalid tool is returned from the API

- library/db/src/main/kotlin/org/cru/godtools/db/repository/TrainingTipsRepository.kt
- library/db/src/main/kotlin/org/cru/godtools/db/room/dao/TrainingTipDao.kt
- library/db/src/main/kotlin/org/cru/godtools/db/room/entity/TrainingTipEntity.kt
- library/db/src/main/kotlin/org/cru/godtools/db/room/repository/TrainingTipsRoomRepository.kt
- library/db/src/test/kotlin/org/cru/godtools/db/repository/TrainingTipsRepositoryIT.kt
- library/db/src/test/kotlin/org/cru/godtools/db/room/GodToolsRoomDatabaseRule.kt
- library/db/src/test/kotlin/org/cru/godtools/db/room/repository/TrainingTipsRoomRepositoryIT.kt
- library/model/src/main/kotlin/org/cru/godtools/model/TrainingTip.kt
- library/user-data/src/main/kotlin/org/cru/godtools/user/activity/UserActivityManager.kt
- library/user-data/src/test/kotlin/org/cru/godtools/user/activity/UserActivityManagerTest.kt
- expose a completed tip flow from the TrainingTipsRepository
- include the number of completed tips in the counters sent to generate UserActivity
> GT-1850 Include the number of completed tips when generating activity

- library/account/src/main/kotlin/org/cru/godtools/account/GodToolsAccountManager.kt
- library/account/src/test/kotlin/org/cru/godtools/account/GodToolsAccountManagerTest.kt
The AccountManager tests were dependent on a task executing in a background thread. This meant that there was a race condition within the test that could lead to occasional failures of the test.
This PR utilizes the coroutines test scope for those background tasks so we can manually control execution of them.
> Stabilize AccountManager tests

- app/src/main/kotlin/org/cru/godtools/activity/BasePlatformActivity.kt
- app/src/main/kotlin/org/cru/godtools/ui/about/AboutActivity.kt
- app/src/main/kotlin/org/cru/godtools/ui/account/AccountLayout.kt
- app/src/main/kotlin/org/cru/godtools/ui/dashboard/DashboardLayout.kt
- app/src/main/kotlin/org/cru/godtools/ui/languages/LanguageSelectionActivity.kt
- app/src/main/kotlin/org/cru/godtools/ui/languages/LanguageSettingsActivity.kt
- app/src/main/kotlin/org/cru/godtools/ui/tooldetails/analytics/model/ToolDetailsScreenEvent.kt
- gradle/libs.versions.toml
- library/analytics/build.gradle.kts
- library/analytics/src/main/kotlin/org/cru/godtools/analytics/model/AnalyticsScreenEvent.kt
- ui/cyoa-renderer/src/main/kotlin/org/cru/godtools/tool/cyoa/analytics/model/CyoaCardCollectionPageAnalyticsScreenEvent.kt
- ui/cyoa-renderer/src/main/kotlin/org/cru/godtools/tool/cyoa/analytics/model/CyoaPageAnalyticsScreenEvent.kt
- ui/cyoa-renderer/src/test/kotlin/org/cru/godtools/tool/cyoa/analytics/model/CyoaCardCollectionPageAnalyticsScreenEventTest.kt
- ui/lesson-renderer/src/main/kotlin/org/cru/godtools/tool/lesson/analytics/model/LessonPageAnalyticsScreenEvent.kt
- ui/tips-renderer/src/main/kotlin/org/cru/godtools/tool/tips/analytics/model/TipAnalyticsScreenEvent.kt
- ui/tract-renderer/src/main/kotlin/org/cru/godtools/tract/analytics/model/TractPageAnalyticsScreenEvent.kt
- utilize analytics constant names from godtools shared
- add a unit test for the analytics screen name of a card collection page card
- update several tool analytics events to utilize the shared tool analytics screen names
- add analytics event for the account activity page
> GT-1878 Use shared analytics constants

- app/src/main/kotlin/org/cru/godtools/ui/tooldetails/ToolDetailsLayout.kt
- app/src/testDebug/kotlin/org/cru/godtools/ui/tooldetails/ToolDetailsLayoutTest.kt
- library/model/src/main/kotlin/org/cru/godtools/model/Language.kt
- library/model/src/test/kotlin/org/cru/godtools/model/LanguageTest.kt
- make sure the display name defaults to the default name if no locale is present
- add a couple unit tests for ToolDetailsLanguages()
- utilize getSortedDisplayNames() for the ToolDetailsLanguages composable
> GT-1864 Some cleanup and tests for ToolDetailsLanguages()

- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/activity/MultiLanguageToolActivity.kt
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/activity/MultiLanguageToolActivityDataModel.kt
- ui/tract-renderer/src/main/kotlin/org/cru/godtools/tract/activity/TractActivity.kt
- don't use the pointless livedata delegate for the primary and parallel locales
- update MultiLanguageToolActivityDataModel.locales to be a StateFlow
> GT-1879 make MultiLanguageToolActivityDataModel.locales a StateFlow

- gradle/libs.versions.toml
This reverts commit f0259da224dba5187741c2a87c856fdaa5e9d4eb.
There is some incompatibility in the 1.4.0-alpha02 compiler, I think it was originally masked by the gradle build cache.
> Revert "Update dependency androidx.compose.compiler:compiler to v1.4.0-alpha02"

- library/db/src/main/kotlin/org/cru/godtools/db/repository/LanguagesRepository.kt
- library/db/src/main/kotlin/org/cru/godtools/db/room/dao/LanguagesDao.kt
- library/db/src/main/kotlin/org/cru/godtools/db/room/repository/LanguagesRoomRepository.kt
- library/db/src/test/kotlin/org/cru/godtools/db/repository/LanguagesRepositoryIT.kt
- library/model/src/main/kotlin/org/cru/godtools/model/Followup.kt
- library/sync/src/main/kotlin/org/cru/godtools/sync/GodToolsSyncService.kt
- library/sync/src/main/kotlin/org/cru/godtools/sync/task/FollowupSyncTasks.kt
- library/sync/src/main/kotlin/org/cru/godtools/sync/work/SyncToolsWorker.kt
- library/sync/src/test/kotlin/org/cru/godtools/sync/GodToolsSyncServiceTest.kt
- library/sync/src/test/kotlin/org/cru/godtools/sync/task/FollowupSyncTasksTest.kt
In the various migrations from the legacy DAO to Room I missed updating the logic loading the language object from the database which is used to populate the Followup languageId. This issue would have triggered an exception, but I believe that exception was lost because it was running in a background coroutine.
After fixing the issue I added several tests for each part of the bug and fix implemented.
> GT-1791 Fix syncing followups to the API

- app/build.gradle.kts
- app/src/main/kotlin/org/cru/godtools/dagger/ConfigModule.kt
- buildSrc/src/main/kotlin/AndroidConfiguration.kt
- buildSrc/src/main/kotlin/GodToolsCustomUriConfiguration.kt
- buildSrc/src/main/kotlin/org/cru/godtools/gradle/bundledcontent/BundledContentConfiguration.kt
- buildSrc/src/main/kotlin/org/cru/godtools/gradle/bundledcontent/DownloadApiResourcesTask.kt
- buildSrc/src/main/kotlin/org/cru/godtools/gradle/bundledcontent/PruneJsonApiResponseTask.kt
- gradle/libs.versions.toml
- library/base/src/main/kotlin/org/cru/godtools/base/Constants.kt
- library/initial-content/build.gradle.kts
- ui/article-renderer/build.gradle.kts
- ui/article-renderer/src/main/kotlin/org/cru/godtools/article/ui/ArticlesActivity.kt
- ui/article-renderer/src/test/kotlin/org/cru/godtools/article/ExternalSingletonsModule.kt
- ui/article-renderer/src/test/kotlin/org/cru/godtools/article/ui/ArticlesActivityTest.kt
- ui/cyoa-renderer/build.gradle.kts
- ui/cyoa-renderer/src/main/kotlin/org/cru/godtools/tool/cyoa/ui/CyoaActivity.kt
- ui/cyoa-renderer/src/test/kotlin/org/cru/godtools/tool/cyoa/ExternalSingletonsModule.kt
- ui/cyoa-renderer/src/test/kotlin/org/cru/godtools/tool/cyoa/ui/CyoaActivityTest.kt
- ui/lesson-renderer/build.gradle.kts
- ui/lesson-renderer/src/main/kotlin/org/cru/godtools/tool/lesson/ui/LessonActivity.kt
- ui/lesson-renderer/src/test/kotlin/org/cru/godtools/tool/lesson/ExternalSingletonsModule.kt
- ui/lesson-renderer/src/test/kotlin/org/cru/godtools/tool/lesson/ui/LessonActivityTest.kt
- ui/tract-renderer/build.gradle.kts
- ui/tract-renderer/src/main/kotlin/org/cru/godtools/tract/activity/TractActivity.kt
- ui/tract-renderer/src/test/kotlin/org/cru/godtools/tract/ExternalSingletonsModule.kt
- ui/tract-renderer/src/test/kotlin/org/cru/godtools/tract/activity/TractActivityTest.kt
AGP (Android Gradle Plugin) 7.4.0 breaks the following deprecated features:
- test `manifestPlaceholders`
- using `libraryVariants` to dynamically attach downloaded assets
We address these issues by:
- configuring our debug/qa/release `manifestPlaceholders` in each library that uses them
- I was unable to find any other path to defining `manifestPlaceholders` for test variants. I think this is just a gap in coverage in the AGP as they are migrating to new APIs that interact with the gradle APIs in a cleaner manner. This will probably be addressed with time, but we needed a more immediate solution because this is blocking Kotlin 1.8, which is blocking some new features for Kotlin Multiplatform
- Updating the download initial content script to utilize the "new" `androidComponents.onVariants …
> GT-1901 Upgrade to AGP 7.4.0-rc03

- app/src/main/kotlin/org/cru/godtools/dagger/features/BundledContentFeatureDependencies.kt
- app/src/main/kotlin/org/cru/godtools/ui/tooldetails/ToolDetailsFragmentDataModel.kt
- app/src/main/kotlin/org/cru/godtools/ui/tools/ToolViewModels.kt
- library/db/src/main/kotlin/org/cru/godtools/db/DatabaseModule.kt
- library/db/src/main/kotlin/org/cru/godtools/db/repository/AttachmentsRepository.kt
- library/db/src/main/kotlin/org/keynote/godtools/android/db/Contract.kt
- library/db/src/main/kotlin/org/keynote/godtools/android/db/repository/LegacyAttachmentsRepository.kt
- library/db/src/test/kotlin/org/cru/godtools/db/repository/AttachmentsRepositoryIT.kt
- library/db/src/test/kotlin/org/keynote/godtools/android/db/repository/LegacyAttachmentsRepositoryIT.kt
- library/download-manager/src/main/kotlin/org/cru/godtools/download/manager/GodToolsDownloadManager.kt
- library/download-manager/src/test/kotlin/org/cru/godtools/download/manager/GodToolsDownloadManagerDispatcherTest.kt
- library/download-manager/src/test/kotlin/org/cru/godtools/download/manager/GodToolsDownloadManagerTest.kt
- library/initial-content/src/main/kotlin/org/cru/godtools/init/content/task/Tasks.kt
- library/initial-content/src/test/kotlin/org/cru/godtools/init/content/task/TasksTest.kt
- library/sync/src/main/kotlin/org/cru/godtools/sync/task/BaseDataSyncTasks.kt
- library/sync/src/main/kotlin/org/cru/godtools/sync/task/ToolSyncTasks.kt
- library/sync/src/test/kotlin/org/cru/godtools/sync/task/BaseDataSyncTasksTest.kt
This abstracts all database interactions around Attachments into a centralized `AttachmentsRepository`. This will allow us to change the underlying database implementation to utilize Room to track Attachments
> GT-1900 Abstract all Attachments db logic to an AttachmentsRepository

- library/download-manager/src/test/kotlin/org/cru/godtools/download/manager/GodToolsDownloadManagerTest.kt
- use the backgroundScope for DownloadManager tests
- create a common TestScope so we can setup the DownloadManager before a test starts executing
- there is no need to set a Main Dispatcher anymore
- remove unnecessary withDownloadManager inline function
> GT-1361 Update DownloadManager coroutines test logic

- library/db/src/main/kotlin/org/keynote/godtools/android/db/repository/TranslationsRepository.kt
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/activity/MultiLanguageToolActivityDataModel.kt
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/service/ManifestManager.kt
- ui/base-tool/src/test/kotlin/org/cru/godtools/base/tool/activity/MultiLanguageToolActivityDataModelTest.kt
- ui/cyoa-renderer/src/test/kotlin/org/cru/godtools/tool/cyoa/MockDatabaseModule.kt
- ui/tract-renderer/src/test/kotlin/org/cru/godtools/tool/tract/MockDatabaseModule.kt
- ui/tract-renderer/src/test/kotlin/org/cru/godtools/tract/activity/TractActivityTest.kt
- update ManifestManager to no longer use getLatestTranslationLiveData
- stop using getLatestTranslationLiveData() for MultiLanguageToolActivityDataModel
- remove unused getLatestTranslationLiveData method
> GT-1949 Remove unnecessary LiveData variant of a TranslationsRepository method

- app/src/main/kotlin/org/cru/godtools/activity/BasePlatformActivity.kt
- app/src/main/kotlin/org/cru/godtools/ui/drawer/DrawerMenuLayout.kt
- correctly close the navigation drawer for platform activities
- dismiss the drawer from within the layout itself
> GT-1923 Some minor fixes to the nav drawer

- buildSrc/src/main/kotlin/AndroidConfiguration.kt
There seems to be some buggy behavior with how test fixtures, manifest placeholders, and removing xml nodes via manifest mergers works.
- Okta requires a manifest placeholder when using their library
- If that library is on the classpath for tests it throws an error if no placeholder is defined
- You can remove the merged parts of the AndroidManifest.xml that use the placeholder to avoid the merger error
- Moving the removal xml into a test fixture AndroidManifest.xml sometimes works and sometimes doesn't
- This behavior was very inconsistent, with a straightforward usage not working, but adding the dependency through gradle buildSrc working until you upgrade to the latest version of jetpack compose.
- When we define a manifest placeholder for testing and still merge the test fixture …
> GT-1975 fix manifest merge errors for tests when Okta is on the classpath

- library/sync/src/main/kotlin/org/cru/godtools/sync/GodToolsSyncService.kt
- library/sync/src/test/kotlin/org/cru/godtools/sync/GodToolsSyncServiceTest.kt
- cleanup GodToolsSyncServiceTest
- correctly handle exceptions when running syncUserCounters()
> GT-1992 correctly handle exceptions when running syncUserCounters()

- library/account/src/main/kotlin/org/cru/godtools/account/provider/facebook/FacebookAccountProvider.kt
- library/account/src/test/kotlin/org/cru/godtools/account/provider/facebook/FacebookAccountProviderTest.kt
- library/api/src/main/kotlin/org/cru/godtools/api/model/AuthToken.kt
If authentication fails because of a bad access_token, try refreshing the token before giving up
> GT-1950 refresh the facebook access_token on auth failure

- library/db/src/main/kotlin/org/cru/godtools/db/repository/AttachmentsRepository.kt
- library/db/src/main/kotlin/org/keynote/godtools/android/db/repository/LegacyAttachmentsRepository.kt
- library/db/src/test/kotlin/org/cru/godtools/db/repository/AttachmentsRepositoryIT.kt
- ui/shortcuts/src/main/kotlin/org/cru/godtools/shortcuts/GodToolsShortcutManager.kt
- ui/shortcuts/src/test/kotlin/org/cru/godtools/shortcuts/GodToolsShortcutManagerDispatcherTest.kt
- ui/shortcuts/src/test/kotlin/org/cru/godtools/shortcuts/GodToolsShortcutManagerTest.kt
- monitor for changes to attachments via the AttachmentsRepository
- use the AttachmentsRepository to lookup an attachment
> GT-1900 Migrate some more DB interactions to the AttachmentsRepository

- library/db/src/main/kotlin/org/cru/godtools/db/repository/ToolsRepository.kt
- library/db/src/main/kotlin/org/keynote/godtools/android/db/repository/LegacyToolsRepository.kt
- library/db/src/test/kotlin/org/cru/godtools/db/repository/ToolsRepositoryIT.kt
- library/model/src/main/kotlin/org/cru/godtools/model/Attachment.kt
- library/sync/src/main/kotlin/org/cru/godtools/sync/repository/SyncRepository.kt
- library/sync/src/main/kotlin/org/cru/godtools/sync/task/ToolSyncTasks.kt
- library/sync/src/test/kotlin/org/cru/godtools/sync/repository/SyncRepositoryTest.kt
- add a new method for syncs that will delete a tool if it's not currently favorited
- update the SyncRepository to utilize the new ToolsRepository.deleteIfNotFavorite() method
- delete unused deleteBlocking method
> GT-1897 Update tools sync logic to better utilize the ToolsRepository

- library/analytics/src/main/kotlin/org/cru/godtools/analytics/appsflyer/AppsFlyerAnalyticsService.kt
- library/analytics/src/main/kotlin/org/cru/godtools/analytics/model/AnalyticsBaseEvent.kt
- library/analytics/src/main/kotlin/org/cru/godtools/analytics/model/AnalyticsScreenEvent.kt
- library/analytics/src/main/kotlin/org/cru/godtools/analytics/model/AnalyticsSystem.kt
- library/analytics/src/test/kotlin/org/cru/godtools/analytics/appsflyer/AppsFlyerAnalyticsServiceTest.kt
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/analytics/model/ContentAnalyticsEventAnalyticsActionEvent.kt
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/analytics/model/ToolAnalyticsScreenEvent.kt
- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/analytics/model/ToolOpenedAnalyticsActionEvent.kt
- ui/cyoa-renderer/src/test/kotlin/org/cru/godtools/tool/cyoa/analytics/model/CyoaPageAnalyticsScreenEventTest.kt
- ui/lesson-renderer/src/test/kotlin/org/cru/godtools/tool/lesson/analytics/model/LessonPageAnalyticsScreenEventTest.kt
- ui/tract-renderer/src/test/kotlin/org/cru/godtools/tract/analytics/model/TractPageAnalyticsScreenEventTest.kt
- ui/tutorial-renderer/src/main/kotlin/org/cru/godtools/tutorial/analytics/model/TutorialAnalyticsScreenEvent.kt
- remove the AppsFlyer analytics system configuration for individual events
- don't log any AppsFlyer analytics events
- remove AppsFlyer AnalyticsSystem value
> GT-1534 Stop recording analytics events for AppsFlyer

- ui/shortcuts/src/main/kotlin/org/cru/godtools/shortcuts/GodToolsShortcutManager.kt
- ui/shortcuts/src/main/kotlin/org/cru/godtools/shortcuts/ShortcutModule.kt
- ui/shortcuts/src/test/kotlin/org/cru/godtools/shortcuts/GodToolsShortcutManagerDispatcherTest.kt
- ui/shortcuts/src/test/kotlin/org/cru/godtools/shortcuts/GodToolsShortcutManagerTest.kt
- add a unit test to ensure that canPinToolShortcut() doesn't crash for instant apps
- fully disable the shortcut manager when running as an InstantApp
- there is no need to expose the ShortcutManager.Dispatcher
> GT-1977 Disable the ShortcutManager for Instant Apps

- app/src/main/kotlin/org/cru/godtools/ui/dashboard/home/HomeViewModel.kt
- library/db/src/main/kotlin/org/cru/godtools/db/repository/AttachmentsRepository.kt
- library/db/src/main/kotlin/org/cru/godtools/db/repository/ToolsRepository.kt
- library/db/src/main/kotlin/org/keynote/godtools/android/db/repository/LegacyAttachmentsRepository.kt
- library/db/src/main/kotlin/org/keynote/godtools/android/db/repository/LegacyToolsRepository.kt
- library/db/src/test/kotlin/org/cru/godtools/db/repository/AttachmentsRepositoryIT.kt
- library/db/src/test/kotlin/org/cru/godtools/db/repository/ToolsRepositoryIT.kt
- library/model/src/main/kotlin/org/cru/godtools/model/Tool.kt
- ui/shortcuts/src/test/kotlin/org/cru/godtools/shortcuts/GodToolsShortcutManagerDispatcherTest.kt
- there is no need for toolsChangeFlow to not emit on start
- add a unit test for ToolsRepository.storeToolOrder
- update AttachmentsRepository.attachmentsChangeFlow() to always emit an initial value
- create a default implementation of getFavoriteToolsFlow()
> Make some tweaks to the DB repositories

- .github/workflows/onesky-download.yml
- adjust permissions for the onesky-download workflow
- fix name of the create PR step
- temporarily disable OneSky interactions to speed up tests
> Adjust the OneSky download workflow

- app/build.gradle.kts
- app/proguard-rules-retrofit2.pro
- app/proguard-rules.pro
- add missing retrofit Proguard rules
- the optimizationpasses directive does nothing in R8
> GT-2046 GT-2057 Fix proguard rules for AGP 8

- app/src/main/kotlin/org/cru/godtools/ui/dashboard/DashboardActivity.kt
- app/src/main/kotlin/org/cru/godtools/ui/dashboard/DashboardLayout.kt
- app/src/main/kotlin/org/cru/godtools/ui/dashboard/home/AllFavoritesLayout.kt
- app/src/main/kotlin/org/cru/godtools/ui/dashboard/home/HomeLayout.kt
- app/src/main/kotlin/org/cru/godtools/ui/dashboard/lessons/LessonsLayout.kt
- app/src/main/kotlin/org/cru/godtools/ui/dashboard/tools/ToolsLayout.kt
- app/src/main/kotlin/org/cru/godtools/ui/tooldetails/ToolDetailsLayout.kt
- app/src/main/kotlin/org/cru/godtools/ui/tools/ToolCardActions.kt
- app/src/main/kotlin/org/cru/godtools/ui/tools/ToolCardLayouts.kt
- introduce a ToolCardEvent class to capture all the events that can come out of tool cards
- introduce a DashboardHomeEvent to capture all the events HomeContent can emit
- introduce a DashboardLessonsEvent that represents events that can happen in the Lessons layout
- make the AllFavoritesList have a generic onEvent method
- finish updating DashboardLayout to use event objects for callbacks
> GT-1991 Switch to an event object for callbacks on the Dashboard

- ui/shortcuts/src/main/kotlin/org/cru/godtools/shortcuts/GodToolsShortcutManager.kt
- ui/shortcuts/src/test/kotlin/org/cru/godtools/shortcuts/GodToolsShortcutManagerDispatcherTest.kt
- don't generate a shortcut id for a null tool code
- use the appLanguage instead of the primaryLanguage when generating shortcuts
- don't use the parallel language when generating a shortcut
> GT-2074 Utilize the app language for shortcuts

- app/src/main/kotlin/org/cru/godtools/ui/tools/ToolViewModels.kt
- library/base/src/main/kotlin/org/cru/godtools/base/Settings.kt
- library/base/src/test/kotlin/org/cru/godtools/base/SettingsTest.kt
- library/initial-content/src/main/kotlin/org/cru/godtools/init/content/InitialContentImporter.kt
- library/initial-content/src/main/kotlin/org/cru/godtools/init/content/task/Tasks.kt
- library/initial-content/src/test/kotlin/org/cru/godtools/init/content/task/TasksTest.kt
- remove usage of the primaryLanguage from the initial content module
- update ToolViewModels to no longer use Settings.primaryLanguage
- remove ToolViewModels usage of Settings.parallelLanguage
- remove unused primary & parallel language settings
> GT-1983 Remove primary & parallel language settings

- app/src/main/kotlin/org/cru/godtools/ui/dashboard/home/AllFavoritesLayout.kt
- app/src/main/kotlin/org/cru/godtools/ui/dashboard/tools/ToolsLayout.kt
- app/src/main/kotlin/org/cru/godtools/ui/tooldetails/ToolDetailsLayout.kt
- app/src/main/kotlin/org/cru/godtools/ui/tools/ToolCardLayouts.kt
- app/src/main/kotlin/org/cru/godtools/ui/tools/ToolViewModels.kt
- use an overloaded get operator instead of separate initialize method
- make it possible to provide a viewModel to the ToolCard layouts
- update VariantToolCard to take a ToolViewModel instead of the code of the tool to render
- provide a ToolViewModel to the ToolCard when rendering
> GT-1991 Make some adjustments to how we access the ToolViewModel

- app/src/main/kotlin/org/cru/godtools/ui/tooldetails/ToolDetailsActivity.kt
- app/src/main/kotlin/org/cru/godtools/ui/tooldetails/ToolDetailsLayout.kt
- app/src/main/kotlin/org/cru/godtools/ui/tooldetails/ToolDetailsViewModel.kt
- app/src/main/kotlin/org/cru/godtools/ui/tools/ToolViewModels.kt
- app/src/test/kotlin/org/cru/godtools/ui/tooldetails/ToolDetailsViewModelTest.kt
- library/base/src/main/AndroidManifest.xml
- library/base/src/main/kotlin/org/cru/godtools/base/BaseModule.kt
- library/download-manager/build.gradle.kts
- library/download-manager/src/main/kotlin/org/cru/godtools/downloadmanager/compose/DownloadLatestTranslation.kt
- library/download-manager/src/test/kotlin/org/cru/godtools/downloadmanager/ExternalSingletonsModule.kt
- library/download-manager/src/test/kotlin/org/cru/godtools/downloadmanager/compose/DownloadLatestTranslationTest.kt
- ui/article-renderer/src/test/kotlin/org/cru/godtools/tool/article/MockBaseModule.kt
- ui/base/build.gradle.kts
- ui/base/src/main/AndroidManifest.xml
- ui/cyoa-renderer/src/test/kotlin/org/cru/godtools/tool/cyoa/MockBaseModule.kt
- ui/lesson-renderer/src/test/kotlin/org/cru/godtools/tool/lesson/MockBaseModule.kt
- ui/tract-renderer/src/test/kotlin/org/cru/godtools/tool/tract/MockBaseModule.kt
- track the additional language in ToolViewModels
- load the additionalTranslation instead of the removed parallelTranslation
- use the secondTranslation & secondLanguage in the ToolDetailsLayout
- we no longer need to load the additionalLanguage model in ToolDetailsViewModel
- create a DownloadLatestTranslation composable that will trigger a download of the latest translation
- move isConnectedStateFlow to the base module
- update DownloadLatestTranslation to only trigger when online
- we no longer need to trigger the download manager from ToolDetailsActivity
> GT-1991 Display additional language label only if translation is available

- app/build.gradle.kts
google-services 4.4.0 changed the location of an internal generated xml file that contained the firebase appId, the firebase app distribution plugin directly reads this file to auto-discover the appId, but currently doesn't know about the new location.
This PR works around the issue by directly setting the appId for the QA build that we distribute via app distribution.
relevant upstream bug report: https://github.com/google/play-services-plugins/issues/276
> GT-2131 workaround a bug after upgrading google-services plugin

- library/db/room-schemas/org.cru.godtools.db.room.GodToolsRoomDatabase/15.json
- library/db/src/main/kotlin/org/cru/godtools/db/repository/ToolsRepository.kt
- library/db/src/main/kotlin/org/cru/godtools/db/room/GodToolsRoomDatabase.kt
- library/db/src/main/kotlin/org/cru/godtools/db/room/dao/ToolsDao.kt
- library/db/src/main/kotlin/org/cru/godtools/db/room/entity/ToolEntity.kt
- library/db/src/main/kotlin/org/cru/godtools/db/room/entity/partial/ToolFavorite.kt
- library/db/src/main/kotlin/org/cru/godtools/db/room/repository/ToolsRoomRepository.kt
- library/db/src/test/kotlin/org/cru/godtools/db/repository/ToolsRepositoryIT.kt
- library/db/src/test/kotlin/org/cru/godtools/db/room/GodToolsRoomDatabaseMigrationIT.kt
- library/initial-content/src/main/kotlin/org/cru/godtools/init/content/task/Tasks.kt
- library/initial-content/src/test/kotlin/org/cru/godtools/init/content/task/TasksTest.kt
- library/model/src/main/kotlin/org/cru/godtools/model/ChangeTrackingModel.kt
- library/model/src/main/kotlin/org/cru/godtools/model/Tool.kt
- track changed fields on the ToolEntity
- support tracking changes to the isFavorite property via pinTool
- don't track changes when initializing favorites
- update unpinTool to track changes
> GT-1796 Track which tools were added/removed as favorites

- app/src/main/kotlin/org/cru/godtools/ui/drawer/DrawerViewModel.kt
- app/src/main/kotlin/org/cru/godtools/ui/login/LoginActivity.kt
- app/src/test/kotlin/org/cru/godtools/ExternalSingletonsModule.kt
- library/account/src/main/kotlin/org/cru/godtools/account/AccountModule.kt
- library/account/src/main/kotlin/org/cru/godtools/account/GodToolsAccountManager.kt
- library/account/src/main/kotlin/org/cru/godtools/account/provider/AccountProvider.kt
- library/account/src/main/kotlin/org/cru/godtools/account/provider/facebook/FacebookAccountProvider.kt
- library/account/src/main/kotlin/org/cru/godtools/account/provider/google/GoogleAccountProvider.kt
- library/account/src/test/kotlin/org/cru/godtools/account/GodToolsAccountManagerTest.kt
- library/account/src/test/kotlin/org/cru/godtools/account/provider/facebook/FacebookAccountProviderTest.kt
- library/analytics/src/main/kotlin/org/cru/godtools/analytics/firebase/FirebaseAnalyticsService.kt
- library/analytics/src/test/kotlin/org/cru/godtools/analytics/firebase/FirebaseAnalyticsServiceTest.kt
- library/api/src/main/kotlin/org/cru/godtools/api/MobileContentApiSessionInterceptor.kt
- library/sync/src/main/kotlin/org/cru/godtools/sync/task/UserCounterSyncTasks.kt
- library/sync/src/main/kotlin/org/cru/godtools/sync/task/UserFavoriteToolsSyncTasks.kt
- library/sync/src/main/kotlin/org/cru/godtools/sync/task/UserSyncTasks.kt
- library/sync/src/test/kotlin/org/cru/godtools/sync/task/UserCounterSyncTasksTest.kt
- library/sync/src/test/kotlin/org/cru/godtools/sync/task/UserFavoriteToolsSyncTasksTest.kt
- library/sync/src/test/kotlin/org/cru/godtools/sync/task/UserSyncTasksTest.kt
- library/user-data/src/main/kotlin/org/cru/godtools/user/data/UserManager.kt
- library/user-data/src/test/kotlin/org/cru/godtools/user/data/UserManagerTest.kt
- nothing requires isAuthenticated or userId to be suspendable
- make isAuthenticated and userId properties instead of methods
- there is no need to make SessionInterceptor.userId() suspendable
> Cleanup some AccountManager properties

- app/src/main/kotlin/org/cru/godtools/ui/dashboard/tools/ToolFilters.kt
- app/src/main/kotlin/org/cru/godtools/ui/dashboard/tools/ToolsViewModel.kt
- library/base/src/main/kotlin/org/cru/godtools/base/AppLanguage.kt
- library/base/src/main/kotlin/org/cru/godtools/base/LocalAppLanguage.kt
- resolve the appLanguage on a background thread
- use remember to prevent a new flow from being created every time LocalAppLanguage.current is called
- switch to a LazyColumn implementation of DropdownMenu for the languages filter
> GT-2168 Performance Improvements for Language Filter

- app/build.gradle.kts
- build-logic/src/main/kotlin/AndroidConfiguration.kt
- library/api/build.gradle.kts
- use a workaround to support transitioning :library:api to KSP
- convert app module to use KSP for Dagger
> Migrate a few more modules to use KSP

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/kotlin/org/cru/godtools/dagger/CircuitModule.kt
- app/src/main/kotlin/org/cru/godtools/ui/account/delete/DeleteAccountActivity.kt
- app/src/main/kotlin/org/cru/godtools/ui/account/delete/DeleteAccountLayout+Preview.kt
- app/src/main/kotlin/org/cru/godtools/ui/account/delete/DeleteAccountLayout.kt
- app/src/main/kotlin/org/cru/godtools/ui/account/delete/DeleteAccountModule.kt
- app/src/main/kotlin/org/cru/godtools/ui/account/delete/DeleteAccountPresenter.kt
- app/src/main/kotlin/org/cru/godtools/ui/account/delete/DeleteAccountScreen.kt
- app/src/main/kotlin/org/cru/godtools/ui/drawer/DrawerMenuLayout.kt
- app/src/main/res/values/strings_account.xml
- app/src/testDebug/kotlin/org/cru/godtools/ui/account/delete/DeleteAccountLayoutTest.kt
- app/src/testDebug/kotlin/org/cru/godtools/ui/account/delete/DeleteAccountPresenterTest.kt
- gradle/libs.versions.toml
- library/account/src/main/kotlin/org/cru/godtools/account/GodToolsAccountManager.kt
- library/account/src/test/kotlin/org/cru/godtools/account/GodToolsAccountManagerTest.kt
- library/api/src/main/kotlin/org/cru/godtools/api/UserApi.kt
Create a new Delete Account UI using Slack Circuit
> GT-2178 Add Support for a user deleting their account

- app/src/main/kotlin/org/cru/godtools/ui/languages/downloadable/DownloadableLanguagesLayout.kt
- app/src/main/kotlin/org/cru/godtools/ui/languages/downloadable/LanguageDownloadProgressIndicator+Preview.kt
- app/src/main/kotlin/org/cru/godtools/ui/languages/downloadable/LanguageDownloadProgressIndicator.kt
- app/src/main/kotlin/org/cru/godtools/ui/languages/downloadable/LanguageViewModels.kt
- library/db/src/main/kotlin/org/cru/godtools/db/repository/ToolsRepository.kt
- library/db/src/main/kotlin/org/cru/godtools/db/room/dao/ToolsDao.kt
- library/db/src/main/kotlin/org/cru/godtools/db/room/repository/ToolsRoomRepository.kt
- library/db/src/test/kotlin/org/cru/godtools/db/repository/ToolsRepositoryIT.kt
- add a repository method to get a flow of downloaded tools for types and a language
- create a LanguageDownloadProgressIndicator for the downloadable languages UI
- replace the Switch on the downloaded languages UI with a custom progres indicator
> GT-2198 Add a download progress indicator for the downloadable languages UI

- app/src/main/kotlin/org/cru/godtools/ui/drawer/DrawerMenuLayout.kt
- app/src/main/kotlin/org/cru/godtools/ui/drawer/DrawerMenuPresenter.kt
- app/src/main/kotlin/org/cru/godtools/ui/drawer/DrawerMenuScreen.kt
- app/src/main/kotlin/org/cru/godtools/ui/tooldetails/ToolDetailsLayout.kt
- app/src/main/kotlin/org/cru/godtools/ui/tooldetails/ToolDetailsPresenter.kt
- app/src/main/kotlin/org/cru/godtools/ui/tooldetails/ToolDetailsScreen.kt
- app/src/testDebug/kotlin/org/cru/godtools/ui/drawer/DrawerMenuPresenterTest.kt
- app/src/testDebug/kotlin/org/cru/godtools/ui/tooldetails/ToolDetailsLayoutTest.kt
- app/src/testDebug/kotlin/org/cru/godtools/ui/tooldetails/ToolDetailsPresenterTest.kt
- **Start refactoring DrawerMenuLayout to use a State object instead of the ViewModel**
- **create a DrawerMenuPresenter**
- **update ToolDetailsLayout to utilize DrawerMenuScreen.State**
> Create a DrawerMenuPresenter for use in Circuit layouts

- app/build.gradle.kts
sideloading an incorrect version leads to crashes if the sideloaded version doesn't contain the proper density resources
> GT-2379 Disable density splits

- app/src/main/kotlin/org/cru/godtools/ui/dashboard/filters/FilterMenu.kt
- app/src/main/kotlin/org/cru/godtools/ui/dashboard/filters/FilterMenuItem.kt
- app/src/main/kotlin/org/cru/godtools/ui/dashboard/lessons/LessonFilters.kt
- app/src/main/kotlin/org/cru/godtools/ui/dashboard/tools/ToolFilters.kt
- app/src/main/kotlin/org/cru/godtools/ui/dashboard/tools/ToolsLayout.kt
- app/src/main/kotlin/org/cru/godtools/ui/dashboard/tools/ToolsPresenter.kt
- app/src/main/kotlin/org/cru/godtools/ui/dashboard/tools/ToolsScreen.kt
- app/src/testDebug/kotlin/org/cru/godtools/ui/dashboard/tools/ToolFiltersPaparazziTest.kt
- app/src/testDebug/kotlin/org/cru/godtools/ui/dashboard/tools/ToolFiltersTest.kt
- app/src/testDebug/kotlin/org/cru/godtools/ui/dashboard/tools/ToolsPresenterTest.kt
- **centralize the FilterMenuItem composable**
- **create a shared FilterMenu.UiState to standardize filter menu state**
- **update the ToolsScreen to use FilterMenu.UiState for the language and category filter menus**
> Centralize some Dashboard filter logic

- ui/base-tool/src/main/kotlin/org/cru/godtools/base/tool/ui/controller/AccordionController.kt
Previously observing on the accordion lifecycle would cause the observer to continue after a section had been destoryed.
This would lead to the destroyed section trying to become a zombie the next time the active section was updated.
> GT-2660 Prevent Zombie Accordion Sections
